### ISSUE TITLE
Could not import accounts: could not write accounts: file already exists without proper 0600 permissions

### ISSUE THREAD

**Issue by aaqr12** [prysmaticlabs/prysm#8180] opened 2020-12-26 04:46 UTC
Currently, one validatorkey is used as a validator. Currently, we have added one validator key with the same mnemonic, and the following error appears. What should I do?

Could not import accounts: could not write accounts: file already exists without proper 0600 permissions

validator is currently in operation, so I don't know if I have to delete my wallet and recreate it.The 32 eth deposit of the new key has already been completed.

[2020-12-26 16:49:51]  WARN flags: Running on ETH2 Mainnet
Wallet password: 
Enter the password for your imported accounts: 
Importing accounts, this may take a while...
Importing accounts... 100% [==========================================]  [0s:0s]
[2020-12-26 16:50:00] FATAL accounts: Could not import accounts: could not write accounts: file already exists without proper 0600 permissions
staker@staker-desktop:~$ 

os:Ubuntu 20.04.1 LTS 64bit

**Comment by yv989c** [comment] 2020-12-27 02:50
This is a duplicate of https://github.com/prysmaticlabs/prysm/issues/7898

**Comment by yv989c** [comment] 2020-12-27 03:16
Hi @aaqr12 , can you check your prysm wallet file and ensure that the user you are using to import the validator keys has the read and write permissions on that file? I'm not familiar with Linux but I think this link could help you to set the appropriate permissions on that file if needed: https://chmodcommand.com/chmod-0600/

Currently there's a bug on Windows related to this (https://github.com/prysmaticlabs/prysm/issues/7898), but I believe Linux is not affected.

**Comment by aaqr12** [comment] 2020-12-27 14:38
It's the same authority that I imported before, but it doesn't seem to work after updating the prism. With the help of someone else, I changed my wallet and proceeded with it. Thank you for your answer.

**Closed** 2021-01-04 23:32 UTC
Labels: Accounts, Bug
