### ISSUE TITLE
"The genesis validators root received from the beacon node does not match what is in your validator database"

### ISSUE THREAD

**Issue by kbrannon95** [prysmaticlabs/prysm#10279] opened 2022-02-24 16:09 UTC
Hi all,

I am currently in the end phases of deployed validator on Prater Testnet. My Geth node is completely synced and the beacon-chain finished syncing this morning, but when I go to start the validator I get a fatal error: 

level = error msg = "The genesis validators root received from the beacon node does not match what is in your validator database. This could indicate that this is a database meant for another network" 

level = fatal msg = Could not determine if beacon chain started: genesis validators root from beacon node (0x043db0d9a83813551ee2f33450d23797757d430911a9320530ad8a0eabc43efb) does not match root saved in validator db (0x77346b6c77f7e79723ad000eef295c882f670449ea7544fcc10d6ad66925195b)

I've tried searching through documentation for a solution with no luck. I would try clearing the database and syncing again but the process took nearly 3 days.

**Comment by rauljordan** [comment] 2022-08-15 21:19
hi @kbrannon95 I realized you never received an answer to this and I sincerely apologize. I think the issue is in your validator database, so clearing your validator DB would be enough. Will close this for now but please let me know if this does not resolve your problem or if you still need help

**Comment by rauljordan** [comment] 2022-08-15 21:19
Our Discord https://discord.gg/prysmaticlabs is a better place for us to answer some of these debugging questions

**Closed by rauljordan** 2022-08-15 21:19 UTC
