### ISSUE TITLE
More efficient VC <-> BN DomainData interaction

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5680] opened 2020-04-29 16:31 UTC
# 🚀 Feature Request

### Description

Does every signing key needs own request to `DomainData`?  
BN <-> VC's domain data interaction can be consolidated to one round trip.

Currently:
<img width="540" alt=" " src="https://user-images.githubusercontent.com/21316537/80621445-24c6e580-89fc-11ea-8743-97f2278ac955.png">

**Comment by prestonvanloon** [comment] 2020-04-29 16:52
There is a feature flag to cache the validator side (https://github.com/prysmaticlabs/prysm/pull/4914) but it was causing major issues. We can pick it up again and see what's the issue.

**Comment by alonmuroch** [comment] 2020-05-17 07:10
@prestonvanloon @rauljordan since this was bumped to high priority maybe I could take a swing at this.

@prestonvanloon what issues the caching caused?

**Comment by prestonvanloon** [comment] 2020-05-17 16:48
@alonmuroch The issue was that signatures were failing to verify for all objects produce from a validator with this flag enabled. `--enable-domain-data-cache`. If you run a local testnet, try adding this flag to half of the validators and you should be able to reproduce the issue. 

I'll tentatively assign to you for investigation, please keep us updated on the issue as you work on it.

**Comment by prestonvanloon** [comment] 2020-05-18 17:25
We can probably accept this flag as "working" if it were to pass end-to-end tests. I attempted to add this flag to e2e over the weekend but did not have much success.

**Comment by terencechain** [comment] 2020-05-18 17:37
I have been running with `--enable-domain-data-cache` on my local 4k validators for 2 weeks.. No issue observed from my end

**Comment by alonmuroch** [comment] 2020-05-19 09:21
I've been running a validator with the flag on and seems to work fine as well. 
e2e crashes for me but probably because I'm doing something wrong..

**Comment by alonmuroch** [comment] 2020-05-20 16:31
@prestonvanloon e2e passes on my end

**Closed** 2020-05-20 18:46 UTC
Labels: Help Wanted, Priority: High
