### ISSUE TITLE
Crash after a few minutes (Beacon Chain)

### ISSUE THREAD

**Issue by mog3n** [prysmaticlabs/prysm#4236] opened 2019-12-10 00:25 UTC
Following the steps on https://prylabs.net/participate I've encountered a bug causing beacon-chain to crash after a few minutes. It was launched under a Ubuntu Xenial (16.04) virtual machine with VirtualBox.

After running
```
docker run -it -v $HOME/prysm:/data -p 4000:4000 \
  gcr.io/prysmaticlabs/prysm/beacon-chain:latest \
  --datadir=/data \
  --init-sync-no-verify
```

I'm not too sure how to debug this. Running the latest via
`docker pull gcr.io/prysmaticlabs/prysm/beacon-chain:latest`

It seems to connect to a few peers, and then downloads the beacon chain but after a while i encounter this:
```
goroutine 46802 [select]:
github.com/libp2p/go-yamux.(*Stream).Read(0xc0001360e0, 0xc000fb960e, 0x238, 0x9f2, 0x0, 0x0, 0x0)
        external/com_github_libp2p_go_yamux/stream.go:113 +0x1f5
github.com/libp2p/go-libp2p-swarm.(*Stream).Read(0xc003d93590, 0xc000fb960e, 0x238, 0x9f2, 0x60e, 0x0, 0x0)
        external/com_github_libp2p_go_libp2p_swarm/swarm_stream.go:64 +0x61
github.com/multiformats/go-multistream.(*lazyClientConn).Read(0xc00219e3f0, 0xc000fb960e, 0x238, 0x9f2, 0x60e, 0x0, 0x0)
        external/com_github_multiformats_go_multistream/lazyClient.go:75 +0xa8
github.com/libp2p/go-libp2p/p2p/host/basic.(*streamWrapper).Read(0xc002a8c740, 0xc000fb960e, 0x238, 0x9f2, 0x60e, 0x0, 0x0)
        external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:765 +0x52
github.com/libp2p/go-libp2p-circuit.(*Conn).Read(0xc0037c0e10, 0xc000fb960e, 0x238, 0x9f2, 0x60e, 0x0, 0x0)
        external/com_github_libp2p_go_libp2p_circuit/conn.go:41 +0x51
io.ReadAtLeast(0x7fde64048860, 0xc0037c0e10, 0xc000fb9000, 0x846, 0x1000, 0x846, 0x4, 0x0, 0x0)
        GOROOT/src/io/io.go:310 +0x87
io.ReadFull(...)
        GOROOT/src/io/io.go:329
github.com/libp2p/go-msgio.(*reader).ReadMsg(0xc0023161c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        external/com_github_libp2p_go_msgio/msgio.go:229 +0x183
github.com/libp2p/go-libp2p-secio.(*etmReader).fill(0xc0012a4280, 0x846, 0x0)
        external/com_github_libp2p_go_libp2p_secio/rw.go:132 +0x38
github.com/libp2p/go-libp2p-secio.(*etmReader).Read(0xc0012a4280, 0xc002334920, 0xc, 0xc, 0x0, 0x0, 0x0)
        external/com_github_libp2p_go_libp2p_secio/rw.go:171 +0x2ae
io.ReadAtLeast(0x7fde6a1f99d0, 0xc001514800, 0xc002334920, 0xc, 0xc, 0xc, 0xc, 0x0, 0x0)
        GOROOT/src/io/io.go:310 +0x87
io.ReadFull(...)
        GOROOT/src/io/io.go:329
github.com/libp2p/go-yamux.(*Session).recvLoop(0xc0023ca000, 0x0, 0x0)
        external/com_github_libp2p_go_yamux/session.go:507 +0xe9
github.com/libp2p/go-yamux.(*Session).recv(0xc0023ca000)
        external/com_github_libp2p_go_yamux/session.go:486 +0x2b
created by github.com/libp2p/go-yamux.newSession
        external/com_github_libp2p_go_yamux/session.go:129 +0x386

goroutine 4657 [select]:
github.com/libp2p/go-yamux.(*Session).AcceptStream(0xc000147450, 0xc000136000, 0x0, 0x46b1de)
        external/com_github_libp2p_go_yamux/session.go:225 +0xb6
github.com/libp2p/go-libp2p-yamux.(*conn).AcceptStream(0xc000147450, 0xc000d4cf20, 0x18, 0xc0015fc600, 0xe656f4)
        external/com_github_libp2p_go_libp2p_yamux/yamux.go:38 +0x2b
github.com/libp2p/go-libp2p-swarm.(*Conn).start.func1(0xc001c5b4a0)
        external/com_github_libp2p_go_libp2p_swarm/swarm_conn.go:98 +0x12d
created by github.com/libp2p/go-libp2p-swarm.(*Conn).start
        external/com_github_libp2p_go_libp2p_swarm/swarm_conn.go:93 +0x3f

goroutine 3585 [select]:
github.com/libp2p/go-yamux.(*Stream).Read(0xc000f6c1c0, 0xc000c4c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        external/com_github_libp2p_go_yamux/stream.go:113 +0x1f5
github.com/libp2p/go-libp2p-swarm.(*Stream).Read(0xc0015e4190, 0xc000c4c000, 0x1000, 0x1000, 0xc0019eaed8, 0x463b5c, 0xc0019eacd8)
        external/com_github_libp2p_go_libp2p_swarm/swarm_stream.go:64 +0x61
github.com/multiformats/go-multistream.(*lazyServerConn).Read(0xc002be6600, 0xc000c4c000, 0x1000, 0x1000, 0x8, 0xc0019eaeb8, 0xc0005cbe00)
        external/com_github_multiformats_go_multistream/lazyServer.go:32 +0x76
github.com/libp2p/go-libp2p/p2p/host/basic.(*streamWrapper).Read(0xc002ecad80, 0xc000c4c000, 0x1000, 0x1000, 0x2, 0x2, 0x0)
        external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:765 +0x52
bufio.(*Reader).fill(0xc002e13380)
        GOROOT/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).ReadByte(0xc002e13380, 0x0, 0x0, 0x60)
        GOROOT/src/bufio/bufio.go:252 +0x39
encoding/binary.ReadUvarint(0x1a759c0, 0xc002e13380, 0xf6871, 0xe3d24d, 0xc0019eaed8)
        GOROOT/src/encoding/binary/varint.go:110 +0x7b
github.com/gogo/protobuf/io.(*varintReader).ReadMsg(0xc002e7fe80, 0x1a9ac40, 0xc0043e5b20, 0x0, 0x0)
        external/com_github_gogo_protobuf/io/varint.go:110 +0x3e
github.com/libp2p/go-libp2p-pubsub.(*PubSub).handleNewStream(0xc000152360, 0x1abc7c0, 0xc002ecad80)
        external/com_github_libp2p_go_libp2p_pubsub/comm.go:36 +0xcf
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1(0xc001d58de2, 0xe, 0x7fde6a1b6718, 0xc002ecad80, 0xe, 0xc000080220)
        external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:393 +0x9d
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
        external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:291 +0x6a2

goroutine 62059 [chan receive]:
github.com/paulbellamy/ratecounter.(*RateCounter).run.func1(0xc0029f58c0)
        external/com_github_paulbellamy_ratecounter/ratecounter.go:51 +0x8d
created by github.com/paulbellamy/ratecounter.(*RateCounter).run
        external/com_github_paulbellamy_ratecounter/ratecounter.go:48 +0x52

goroutine 4705 [select, 1 minutes]:
github.com/libp2p/go-yamux.(*Stream).Read(0xc0012840e0, 0xc00188b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        external/com_github_libp2p_go_yamux/stream.go:113 +0x1f5
github.com/libp2p/go-libp2p-swarm.(*Stream).Read(0xc000ef14a0, 0xc00188b000, 0x1000, 0x1000, 0xc000d5ed80, 0xc00045d500, 0xc000c5ae28)
        external/com_github_libp2p_go_libp2p_swarm/swarm_stream.go:64 +0x61
bufio.(*Reader).fill(0xc0000d3860)
        GOROOT/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).ReadByte(0xc0000d3860, 0xc0015b3e00, 0x1000, 0x60)
        GOROOT/src/bufio/bufio.go:252 +0x39
encoding/binary.ReadUvarint(0x1a759c0, 0xc0000d3860, 0x1000, 0x1000, 0x7fde6a1b6568)
        GOROOT/src/encoding/binary/varint.go:110 +0x7b
github.com/gogo/protobuf/io.(*varintReader).ReadMsg(0xc0015b3e00, 0x1a9ac40, 0xc0011ac8c0, 0x1a8a100, 0xc0015b3e00)
        external/com_github_gogo_protobuf/io/varint.go:110 +0x3e
github.com/libp2p/go-libp2p-pubsub.(*PubSub).handlePeerEOF(0xc000152360, 0x1aa60c0, 0xc0005fed40, 0x1abc6c0, 0xc000ef14a0)
        external/com_github_libp2p_go_libp2p_pubsub/comm.go:91 +0x106
created by github.com/libp2p/go-libp2p-pubsub.(*PubSub).handleNewPeer
        external/com_github_libp2p_go_libp2p_pubsub/comm.go:80 +0x432
```

**Comment by prestonvanloon** [comment] 2019-12-10 17:01
@mog3n Do you happen to have the full error by chance? The part you pasted is missing part of it. 
If possible, upload the full log. Thanks!

**Comment by mog3n** [comment] 2019-12-10 21:59
Hey @prestonvanloon ! I got a different error this time.
The command I ran was:
`docker run -v $HOME/prysm-data:/data -p 4000:4000   --name beacon-node   gcr.io/prysmaticlabs/prysm/beacon-chain:latest   --no-genesis-delay   --datadir=/data --p2p-max-peers=40 --p2p-host-ip=99.244.106.108 |& tee -a log.txt`

```time="2019-12-10 21:57:18" level=info msg="Processing block 17304/210446 - estimated time remaining 1h43m0s" blocksPerSecond=31.2 peers="7/9" prefix=initial-sync
panic: could not process blockCopy from fork choice service: could not execute state transition: could not process block: could not process block header: parent root 0x0a33490755c146a7359647871707e388e37dbc67d4701c468dacf26988d72dd9 does not match the latest block header signing root in state 0xab5db296c4fc0533b2f22f9dc10493baaceeff4b3bf243ca074068c9fd858b28

goroutine 266 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).Start(0xc00039b3e0)
	beacon-chain/sync/initial-sync/service.go:133 +0xf1c
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
	shared/service_registry.go:44 +0x23e```

Here's the full output, though most of it is not useful: https://gist.githubusercontent.com/mog3n/28f082b41f9303633c50fd886ac1eeba/raw/7f3106697a0c5c22b3b740686159c34dee989202/log.txt

**Comment by mog3n** [comment] 2019-12-10 22:07
Update: I ran the command again and the original error is back: https://gist.github.com/mog3n/84540b49e48febc5f6ef892a9f63ef2a
Thanks!

**Comment by mog3n** [comment] 2019-12-11 02:13
I ran the command on a native Ubuntu device and the same error seems to have appeared: https://gist.github.com/mog3n/0dd8ef05249f813e3c7f4b505a08ec5d

**Comment by nisdas** [comment] 2019-12-11 03:01
This errors seem to be pointing to a deeper issue in your machine 
```
unexpected fault address 0x14885c0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x14885c0 pc=0x14d0dac]
```
you mentioned you were running with 
>Ubuntu Xenial (16.04) virtual machine with VirtualBox.

If possible, could you try with a more current version of Ubuntu ? ex: Bionic(18.04)

**Comment by mog3n** [comment] 2019-12-11 04:07
@nisdas I've now run it on Ubuntu Bionic 18.04 LTS, and i'm getting the same error. https://gist.github.com/mog3n/d4e6ea7352512ee3ca27869d43b59120
```
unexpected fault address 0xc00f501b48
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc00f501b48 pc=0xa7cf2c]
```

Thanks

**Comment by nisdas** [comment] 2019-12-11 04:41
Hey I opened a PR https://github.com/prysmaticlabs/prysm/pull/4252 , this should resolves your error. Can you try it and let me know if it fixes it for you ?

**Comment by rauljordan** [comment] 2020-01-08 02:30
Closing this for now as there were confirmed segfaults in SSZ that have since then been resolved

**Closed by rauljordan** 2020-01-08 02:30 UTC
