### ISSUE TITLE
Wrong version is shown when running latest docker images 

### ISSUE THREAD

**Issue by ChristianCoenen** [prysmaticlabs/prysm#6798] opened 2020-07-31 08:10 UTC
# 💎 Issue
Wrong version is shown when running latest docker images 

### Background

1. Removed all files / container / images that I had for Onyx. 
2. Fetched the latest images (If I understood the 'Build at' line in the screenshot correctly, it can be seen that I really started the latest one). 
3. Went through the Medalla docker setup documentation to run the validator and beacon chain

### Description
It seems like everything is working except that it is showing the wrong version for both the beacon chain and validator as seen in the screenshot.

edit: I just checked the image-digest, which is the same as the latest on docker hub. So I am definitely running the latest version

![Screenshot 2020-07-31 at 09 17 15](https://user-images.githubusercontent.com/22744609/89014480-d6382880-d315-11ea-8018-1f86e70e5846.png)

**Comment by prestonvanloon** [comment] 2020-07-31 18:17
Thanks for the report. This is a problem with our CI infrastructure. Here's whats going on.

1. When a PR merges to master, we immediately build and push docker images for that commit.
1. When we are evaluating a release candidate, we let it soak in a production environment for several days
1. After a release candidate has passed all of our automated and manual testing, then we create a release.

The problem here is that the docker image already existed before we tagged v1.0.0-alpha.17. We should consider rebuilding these images whenever we tag a new release so that the version reflects the appropriate git tag.

**Comment by rauljordan** [comment] 2020-08-07 05:14
Duplicate of #6561

**Comment by rauljordan** [comment] 2020-08-07 05:14
Actually, scratch that. They are similar but not the same issue

**Comment by shayzluf** [comment] 2020-09-22 10:10
seems like a ci issue @prestonvanloon please reassign to me if you find it inappropriate

**Comment by prestonvanloon** [comment] 2020-09-26 00:38
We don;t have a solution for this yet, but I am probably the most appropriate owner at the moment. Thanks

**Comment by prestonvanloon** [comment] 2020-11-20 20:14
Removing from v1 milestone. We'll have a better pipeline in place soon, but this is not a milestone blocker.

**Comment by prestonvanloon** [comment] 2022-09-30 04:15
This has been fixed for some time. Thanks @rauljordan

**Closed** 2022-09-30 04:15 UTC
Labels: CI
