### ISSUE TITLE
Docker images' creation date incorrect

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#6561] opened 2020-07-11 09:01 UTC
# 🐞 Bug Report

### Description

Prysm's Docker images for `validator`, `beacon-chain` and `slasher` have all the same creation date 50 years ago.

### Has this worked before in a previous version?

No

## 🔬 Minimal Reproduction

Run
```
docker images
```

or visit https://console.cloud.google.com/gcr/images/prysmaticlabs/GLOBAL/prysm/beacon-chain?gcrImageListsize=30

## 🔥 Error

![image](https://user-images.githubusercontent.com/54934211/87220611-a2e12a00-c365-11ea-82f3-6150fbedf014.png)

**Comment by prestonvanloon** [comment] 2020-07-12 19:21
I think this is a bug with [rules_docker](https://github.com/bazelbuild/rules_docker). We are building these images with `--stamp`, but the creation_time seems to be set to epoch 0.

Looking at rules_docker, they only set the creation timestamp when it is explicitly defined or ctx.attr.stamp is used. However, stamp is listed as "deprecated" so I am not sure the best approach. In any case, I modified this locally to set `-creationTime {BUILD_TIMESTAMP}` in the args for image config and there was an error where the placeholder was not replaced.

```
SUBCOMMAND: # //tools:cc_image [action 'ImageConfig tools/cc_image.0.config', configuration: 6bceea3a6a16503c54e0002f649115e014f212639f417aa9bc9de63a323389a9]
(cd /home/preston/.cache/bazel/_bazel_preston/6e220e5720b8243fd605645eb29a29ba/execroot/prysm && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
  bazel-out/host/bin/external/io_bazel_rules_docker/container/go/cmd/create_image_config/linux_amd64_stripped/create_image_config -outputConfig bazel-out/k8-opt/bin/tools/cc_image.0.config -outputManifest bazel-out/k8-opt/bin/tools/cc_image.0.manifest -creationTime '{BUILD_TIMESTAMP}' -user root -layerDigestFile @bazel-out/k8-opt/bin/tools/cc_image-layer.tar.sha256 -baseConfig external/cc_image_base/image/config.json -architecture amd64 -operatingSystem linux)
ERROR: /home/preston/git/prysm/tools/BUILD.bazel:61:16: ImageConfig tools/cc_image.0.config failed (Exit 1) create_image_config failed: error executing command bazel-out/host/bin/external/io_bazel_rules_docker/container/go/cmd/create_image_config/linux_amd64_stripped/create_image_config -outputConfig bazel-out/k8-opt/bin/tools/cc_image.0.config ... (remaining 14 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
2020/07/12 12:17:10 Failed to override values in old image config and write to dst failed to create/update image config: failed to parse creation time from config: failed to parse "{BUILD_TIMESTAMP}" as RFC3339. Assumed format to be RFC3339 as it failed to parse as a float as well: parsing time "{BUILD_TIMESTAMP}" as "2006-01-02T15:04:05Z07:00": cannot parse "{BUILD_TIMESTAMP}" as "2006": bazel-out/k8-opt/bin/tools/cc_image.0.config
```

https://github.com/bazelbuild/rules_docker/blob/849d6d665e06cb33e5a250a3c42818b14567def2/container/image.bzl#L136-L141 

We'll have to file a bug in rules_docker, I think.

**Comment by prestonvanloon** [comment] 2020-07-12 19:29
Filed https://github.com/bazelbuild/rules_docker/issues/1554

**Comment by terencechain** [comment] 2020-07-13 14:16
Marking this as blocked. We need resolution from bazelbuild/rules_docker#1554

**Comment by pinglamb** [comment] 2020-11-21 15:44
It seems to be by design so that the build is reproducible. https://github.com/bazelbuild/rules_docker/issues/52#issuecomment-308490078

**Comment by pingnamo** [comment] 2020-11-21 16:32
The main reason for `stamp` not working is that `go_image` doesn't support that: https://github.com/bazelbuild/rules_docker/pull/560. It doesn't pass the `stamp` or `creation_time` config to the underlying `container_image` call.

The `container_bundle` `stamp` option (which is deprecated) is more for the image tag, it allows us to substitute `{BUILD_TIMESTAMP}` into tag if we want to (e.g. `v0.1-1605975953`).

We can have the creation timestamp back if we define the build rule like this:

```
# Extra step to stamp the go_image output
container_image(
    name = "image_with_creation_time",
    base = "image",
    stamp = True,
)

container_bundle(
    name = "image_bundle",
    images = {
        "gcr.io/prysmaticlabs/prysm/validator:latest": ":image_with_creation_time",
        "gcr.io/prysmaticlabs/prysm/validator:{DOCKER_TAG}": ":image_with_creation_time",
        "index.docker.io/prysmaticlabs/prysm-validator:latest": ":image_with_creation_time",
        "index.docker.io/prysmaticlabs/prysm-validator:{DOCKER_TAG}": ":image_with_creation_time",
    },
    tags = ["manual"],
)
```

but as suggested in https://github.com/bazelbuild/rules_docker/issues/52#issuecomment-308490078, it seems to be by design for reproducible build. (`distroless` also has 50 years old image)

```
gcr.io/distroless/base                                   latest                      972b93457774        50 years ago        16.9MB
```

**Comment by pinglamb** [comment] 2020-11-21 16:38
The main reason for `stamp` not working is that `go_image` doesn't support that: https://github.com/bazelbuild/rules_docker/pull/560. It doesn't pass the `stamp` or `creation_time` config to the underlying `container_image` call.

The `container_bundle` `stamp` option (which is deprecated) is more for the image tag, it allows us to substitute `{BUILD_TIMESTAMP}` into tag if we want to (e.g. `v0.1-1605975953`).

We can have the creation timestamp back if we define the build rule like this:

```
# Extra step to stamp the go_image output
container_image(
    name = "image_with_creation_time",
    base = "image",
    stamp = True,
)

container_bundle(
    name = "image_bundle",
    images = {
        "gcr.io/prysmaticlabs/prysm/validator:latest": ":image_with_creation_time",
        "gcr.io/prysmaticlabs/prysm/validator:{DOCKER_TAG}": ":image_with_creation_time",
        "index.docker.io/prysmaticlabs/prysm-validator:latest": ":image_with_creation_time",
        "index.docker.io/prysmaticlabs/prysm-validator:{DOCKER_TAG}": ":image_with_creation_time",
    },
    tags = ["manual"],
)
```

but as suggested in https://github.com/bazelbuild/rules_docker/issues/52#issuecomment-308490078, it seems to be by design for reproducible build. (`distroless` also has 50 years old image)

```
gcr.io/distroless/base                                   latest                      972b93457774        50 years ago        16.9MB
```

**Comment by pinglamb** [comment] 2020-11-21 16:40
@terencechain @prestonvanloon If we want to add the timestamp I can draft a PR with the above changes, or we can close this saying it is expected behaviour.

**Comment by prestonvanloon** [comment] 2020-11-21 18:16
@pinglamb If it's not a lot of work, please draft a PR and I can take a look. Thanks!

**Closed** 2020-11-21 21:37 UTC
Labels: Blocked
