### ISSUE TITLE
[Pyrmont] Beacon chain stopped syncing for unknown reason

### ISSUE THREAD

**Issue by sknuth** [prysmaticlabs/prysm#7905] opened 2020-11-22 17:20 UTC
# 🐞 Bug Report

### Description

Hello, I would like to report a strange behaviour. my prism validator on pyrmont has suddenly stopped attesting.
when I discovered the issue : 
the beacon logs showed :
```
nov. 22 12:17:09 sknuth prysm.sh[27116]: time="2020-11-22 12:17:09" level=warning msg="Range is not processed" err="Range had no valid 
blocks to process" prefix=initial-sync
and the validator logs :
nov. 22 12:12:35 sknuth prysm.sh[9552]: time="2020-11-22 12:12:35" level=error msg="Could not check if validators are exited" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
nov. 22 12:12:39 sknuth prysm.sh[9552]: time="2020-11-22 12:12:39" level=error msg="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
nov. 22 12:12:39 sknuth prysm.sh[9552]: time="2020-11-22 12:12:39" level=error msg="Failed to update assignments" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
```
I had to restart the beacon and validator services
Now it is working fine

### Has this worked before in a previous version?

Not reproduced on Medalla

## 🔬 Minimal Reproduction
Prysm is running as a systemd service with the following execution string :
ExecStart=/home/beacon/bin/prysm.sh beacon-chain --config-file /home/beacon/prysm-beacon.yaml

## 🔥 Error

I have traced the journal logs please find the first error 
```
nov. 22 09:09:57 sknuth prysm.sh[27116]: time="2020-11-22 09:09:57" level=warning msg="Could not update head" error="could not save head root in DB: no state or state summary found with head block root" prefix=blockchain

nov. 22 09:10:08 sknuth prysm.sh[27116]: time="2020-11-22 09:10:08" level=warning msg="No access to parent state" blockSlot=27650 error=<nil> prefix=sync

nov. 22 09:16:19 sknuth prysm.sh[27116]: time="2020-11-22 09:16:19" level=warning msg="Resolving fork due to new attestation: head at slot 27648 with weight 292496 is not eligible, finalizedEpoch 862 != 862, justifiedEpoch 863 != 864" prefix=blockchain

nov. 22 09:25:33 sknuth prysm.sh[27116]: time="2020-11-22 09:25:33" level=info msg="Fallen behind peers; reverting to initial sync to catch up" currentEpoch=866 peersEpoch=866 prefix=sync syncedEpoch=864
```
followed by : 
```
nov. 22 09:27:33 sknuth prysm.sh[27116]: time="2020-11-22 09:27:33" level=info msg="Processing block batch of size 52 starting from  0x29f6ad0a... 27680/27737 - estimated time remaining 21s" blocksPerSecond=2.6 peers=30 prefix=initial-sync
nov. 22 09:27:51 sknuth prysm.sh[27116]: time="2020-11-22 09:27:51" level=warning msg="Batch is not processed" err="missing state summary for finalized root" prefix=initial-sync
nov. 22 09:27:51 sknuth prysm.sh[27116]: time="2020-11-22 09:27:51" level=info msg="Synced to finalized epoch - now syncing blocks up to current head" headSlot=27738 prefix=initial-sync syncedSlot=27736
nov. 22 09:27:52 sknuth prysm.sh[27116]: time="2020-11-22 09:27:52" level=warning msg="Range is not processed" err="Range had no valid blocks to process" prefix=initial-sync
```

</code></pre>

## 🌍  Your Environment

I am running Ubuntu 16.4LTS 

**What version of Prysm are you running? (Which release)**

v1.0.0-beta.3

**Anything else relevant (validator index / public key)?**

validator index : 100445 
publick key : 0x80b84cc7b4cb9282b294dc4170d1d353e86ac0323ea92aaaf3316ac7453cf6f1a1b454ab7381a4477101f1a45bb50709

**Comment by 0xKiwi** [comment] 2020-11-27 20:16
Hello @sknuth thank you for reporting this!

@farazdagi any idea what could be going on here?

**Comment by levelboy** [comment] 2020-12-01 07:12
Happened the same for me:

Running Ubuntu 20.04
And Prysm version is v1.0.2 (but also had this on v1.0.1 and v1.0.0-beta.3

Validator Index: 105421 
Public Key: 0x818ae19143d47e6cc85a425d7b87952859606670222b12e91804bb0d3825292c2b42f05c7376037cbdb5ef1015db3f3a



Now the beacon chain is failing to sync with errors like this:
```
dec 01 09:10:40 freak-ProLiant-ML10 bash[841]: time="2020-12-01 09:10:40" level=info msg="Processing block 0x05c42c63... 89728/92152 - estimated time remaining 28s" blocksPerSecond=85.7 peers=30 prefix=initial-sync
dec 01 09:10:40 freak-ProLiant-ML10 bash[841]: time="2020-12-01 09:10:40" level=info msg="Processing block 0x06e5a389... 89760/92152 - estimated time remaining 27s" blocksPerSecond=87.2 peers=30 prefix=initial-sync
dec 01 09:10:40 freak-ProLiant-ML10 bash[841]: time="2020-12-01 09:10:40" level=warning msg="Range is not processed" err="Range had no valid blocks to process" prefix=initial-sync
dec 01 09:10:40 freak-ProLiant-ML10 bash[841]: time="2020-12-01 09:10:40" level=warning msg="Range is not processed" err="Range had no valid blocks to process" prefix=initial-sync
```

**Comment by nisdas** [comment] 2020-12-01 07:19
@levelboy can you confirm that this was indeed on `v1.0.2` ? 

what is the output of `--version` ?

**Comment by farazdagi** [comment] 2020-12-01 08:00
@levelboy also, if you've run your node with `--log-file filepath`, can you please share the full logs (archived copy attached to `sync-bugs` in discord will be ideal).

**Comment by levelboy** [comment] 2020-12-01 09:26
@nisdas sorry, I confirm that it's *NOT* `v1.0.2` . It is `v1.0.1`
```
beacon-chain version Prysm/v1.0.1/9d174d592735da35244d11f1cd44f47b469e9018. Built at: 2020-11-28 15:22:57+00:00
```

**Comment by levelboy** [comment] 2020-12-01 09:27
@farazdagi was not running  it with log-file, but started it with log file now

**Comment by farazdagi** [comment] 2020-12-01 09:28
> @farazdagi was not running it with log-file, but started it with log file now

Thank you! If it is not on `1.0.2` then this should be a known issue (which is fixed in `1.0.2`).

**Comment by yuilleb** [comment] 2020-12-08 05:45
This just happened to me as well on 1.0.2

`beacon-chain version Prysm/v1.0.2/b150acffca3d93e8cf1f404ff7e4602391017186. Built at: 2020-11-30 02:48:11+00:00
`

`Dec 08 05:23:11 wci-eth1 prysm-beacon-chain[463]: time="2020-12-08 05:23:11" level=info msg="Synced new block" block=0x2e7417bd... epoch=1512 finalizedEpoch=1510 finalizedRoot=0xbefdbb17... prefix=blockchain slot=48414 slotInEpoch=30
Dec 08 05:23:11 wci-eth1 prysm-beacon-chain[463]: time="2020-12-08 05:23:11" level=info msg="Finished applying state transition" attestations=6 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
Dec 08 05:23:23 wci-eth1 prysm-beacon-chain[463]: time="2020-12-08 05:23:23" level=info msg="Synced new block" block=0x492d1f72... epoch=1512 finalizedEpoch=1510 finalizedRoot=0xbefdbb17... prefix=blockchain slot=48415 slotInEpoch=31
Dec 08 05:23:23 wci-eth1 prysm-beacon-chain[463]: time="2020-12-08 05:23:23" level=info msg="Finished applying state transition" attestations=13 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
Dec 08 05:32:28 wci-eth1 prysm-beacon-chain[463]: time="2020-12-08 05:32:28" level=info msg="Fallen behind peers; reverting to initial sync to catch up" currentEpoch=1514 peersEpoch=1514 prefix=sync syncedEpoch=1512
Dec 08 05:32:28 wci-eth1 prysm-beacon-chain[463]: time="2020-12-08 05:32:28" level=warning msg="Batch is not processed" err="no good blocks in batch" prefix=initial-sync
Dec 08 05:32:30 wci-eth1 prysm-beacon-chain[463]: time="2020-12-08 05:32:30" level=info msg="Synced to finalized epoch - now syncing blocks up to current head" headSlot=48460 prefix=initial-sync syncedSlot=48415
Dec 08 05:32:30 wci-eth1 prysm-beacon-chain[463]: time="2020-12-08 05:32:30" level=warning msg="Range is not processed" err="Range had no valid blocks to process" prefix=initial-sync
Dec 08 05:32:30 wci-eth1 prysm-beacon-chain[463]: time="2020-12-08 05:32:30" level=info msg="Processing block 0x1e11a528... 48448/48460 - estimated time remaining 2m0s" blocksPerSecond=0.1 peers=32 prefix=initial-sync
Dec 08 05:32:30 wci-eth1 prysm-beacon-chain[463]: time="2020-12-08 05:32:30" level=warning msg="Range is not processed" err="Range had no valid blocks to process" prefix=initial-sync

$ date
Tue Dec  8 05:42:38 UTC 2020
`

**Comment by farazdagi** [comment] 2020-12-08 06:52
@yuilleb are those full logs? Can you please share logs of what happened btw `05:32:30` and `05:47:22`? Node seems to fall behind, and drop from the normal sync back to initial-sync (to catch up), but then nothing happens?

**Comment by yuilleb** [comment] 2020-12-08 06:56
@farazdagi Yes sorry, I should have copied the line preceding `05:47:22`, but yes the log right before that is `05:32:30`. Nothing happened in between. No new logs were generated until I tried to gracefully stop the process.

**Comment by yuilleb** [comment] 2021-01-16 18:10
Seems to have happened again today on version:

`beacon-chain version Prysm/v1.0.5/2428880058c0e8183bd33ec04c3a0656ec471deb. Built at: 2020-12-14 17:23:54+00:00`

I've been running v1.0.5 for almost exactly a month now with no outages or restarts.

It appears now the dead lock occurs sooner, immediately after `msg="Fallen behind peers; reverting to initial sync to catch up"` there are no further outputs:

```
time="2021-01-16 17:38:23" level=info msg="Finished applying state transition" attestations=34 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2021-01-16 17:38:47" level=info msg="Synced new block" block=0x17445991... epoch=10402 finalizedEpoch=10400 finalizedRoot=0x424cab94... prefix=blockchain slot=332892 slotInEpoch=28
time="2021-01-16 17:38:47" level=info msg="Finished applying state transition" attestations=38 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2021-01-16 17:38:59" level=info msg="Synced new block" block=0x0b8445d0... epoch=10402 finalizedEpoch=10400 finalizedRoot=0x424cab94... prefix=blockchain slot=332893 slotInEpoch=29
time="2021-01-16 17:38:59" level=info msg="Finished applying state transition" attestations=37 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2021-01-16 17:39:11" level=info msg="Synced new block" block=0xa436cc85... epoch=10402 finalizedEpoch=10400 finalizedRoot=0x424cab94... prefix=blockchain slot=332894 slotInEpoch=30
time="2021-01-16 17:39:11" level=info msg="Finished applying state transition" attestations=23 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2021-01-16 17:39:24" level=info msg="Synced new block" block=0x9956c49b... epoch=10402 finalizedEpoch=10400 finalizedRoot=0x424cab94... prefix=blockchain slot=332895 slotInEpoch=31
time="2021-01-16 17:39:24" level=info msg="Finished applying state transition" attestations=35 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2021-01-16 17:47:36" level=info msg="Fallen behind peers; reverting to initial sync to catch up" currentEpoch=10404 peersEpoch=10404 prefix=sync syncedEpoch=10402
```

**Comment by farazdagi** [comment] 2021-01-16 18:13
If it can be reproduced deterministically, is there any way you can share your database (in `.eth2/` folder)? It will help immensely to debug the issue.

**Comment by yuilleb** [comment] 2021-01-16 18:20
Sure, can you specify exactly which files you'd need? Everything in .eth2? I have since stopped and started the process, will that be a problem for debugging?

Also will the process need to be stopped before copying the files or could I copy them while it's running? I have a decent number of validators using this process.

**Comment by farazdagi** [comment] 2021-01-16 18:44
I'll need `.eth2/beaconchaindata/beaconchain.db` which may be quite huge (in GBs), that file is our database so holds all blocks synced on your node. The process needs to be stopped on copy, so whenever you will need to restart the process the next time, please, before doing so, copy file to some local path (it shouldn't take too much of time), and then restart. Then, while nodes are running we can handle the file transfer somehow.

I will ping you on Discord as well, thank you!

**Comment by klatooine** [comment] 2021-02-26 09:05
I am having exactly the same issue than @yuilleb, when it happens I need to reboot my machine

**Comment by rauljordan** [comment] 2021-04-16 13:59
There have not been any similar error reports since 1.3. If this issue still exists, we can reopen this issue thread

**Comment by Karmastic** [comment] 2021-05-17 03:36
I just saw this in 1.3.8+hotfix.  Recovered by restarting the node (k8s container).  Logs available upon request.

**Comment by 0xKiwi** [comment] 2021-05-27 22:15
Hello @Karmastic! Mind sharing your logs to help us debug? :smile:

**Comment by Karmastic** [comment] 2021-06-02 12:51
This is not low priority if it's not fixed already.

**Comment by Karmastic** [comment] 2021-08-23 19:51
This is happening a lot now with pyrmont beacons configured with `--slots-per-archive-point=32`, especially after restarting them.  There doesn't seem to be a fix besides deleting the DB and re-syncing (which takes several days)

**Comment by prestonvanloon** [comment] 2021-08-24 01:01
> This is happening a lot now with pyrmont beacons configured with `--slots-per-archive-point=32`, especially after restarting them. There doesn't seem to be a fix besides deleting the DB and re-syncing (which takes several days)

@Karmastic follow this issue: https://github.com/prysmaticlabs/prysm/issues/9450

**Closed** 2021-12-23 17:56 UTC
Labels: Bug
