### ISSUE TITLE
`LightClientUpdate` is not compatible with `capella` spec

### ISSUE THREAD

**Issue by aeryz** [prysmaticlabs/prysm#13754] opened 2024-03-15 19:42 UTC
# 💎 Issue

### Background

I wanted to give `prysm` a go to use it as the beacon chain and I specifically need light client API's. Looking through the issues and PR's, I saw that a lot of work is done related to this but it's not completed yet. 

### Description

I realized that there is only a single [LightClientUpdate](https://github.com/prysmaticlabs/prysm/blob/develop/api/server/structs/endpoints_lightclient.go#L14) type and it is not compatible with the [capella fork](https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/light-client/sync-protocol.md#modified-lightclientheader). The modifications in the `LightClientHeader` is not present in this repo. I also checked out [this PR](https://github.com/prysmaticlabs/prysm/pull/12854/files#diff-77c308115b8311db642c5d29e2b1b73ec5f97289855d9bfb201a5503a21a90d4R25) but it seems like the same. Is this something that is missed or are the changes introduced in capella going to be handled later?

**Comment by rkapka** [comment] 2024-03-19 04:04
Hi @aeryz , thanks for raising this. Our light client support is incomplete and it's hard to say when exactly we will pick it up again. But it surely will be this year.

**Comment by prestonvanloon** [comment] 2024-03-21 18:21
Duplicate of #11571

**Closed by prestonvanloon** 2024-03-21 18:21 UTC
