### ISSUE TITLE
启动prysm节点失败

### ISSUE THREAD

**Issue by astrid19981112** [prysmaticlabs/prysm#13799] opened 2024-03-26 06:55 UTC
### Describe the bug

geth start command
  /data/geth --datadir /data/eth_data/ --cache 4096 --http --http.port 8545 --http.addr 0.0.0.0 --http.api txpool,eth,web3,admin,personal,net - -syncmode snap --sepolia --authrpc.jwtsecret /home/spadm/jwt.hex --maxpeers 200 --authrpc.vhosts="*" --authrpc.addr=0.0.0.0

prysm.sh startup command
  /data/prysm/prysm.sh beacon-chain --execution-endpoint=http://localhost:8551 --prater --jwt-secret=/home/spadm/jwt.hex --genesis-state=/data/ genesis.ssz --datadir /data/eth_data-new/ --sepolia --genesis-state=/data/genesis.ssz --checkpoint-sync-url=https://sepolia.beaconstate.info --genesis-beacon -api-url=https://sepolia.beaconstate.info
 
  Error log for startup failure
   /data/prysm/prysm.sh beacon-chain --execution-endpoint=http://localhost:8551 --prater --jwt-secret=/home/spadm/jwt.hex --genesis-state=/data/ genesis.ssz --datadir /data/eth_data-new/ --sepolia --checkpoint-sync-url=https://sepolia.beaconstate.info --genesis-beacon-api-url=https://sepolia.beaconstate .info --force-clear-db
Latest Prysm version is v5.0.1.
Beacon chain is up to date.
Verifying binary integrity.
beacon-chain-v5.0.1-linux-amd64: OK
gpg: Signature made Sat 09 Mar 2024 04:49:14 AM CST using RSA key ID F1A5036E
gpg: Good signature from "Preston Van Loon <preston@pvl.dev>"
gpg: aka "Preston Van Loon <preston@prysmaticlabs.com>"
gpg: aka "Preston Van Loon <preston90@gmail.com>"
gpg: aka "Preston Van Loon (0xf71E9C766Cdf169eDFbE2749490943C1DC6b8A55) <preston@machinepowered.com>"
gpg: WARNING: This key is not certified with a trusted signature! gpg: There is no indication that the signature belongs to the owner. Primary key fingerprint: 0AE0 051D 647B A3C1 A917 AF40 72E3 3E4D F1A5 036E
Verified /data/prysm/dist/beacon-chain-v5.0.1-linux-amd64 has been signed by Prysmatic Labs.
Starting Prysm beacon-chain --execution-endpoint=http://localhost:8551 --prater --jwt-secret=/home/spadm/jwt.hex --genesis-state=/data/genesis.ssz --datadir /data/eth_data-new/ --sepolia --checkpoint-sync-url=https://sepolia.beaconstate.info --genesis-beacon-api-url=https://sepolia.beaconstate.info --force- clear-db[2024-03-26 14:46:54] INFO Finished reading JWT secret from /home/spadm/jwt.hex[2024-03-26 14:46:54] WARN flags: Running on the Prater Testnet
[2024-03-26 14:46:54] WARN node: In order to receive transaction fees from proposing blocks, you must provide flag --suggested-fee-recipient with a valid ethereum address when starting your beacon node. Please see our documentation for more information on this requirement (https://docs.prylabs.network/docs/execution-node/fee-recipient).
[2024-03-26 14:46:54] INFO node: Checking DB database-path=/data/eth_data-new/beaconchaindata
[2024-03-26 14:46:54] INFO db: Opening Bolt DB at /data/eth_data-new/beaconchaindata/beaconchain.db
[2024-03-26 14:46:54] WARN node: Removing database
[2024-03-26 14:46:54] INFO db: Opening Bolt DB at /data/eth_data-new/beaconchaindata/beaconchain.db[2024-03-26 14:46:54] INFO detected supported config in remote finalized state, name=sepolia, fork=deneb[2024-03-26 14:46:54] INFO Downloaded checkpoint sync state and block. block_root=0x10d79a7849bd939f6ad037c14649b40f407f0024e774b607a4fc69567d515210 block_slot=4641 728 state_root=0xc889d38fba992d8bf7375b26e4bc508f35fe0b8807ac2a4c27fb9a91dbf28119 state_slot=4641728
unable to start beacon node: config mismatch, beacon node configured to connect to prater, detected state is for sepolia

The versions of prysm and geth are the latest. Please help to check this. Can you give me the correct startup command for the sepolia network?
Thanks

**Comment by nalepae** [comment] 2024-03-26 09:53
In your Prysm BN command launch you have both `--prater` and `--sepolia` flags. Please remove `--prater`.

These arguments should work:
```
/data/prysm/prysm.sh beacon-chain --execution-endpoint=http://localhost:8551/ --jwt-secret=/home/spadm/jwt.hex --datadir /data/eth_data-new/ --sepolia --checkpoint-sync-url=https://sepolia.beaconstate.info/ --genesis-beacon-api-url=https://sepolia.beaconstate.info/
```

However, it's not normal that the Beacon node tries to start with both `--sepolia` and `--prater` flags set at the same time.
(I'll open a new ticket for this issue.)

**Comment by prestonvanloon** [comment] 2024-03-26 18:55
Closing this as duplicate of #13801

**Closed** 2024-03-26 18:55 UTC
Labels: Bug

**Comment by astrid19981112** [comment] 2024-04-18 07:32
谢谢
