### ISSUE TITLE
[Docker image] version showed in logs still v1.0.4

### ISSUE THREAD

**Issue by nicolashomble** [prysmaticlabs/prysm#8112] opened 2020-12-14 19:45 UTC
# 💎 Issue

### Background

Starting the new v1.0.5 docker image, validator and beacon node

### Description

Certainly not a big issue but in the logs when i start the new docker image v1.0.5 the validator and beacon node version still show prysm/v1.0.4/$tag instead of what i assume should be prysm/v1.0.5/$tag now.

with the proper tag for the v1.0.5 (242888...) according to the release page

See attachment
![Screenshot from 2020-12-14 20-37-06](https://user-images.githubusercontent.com/9433820/102127645-0c9dbc80-3e4d-11eb-9f91-81059ce65252.png)

**Comment by mfiumara** [comment] 2020-12-14 22:08
Same here was wondering what I was doing wrong but it looks like something went wrong with the build.

**Comment by prestonvanloon** [comment] 2020-12-14 22:11
Duplicate of #6798.

We're still working on streamlining our build pipeline. The issue is the images are created before the git tag is pushed. I thought we had fixed this, but will continue to work on it in #6798.

**Closed by prestonvanloon** 2020-12-14 22:11 UTC
