### ISSUE TITLE
beacon-chain v1.0.0-beta.1 requires more than 25G RAM

### ISSUE THREAD

**Issue by jerryji** [prysmaticlabs/prysm#7714] opened 2020-11-03 14:06 UTC
# 🐞 Bug Report

### Description

 beacon-chain v1.0.0-beta.1 requires more than 25G memory to run

![image](https://user-images.githubusercontent.com/83122/97996126-5b097580-1e22-11eb-8d04-cc8d50391d68.png)

### Has this worked before in a previous version?

 N.A.

## 🔬 Minimal Reproduction

Not sure how special my case is, Nishant and others are saying their nodes use less than 4G memory...

## 🔥 Error

Well, my beacon-chain easily crashes on server with less than 32G memory.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
beacon-chain v1.0.0-beta.1  (compiled from source)
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

heap.pprof --

https://drive.google.com/file/d/1rqymI4N9ubdsGvLgIJMb50D7t4Xo-8MR/view?usp=sharing

heap2.pprof (30 minutes from the above one) --

https://drive.google.com/file/d/17gr0PuTmTmrDLNBhQh92Ibl9dkhdKcLo/view?usp=sharing

**Comment by nisdas** [comment] 2020-11-03 14:29
So both profiles basically show the same story, it seems like your db potentially might have a bad head block ? Your node basically isnt starting up at all. You might have better luck syncing with a fresh db. 

cc @terencechain 
any ideas on how this is possible ? the state generation isn't terminating to any obvious state. So it looks like its running perputually.

**Comment by terencechain** [comment] 2020-11-03 14:55
It's impossible to tell what is going on based on the given information. @jerryji can you upload your db somewhere?

**Comment by jerryji** [comment] 2020-11-03 15:32
OMG, I've already restarted with --force-clear-db

**Comment by rauljordan** [comment] 2020-11-03 19:57
Duplicate of #7703

**Closed by rauljordan** 2020-11-03 19:57 UTC
