### ISSUE TITLE
Upgrade from alpha-24 to alpha-25 doubles CPU usage and load

### ISSUE THREAD

**Issue by jwhelan72** [prysmaticlabs/prysm#7279] opened 2020-09-19 21:23 UTC
After upgrading from alpha-24 to alpha-25 a few days ago, I see that my VPS CPU usage and load has doubled.

All other settings remain the same. Only two validators running.

![image](https://user-images.githubusercontent.com/1807284/93689464-05297a00-facf-11ea-892f-acb3373dc46a.png)

![image](https://user-images.githubusercontent.com/1807284/93689469-0b1f5b00-facf-11ea-8527-006306579aca.png)

Problem has also been reported by several other users in the Discord chat.

**Comment by finoaker** [comment] 2020-09-20 03:25
![image](https://user-images.githubusercontent.com/52343686/93693517-20829c80-fb44-11ea-963d-39951e545fa2.png)

Same for me. Low spec machine so much higher utilisation, but in versions prior to alpha 25, would sit around 40-50% utilisation, peaking to 90+% only a few times per min.

**Comment by prestonvanloon** [comment] 2020-09-22 04:42
Could you please confirm this for alpha.16?

**Comment by finoaker** [comment] 2020-09-22 04:51
Was just checking as your message arrived. Better but, not back down to alpha 24 level. Upgraded at 12:30 mark, pattern was the same for 12 hours prior using alpha 25.

![image](https://user-images.githubusercontent.com/52343686/93845034-b8b68800-fce2-11ea-8bb7-a5e477848439.png)

**Comment by prestonvanloon** [comment] 2020-09-22 19:52
Looking through this commit range: https://github.com/prysmaticlabs/prysm/compare/v1.0.0-alpha.24...v1.0.0-alpha.26

**Comment by raphpa** [comment] 2020-09-22 22:49
I just had the same issue, cannot reproduce unfortunately (on :latest)

- On the first start after a server reboot it used up all RAM available, so I restarted the docker container again.
- On consecutive container restarts I had a high CPU load and the prometheus endpoint did just stall on an open connection and did not return any data, even though the node seemed to work okay (besides the high cpu load).
- After a couple of restarts it went back to normal operation again

**Comment by raphpa** [comment] 2020-09-22 23:38
Got it again, maybe there is something interesting in the pprof file

[cpu.pprof.zip](https://github.com/prysmaticlabs/prysm/files/5264611/cpu.pprof.zip)

**Comment by jwhelan72** [comment] 2020-09-23 09:25
Below is the CPU & Load stats when running 24, 25 & 26.  As you can see, there was a big jump in resource consumption with 25.  That dropped considerably with 26 but is not back to the level when running 24.

![image](https://user-images.githubusercontent.com/1807284/93993859-87e05c80-fd8f-11ea-84df-2c18a8ac8af5.png)

**Comment by prestonvanloon** [comment] 2020-09-26 00:18
This should be fixed with #7340, let's keep this open until alpha.27 is available on Monday for testing.

**Comment by rauljordan** [comment] 2020-10-13 15:15
No longer reported as an issue. If this is still a problem in alpha.29 we can re-open, please advise @jwhelan72

**Closed by rauljordan** 2020-10-13 15:15 UTC
