### ISSUE TITLE
fetching blocks with slot=0 returns multiple entries

### ISSUE THREAD

**Issue by tzapu** [prysmaticlabs/prysm#4258] opened 2019-12-11 12:27 UTC
hi
when trying to list blocks with the filter slot=0 i get back multiple (250, a page i assume) return values on my node and a 503 error on yours.
`curl -X GET "https://api.prylabs.net/eth/v1alpha1/beacon/blocks?slot=0" -H  "accept: application/json"`
cheers

possibly linked to https://github.com/prysmaticlabs/prysm/issues/4257

**Comment by prestonvanloon** [comment] 2019-12-11 17:35
Slot=0 is the same as not setting a slot value, if you intended to get the genesis block, you can set genesis=true.

https://api.prylabs.net/eth/v1alpha1/beacon/blocks?genesis=true

However, this also seems to be broken with #4257. I'll close this as a duplicate of #4257, but please reopen it if you feel there is something different to address. Thanks!

**Closed by prestonvanloon** 2019-12-11 17:35 UTC

**Comment by tzapu** [comment] 2019-12-11 21:30
hey @prestonvanloon , it does not seem to behave the same. if you call it without any filter you get back `400 Undocumented | Error: Bad Request` and with `?slot=0` i no longer get a 503 as in the intial post but i do get a 200 http status code.

**Comment by prestonvanloon** [comment] 2019-12-12 22:41
Ah ok, thanks. In any case, this looks resolved by #4257
