### ISSUE TITLE
Slasher: Prysm takes up more and more memory until it stops. Why?

### ISSUE THREAD

**Issue by 953446** [prysmaticlabs/prysm#13430] opened 2024-01-08 11:11 UTC
### Describe the bug

Prysm takes up more and more memory until it stops. Why?

This is my startup command

```
./prysm.sh beacon-chain --slasher --execution-endpoint=http://127.0.0.1:8551 --jwt-secret=/root/prysm/jwt.hex --chain-id=1 --datadir ='/home/www/eth_data' --mainnet --checkpoint-sync-url=https://sync.invis.tools --genesis-beacon-api-url=https://sync.invis.tools -- enable-experimental-state --p2p-max-peers=20 --grpc-max-msg-size=1000000000
```

geth version geth version 1.13.2-stable-dc34fe82

Latest Prysm version is v4.1.1.

Run using screen

![image](https://github.com/prysmaticlabs/prysm/assets/128539227/e98a7e5f-db40-44c1-b6eb-ab5348f5e545)
![image](https://github.com/prysmaticlabs/prysm/assets/128539227/369a51f1-a8aa-4ea4-b779-3c4fbcf9ae93)

This will eventually happen
![image](https://github.com/prysmaticlabs/prysm/assets/128539227/038e06cd-4b5f-4d4a-9487-79cf98cd51a1)

**Comment by 953446** [comment] 2024-01-11 13:30
@prestonvanloon Why no one cares about me

**Comment by prestonvanloon** [comment] 2024-01-11 14:23
Thanks for the report @953446. @nalepae please take a look at this. It seems like the slasher could be causing a memory leak.

This may be a duplicate of #13270

**Comment by 953446** [comment] 2024-01-20 18:19
> 感谢您的报告@953446。@nalepae请看一下这个。看起来削减者可能会导致内存泄漏。
> 
> [这可能是#13270](https://github.com/prysmaticlabs/prysm/issues/13270)的重复[](https://github.com/prysmaticlabs/prysm/issues/13270)

So how can I solve this problem?

**Comment by nalepae** [comment] 2024-02-01 13:32
We were able to reproduce the issue and we are working on it.
The issue come from the slasher service.

A short term, not ideal solution is to run your beacon node without the `--slasher` flag.

By the way, thanks for running a slasher in your infrastructure :)

**Comment by 953446** [comment] 2024-02-02 18:46
> We were able to reproduce the issue and we are working on it. The issue come from the slasher service.
> 
> A short term, not ideal solution is to run your beacon node without the `--slasher` flag.
> 
> By the way, thanks for running a slasher in your infrastructure :)

thank you very much for your help

**Closed** 2024-02-21 15:33 UTC
Labels: Bug
