### ISSUE TITLE
Console log: "Enter this raw deposit TX data into step 3 on the prylabs.net/participate page"

### ISSUE THREAD

**Issue by wgknowles** [prysmaticlabs/prysm#5729] opened 2020-05-04 10:00 UTC
# 🚀 Feature Request

Lots of new users aren't taking the raw deposit TX data and submitting it via the the prylabs.net/participate page.  The UX could be improved by adding instructions in the form of a console message accompanying the TX data.

 If you have a solution in mind, please describe it.

The end of "validator accounts generate should look like this:

```
==========Raw Transaction Data============
0x200000000000000000000000000000000000006081e9e0000000095bccce6f600000000000000000000000000000000000000000000000…b5fcb
========================================
*** Enter the above Raw Transaction Data into step 3 on https://prylabs.net/participate ***
```

**Comment by shayzluf** [comment] 2020-05-04 15:42
@har00ga please reassign to me if you find the assignment inappropriate

**Comment by har00ga** [comment] 2020-05-07 22:08
@shayzluf That step is described in [this part of the validator activation pages](https://docs.prylabs.network/docs/install/lin/activating-a-validator/#step-3b-submitting-the-deposit-data), I think the issue is with people that're simply following the steps on prylabs.net  sans documentation. The prylabs page could probably use a more concise note about this step which I'm happy to change, and also @wgknowles suggestion of adding it to the console printout is a good one :slightly_smiling_face: Would do that adjustment as well, but not sure which file in the repo contains the string. Probably easier for one of you folks to fix that part.

**Closed** 2020-05-15 20:24 UTC
Labels: Enhancement, Good First Issue
