### ISSUE TITLE
Latest beacon client produces duplicate log entries

### ISSUE THREAD

**Issue by torfbolt** [prysmaticlabs/prysm#4218] opened 2019-12-07 13:04 UTC
The latest client versions seem to log some (not all) of the messages twice:

```
[2019-12-07 12:54:04]  INFO forkchoice: Executing state transition on block root=0x40023cd3... slot=186130
[2019-12-07 12:54:04]  INFO forkchoice: Executing state transition on block root=0x40023cd3... slot=186130
[2019-12-07 12:54:04]  INFO blockchain: Finished applying state transition attestations=4 deposits=0 slot=186130
[2019-12-07 12:54:04]  INFO blockchain: Finished applying state transition attestations=4 deposits=0 slot=186130
[2019-12-07 12:54:15]  INFO forkchoice: Executing state transition on block root=0x95a2c9b9... slot=186131
[2019-12-07 12:54:15]  INFO blockchain: Finished applying state transition attestations=5 deposits=0 slot=186131
[2019-12-07 12:54:29]  INFO forkchoice: Executing state transition on block root=0xdf05a783... slot=186132
[2019-12-07 12:54:29]  INFO blockchain: Finished applying state transition attestations=4 deposits=0 slot=186132
[2019-12-07 12:54:40]  INFO forkchoice: Executing state transition on block root=0xff3f00ba... slot=186133
[2019-12-07 12:54:41]  INFO blockchain: Finished applying state transition attestations=5 deposits=0 slot=186133
[2019-12-07 12:54:51]  INFO forkchoice: Executing state transition on block root=0x82083571... slot=186134
[2019-12-07 12:54:51]  INFO forkchoice: Executing state transition on block root=0x82083571... slot=186134
[2019-12-07 12:54:51]  INFO blockchain: Finished applying state transition attestations=4 deposits=0 slot=186134
[2019-12-07 12:54:51]  INFO blockchain: Finished applying state transition attestations=4 deposits=0 slot=186134
[2019-12-07 12:55:04]  INFO forkchoice: Executing state transition on block root=0x33357dbf... slot=186135
[2019-12-07 12:55:04]  INFO forkchoice: Executing state transition on block root=0x33357dbf... slot=186135
[2019-12-07 12:55:04]  INFO blockchain: Finished applying state transition attestations=5 deposits=0 slot=186135
[2019-12-07 12:55:04]  INFO blockchain: Finished applying state transition attestations=5 deposits=0 slot=186135
[2019-12-07 12:55:16]  INFO forkchoice: Executing state transition on block root=0x16a7be2a... slot=186136
[2019-12-07 12:55:16]  INFO forkchoice: Executing state transition on block root=0x16a7be2a... slot=186136
[2019-12-07 12:55:17]  INFO forkchoice: Starting next epoch epoch=23267 finalizedEpoch=23265 justifiedEpoch=23266 previousJustifiedEpoch=23265
[2019-12-07 12:55:17]  INFO forkchoice: Validator registry information activeValidators=521 averageBalance=4.57855 ETH totalValidators=751
[2019-12-07 12:55:17]  INFO forkchoice: Starting next epoch epoch=23267 finalizedEpoch=23265 justifiedEpoch=23266 previousJustifiedEpoch=23265
[2019-12-07 12:55:17]  INFO forkchoice: Validator registry information activeValidators=521 averageBalance=4.57855 ETH totalValidators=751

```

Minor issue, but maybe an indication of something that might be causing other bugs. Feel free to close as wontfix.

**Comment by prestonvanloon** [comment] 2019-12-10 16:08
Interesting. This could mean that the same routine is running twice. Is this still producible? 

cc: @terencechain

**Comment by terencechain** [comment] 2019-12-10 16:15
Reproduced on my local node syncing with cluster. Will look into this today

**Comment by terencechain** [comment] 2019-12-13 19:28
Looked into this. Ristretto cache isn't working as expected. Duplicated blocks and attestations pass through the following checks

```go
	if _, ok := recentlySeenRoots.Get(string(blockRoot[:])); ok || r.db.HasBlock(ctx, blockRoot) {
		return false, nil
	}
	recentlySeenRoots.Set(string(blockRoot[:]), true /*value*/, 1 /*cost*/)
```

**Comment by terencechain** [comment] 2019-12-13 19:28
cc @prestonvanloon

**Comment by prestonvanloon** [comment] 2019-12-13 19:39
We need a regression test to validate this theory. Is the cache being
pruned?

**Comment by terencechain** [comment] 2019-12-13 19:42
> We need a regression test to validate this theory. Is the cache being pruned?

I verified run time. There's always one of the same object that gets through 25% of the time. What do you recommend for regression testing this type of intermittent issue?

**Comment by torfbolt** [comment] 2019-12-13 20:38
If the info helps, I have sometimes seen triple and even quadruple log entries.

**Comment by prestonvanloon** [comment] 2019-12-13 20:41
Any unit test that proves this theory. Do multiple identical objects miss
the cache? How what is the root cause?

**Comment by terencechain** [comment] 2019-12-13 20:46
So far unable to reproduce via unit test

**Comment by terencechain** [comment] 2019-12-13 23:27
Sorry I haven't been able to spend much time on it due to v0.9.2 and addressing cache feedback. Will spend more time on it this weekend

**Comment by prestonvanloon** [comment] 2019-12-14 16:59
We discussed this a bit offline. There are two parts message de-duplication. The application layer, which is outlined in this issue, checks the hash tree root of the object and if the application has seen that particular object already. The second part of de-duplication is pubsub message IDs. We currently aren’t using libp2p pubsub validation pipeline because it would require deserializing the message at least twice. As a result, any messages that are propagated forward in our regular sync will appear as new pubsub messages with new IDs. 

Given that we can’t write a unit test for hash tree root checking for identical objects, this may be a problem with cache eviction, race conditions, or other problems. 

Action items here are:
- Resolve the issue outlined here, something isn’t right to allow multiple identical messages to pass this validation. 
- Fork gossipsub validation pipeline to reuse existing message IDs for propagation

**Comment by torfbolt** [comment] 2019-12-24 10:05
Haven't seen this again for a few days. Do you think #4319 fixed it?

Can we close this? My guess from @terencechain 's comments would be that it's hard and probably not worth the effort to try and write a test case for this.

**Comment by rauljordan** [comment] 2019-12-26 17:14
I have not observed this today with latest master after syncing to head - closing unless it comes up again

**Closed by rauljordan** 2019-12-26 17:14 UTC
Labels: Priority: High
