### ISSUE TITLE
Initial sync cache state is broken

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#4676] opened 2020-01-28 16:56 UTC
`--initial-sync-cache-state` is broken in latest master, for some reason the processing block went back in slot for the very last slot `134667` -> `134626`

```
[2020-01-28 08:53:46]  INFO initial-sync: Processing block 134664/134668 - estimated time remaining 1s blocksPerSecond=2.8 peers=3/4
[2020-01-28 08:53:46]  INFO initial-sync: Processing block 134667/134668 - estimated time remaining 0s blocksPerSecond=2.8 peers=3/4
[2020-01-28 08:53:47]  INFO initial-sync: Processing block 134626/134668 - estimated time remaining 15s blocksPerSecond=2.7 peers=1/4
[2020-01-28 08:53:47] ERROR initial-sync: Failed to process block, exiting init sync error=pre state of slot 134626 does not exist
could not process block from fork choice service
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveBlockNoPubsubForkchoice
	beacon-chain/bl
bockchain/receive_block.go:221
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync
	beacon-chain/sync/initial-sync/round_robin.go:262
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).Start
	beacon-chain/sync/initial-sync/service.go:123
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
[2020-01-28 08:53:47]  INFO initial-sync: Synced up to slot 134625
```

**Comment by rauljordan** [comment] 2020-01-28 18:01
Duplicate of #4583

**Closed by rauljordan** 2020-01-28 18:01 UTC
Labels: Bug, Priority: High
