### ISSUE TITLE
[Docker] Validator client gets stuck waiting for beacon node during automatic updates.

### ISSUE THREAD

**Issue by KuDeTa** [prysmaticlabs/prysm#6412] opened 2020-06-26 10:10 UTC
# 🐞 Bug Report

### Description

Validator client occasionally gets stuck during automatic updates with docker + watchtower. 

### Has this worked before in a previous version?

Haven't experienced this before. 

## 🔬 Minimal Reproduction

Uncertain. 

## 🔥 Error

Recently, automatic updates with watchtower often result in the new validator process getting stuck at:

[2020-06-25 22:11:22]  INFO validator: Waiting for beacon chain start log from the ETH 1.0 deposit contract.

It works again fine if the process is restarted, but can result in loss of earnings. 

Root cause may well be due to both beacon and validator being updated at the same time i.e if the beacon node is down/not responding just at moment the validator client is updated. Can behaviour around this be made more robust? 

watchtower logs:

time="2020-06-25T22:11:01Z" level=info msg="Found new gcr.io/prysmaticlabs/prysm/slasher:latest image (sha256:228c3230f8af61b28dfe277b16197bf40e74a018ac74055c2df074fec9354a20)"
time="2020-06-25T22:11:03Z" level=info msg="Found new gcr.io/prysmaticlabs/prysm/beacon-chain:latest image (sha256:12a41eadc2f97826018edf7c3e6cd87ff054c484076fbcec9bf291746a5f83f2)"
time="2020-06-25T22:11:05Z" level=info msg="Found new gcr.io/prysmaticlabs/prysm/validator:latest image (sha256:a39ba765b0463cfd49c3aea82fbda282d22f22a3fac807ead5765bf5cfc97055)"
time="2020-06-25T22:11:14Z" level=info msg="Stopping /eth2-prysm-valid (fccb676fdecdd6e1b703a8f23ee06768dee8800bdba9a7050443bfbd59852920) with SIGTERM"
time="2020-06-25T22:11:16Z" level=info msg="Stopping /eth2-prysm-beacon (6ce3b4c9b813ca03be8f91c4658a63eb69eb7bbc23cc7c3f423b7d7b0723724c) with SIGTERM"
time="2020-06-25T22:11:17Z" level=info msg="Stopping /eth2-prysm-slasher (148db936ff554f97c981bf6f0b883927078c1d32cf7d21c19fcaf794fce9b5b6) with SIGTERM"
time="2020-06-25T22:11:18Z" level=info msg="Creating /eth2-prysm-slasher"
time="2020-06-25T22:11:19Z" level=info msg="Creating /eth2-prysm-beacon"
time="2020-06-25T22:11:20Z" level=info msg="Creating /eth2-prysm-valid"

## 🌍  Your Environment

**Operating System:**

Setup: 
Ubuntu LTS
Docker
Watchtower (for automatic updates)
Validator/Slasher/Beacon node all running on local box

**Comment by prestonvanloon** [comment] 2020-06-26 22:25
Closing as a duplicate of #6325. Please subscribe to #6325 for updates. Thanks!

**Closed by prestonvanloon** 2020-06-26 22:25 UTC
