### ISSUE TITLE
Backup ETH1 Provider Support

### ISSUE THREAD

**Issue by jerryji** [prysmaticlabs/prysm#7976] opened 2020-11-27 02:37 UTC
# 🚀 Feature Request

### Description

 Lighthouse has a PR for Fallback nodes for eth1 access sigp/lighthouse/pull/1918
It would be great if Prysm supports backup --http-web3provider as well 

### Describe the solution you'd like

 NA

### Describe alternatives you've considered

 NA

**Comment by 0xKiwi** [comment] 2020-11-27 18:22
Closing as this is a duplicate of: #7969

**Closed by 0xKiwi** 2020-11-27 18:22 UTC
Labels: Enhancement, Needs Design
