### ISSUE TITLE
Initial Sync Cache State Leads to OOMs

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#4813] opened 2020-02-10 14:35 UTC
Using the ```initial-sync-cache-state``` flags leads to  OOMs when syncing blocks in a period without finality. This is as we cache the relevant fields of each state in a slot. Without finality there is no pruning of states, so all these fields are kept on the heap and leads to the heap size quickly ballooning.

A solution for this would be to handle periods without finality properly and not keep all states in memory.

**Comment by rauljordan** [comment] 2020-02-11 01:59
Can we close this @nisdas now that we're deleting states after init sync?

**Comment by prestonvanloon** [comment] 2020-02-11 18:49
I'm not entirely sure this is resolved by #4817. If users are crashing OOM during init sync, then the problem is not resolved by #4817.

**Closed** 2020-02-18 21:10 UTC
Labels: Bug, Priority: High

**Comment by michaelbryan92** [comment] 2020-08-19 07:11
This is still happening. My Prysm node crashed while running well after the initial-sync period was over, and upon restarting had to sync the whole beacon chain again.
