### ISSUE TITLE
Missing Lots of Sync Committee Duties Until Restarting Prysm

### ISSUE THREAD

**Issue by biteric2000** [prysmaticlabs/prysm#12334] opened 2023-04-26 02:06 UTC
# 🐞 Bug Report

### Description

Hello Prysm team, my node is missing sync committee duties a lot. 
The problem has persisted for quite some time. The general issue is:

Attestations and proposals are good.
The sync committee duties are good for the first several hours and then it will begin to struggle with lots of misses & penalties. 
During the struggle the peer count and logs are fine.
The problem will be solved once I restart Prysm client. 
But restarting during sync committee also hurts.

This happens every time when my validators enter the sync committee.

I have found reports by others with same problem:
https://www.reddit.com/r/ethstaker/comments/113s1so/every_sync_committee_i_have_to_reboot_prysm_to/
https://discord.com/channels/694822223575384095/782670371735732274/937392575294349355

### Has this worked before in a previous version?
The problem has lasted for quite long time (at least the recent 3-4 Prysm versions). 
I thought it was network issue until I found restarting will almost always help.

## 🌍  Your Environment

**Operating System:**
Windows 11

**What version of Prysm are you running? (Which release)**
4.0.3

**Hardware Info:**
Intel NUC latest gen i5-1240p 64GB RAM
4TB SSD dedicated for prysm and 8TB SSD for Geth

**Comment by biteric2000** [comment] 2023-04-26 03:30
Found another post reporting the same issue:
https://www.reddit.com/r/ethstaker/comments/z2r7ee/what_explains_sync_penalties_when_the_validator/

**Comment by nisdas** [comment] 2023-04-26 03:49
Possibly the only thing that could explain it is that you do start receiving blocks later or your node becomes stressed during this period. Did you have debug logs enabled during this period ? We haven't seen this on our nodes so far but not ruling anything out yet. 

One possible thing you could do is run prysm with `--pprof` and then fetch a profile via 
```
curl http://localhost:6060/debug/pprof/profile -o cpu.pprof
```

**Comment by biteric2000** [comment] 2023-04-26 04:33
> Possibly the only thing that could explain it is that you do start receiving blocks later or your node becomes stressed during this period. Did you have debug logs enabled during this period ? We haven't seen this on our nodes so far but not ruling anything out yet.
> 
> One possible thing you could do is run prysm with `--pprof` and then fetch a profile via
> 
> ```
> curl http://localhost:6060/debug/pprof/profile -o cpu.pprof
> ```
> 
> when you see your node's performance deteriorating

Yes, Prysm was started with --ppof enabled. I'll fetch a profile with the command you suggested.

In the mean time, if it is the stressed issue which caused the problem, how can I reduce the resource usage without switch the rig? 
Thought the hardware configuration should be decent (or even a bit future proof) for running a node.
Maybe by reducing peers, or is there other effective methods?

**Comment by nisdas** [comment] 2023-04-26 04:41
> In the mean time, if it is the stressed issue which caused the problem, how can I reduce the resource usage without switch the rig?
Thought the hardware configuration should be decent (or even a bit future proof) for running a node.

Honestly, I can't say for sure without more data. We have never seen this issue in our testing, so I am not sure if the node is actually stressed or there is some other issue at play here. Debug logs + a profile would help us investigate this further. You could try to keep your system's clock synced and see if that helps when you start running into this issue as an out of sync clock is the only thing that would explain what you have observed.

**Comment by biteric2000** [comment] 2023-04-26 04:52
Thank you for the reply. I'll try to provide profile and verbose logs on the issue when the situation deteriorate again. Maybe because the validator amount is larger than normal scenarios (or other reasons), the problem is not shown on every configuration. The system is auto-synced with a specific service we installed.

**Comment by biteric2000** [comment] 2023-05-08 11:36
> Possibly the only thing that could explain it is that you do start receiving blocks later or your node becomes stressed during this period. Did you have debug logs enabled during this period ? We haven't seen this on our nodes so far but not ruling anything out yet.
> 
> One possible thing you could do is run prysm with `--pprof` and then fetch a profile via
> 
> ```
> curl http://localhost:6060/debug/pprof/profile -o cpu.pprof
> ```
> 
> when you see your node's performance deteriorating

Hello, @nisdas !

Could you please tell me how to continuously monitor / obtain the cpu.pprof profile? It seems that the gathering of data will be stopped after a short while, like ~30 seconds. 

Therefore it is unlikely to get the info around the right moment when the situation deteriorates. Only the profiles before and after, once I found the problem emerged. (Or maybe that's already enough?)

The Prysm node's OS is Windows, and curl is ported from linux (some functions may not be exact the same). 

Thanks!

**Comment by biteric2000** [comment] 2023-05-24 00:33
Yes, the problem still persists. 
Where can I send the logs and profiles? Maybe specify an email address please @nisdas , thanks!

**Comment by fabrice-quadrata** [comment] 2023-07-05 21:05
Experiencing the same issue.

Could be a duplicate of https://github.com/prysmaticlabs/prysm/issues/12479

**Comment by fabrice-quadrata** [comment] 2023-07-06 00:00
Linking for reference: https://github.com/prysmaticlabs/prysm/issues/12596

**Comment by nisdas** [comment] 2023-07-17 04:40
@Chaz27 Its possible your machine's clock isn't fully synced

**Comment by nisdas** [comment] 2023-07-17 04:50
Maybe look at this:
https://docs.prylabs.network/docs/prysm-usage/p2p-host-ip#configure-your-firewall 

Specifically this section:
```
*/UDP+TCP    Allow outbound traffic.    To discover peers, Prysm's beacon node dials out through random ports. Allowing outbound TCP/UDP traffic from any port will help Prysm find peers.
 this might actually be the reasons.
 ```

**Comment by terencechain** [comment] 2023-08-06 14:43
I am closing this. Feel free to reopen if it persists

**Closed by terencechain** 2023-08-06 14:43 UTC
Labels: Bug, Need-Info

**Comment by alexfisher** [comment] 2023-09-07 13:40
Posted on a similar issue, but also had issue on 4.0.8 with sync committee messages being missed.  No peering or attestation issues...

https://github.com/prysmaticlabs/prysm/issues/12596#issuecomment-1710148597

**Comment by fabrice-quadrata** [comment] 2023-09-27 06:30
same, having only 40% sync attestations completed.

With 4.0.8 and latest geth
