### ISSUE TITLE
Sharding P2P Protocol Specs Proposition

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#72] opened 2018-03-14 01:23 UTC
Hi Team,

As part of this issue I would like to propose we use **libp2p** as our sharding networking protocol. It is a solid library created by Protocol Labs and currently powering IPFS. Let's use this issue to elaborate on this as much as we can and discuss if we want to integrate this.

Let's figure out how different it is from devp2p and if it would be worth our while to try this approach.

Here are some of the resources to get started:

[libp2p site](https://libp2p.io/)
[libp2p specs](https://github.com/libp2p/specs)
[go libp2p](https://github.com/libp2p/go-libp2p)
[js libp2p](https://github.com/libp2p/js-libp2p)

[distinction between p2p libraries](https://ethereum.stackexchange.com/questions/12290/what-is-the-distinction-between-libp2p-devp2p-and-rlpx)
[libp2p video by juan benet](https://www.youtube.com/watch?v=HxueJbeMVG4)
[devp2p wiki](https://github.com/ethereum/wiki/wiki/%C3%90%CE%9EVp2p-Wire-Protocol)

Let me know your thoughts below.

**Comment by terenc3t** [comment] 2018-03-14 01:52
Check out Felix's slide on evolving devp2p from devcon3:
https://twurst.com/files/devcon3-evolving-devp2p.pdf

Also WhisperV6 runs on libp2p because whisper peering sucks on devp2p

**Comment by Magicking** [comment] 2018-03-14 14:36
For a different [project](https://github.com/Magicking/protochannel) I
looked at devp2p & libp2p.
Libp2p was what we choosed to experiment[1] with mainly because it looked
more mature, seemed to be more used in the wild and there were good
[examples](https://github.com/libp2p/go-libp2p/tree/master/examples) to
begin with while I'm less convinced by devp2p due to the lack of easy to
read examples & documentation :(.

[1] - Not started yet :(

**Comment by nisdas** [comment] 2018-03-21 05:43
I did an overview summarizing what devp2p and libp2p would entail , you guys can take a look for it here https://docs.google.com/document/d/1K9NVV2SBjxdgejWnip3l-ZYyknOdWu6i5Ot_X_y6t1k/edit?usp=sharing 

I am in agreement with Raul that for us using libp2p would be a better option than devp2p owing to the fact the former has more robust documentation , libp2p was designed to be able to use a much wider variety of transport protocols and is transport agnostic. Also the team at protocol labs is consistently working on it and improving on it which is beneficial to us. In comparison devp2p has very sparse documentation and does not look like it is being actively maintained.

**Comment by Magicking** [comment] 2018-03-23 12:11
As I re-read this issue, there is also something missing as libp2p or devp2p would only be the network layer where we also need a protocol specification to define the standard communication mecanism, it's certainly an issue we should tackle upstream (https://ethresear.ch/c/sharding)

**Comment by enriquefynn** [comment] 2018-03-23 12:28
I think this should be pushed forward in the implementation. We don't need any p2p network for a local client.

**Comment by nisdas** [comment] 2018-03-23 12:30
We would need for our proposer node , since it is using a separate transaction pool to the main client

**Comment by enriquefynn** [comment] 2018-03-23 12:32
Can you elaborate why you need a p2p network for a *local* implementation?

**Comment by enriquefynn** [comment] 2018-03-23 18:21
We don't need any p2p network for a **local** client, I'm pushing this to the sapphire release

**Comment by terenc3t** [comment] 2019-01-15 01:17
We have been working with Libp2p for a while now. Ok to close this issue?

**Comment by prestonvanloon** [comment] 2019-01-16 00:30
Sounds good to me

**Closed by prestonvanloon** 2019-01-16 00:30 UTC
Labels: Question
