### ISSUE TITLE
Everytime the node restart, the sync start back from the beginning of alpha 9

### ISSUE THREAD

**Issue by GuillaumeMiralles** [prysmaticlabs/prysm#6156] opened 2020-06-06 12:39 UTC
#🐞 Bug Report

### Description

I restarted my node with this exact command:
```c:/prysm/prysm.bat beacon-chain --datadir=c:/prysm --dev --pprof```

My node was synced right before to restart it, but still when it started, I had around 30.000 slots behind the beacon chain. I waited it to be fully synced, then I restarted it again, and I got the same result:
![image](https://user-images.githubusercontent.com/23481418/83944326-0a560800-a803-11ea-8993-f35fa42b122c.png)

Also after syncing, it deleted a lot of old state, which shows that the db hasn't been saved at all
![image](https://user-images.githubusercontent.com/23481418/83944367-47ba9580-a803-11ea-9e50-41136744f24b.png)

### Has this worked before in a previous version?

I never had this issue in previous version (alpha 8 and bellow). It seems like the current state of the db is not correctly save or something.

## 🔬 Minimal Reproduction

Only restart the beacon node (maybe `--dev` is needed to reproduce the bug)

## 🔥 Error

 N/A

## 🌍  Your Environment

**Operating System:**
Windows 10 Home

**What version of Prysm are you running? (Which release)**
Alpha 9, using prysm.bat

**Comment by terencechain** [comment] 2020-06-06 14:47
Just to clarify with new state mgmt, it is expected a node always starts to sync 2048-4096 slots back (ie. start at last archived check point) since it operates mostly on memory. I'm not sure about 30k slots back, I haven't been able to reproduce that and I haven't heard anyone mentioned this.

Can you upload your DB?

**Comment by terencechain** [comment] 2020-06-06 15:10
I know what happened. In:

- Alpha.8: Default --slots-per-archived-point is 256 slots
- Alpha.9: Default --slots-per-archived-point is 2048 slots (I should never have increased this mid flight. Bad idea)

Now the archived index structure in DB is messed up. The node thinks it has more archived indices than it should. Hence it's not saving new archived index at every 2048 interval. To work around, theres two options:

1.) Resync from genesis with --dev flag
2.) Add `--slots-per-archived-point=256` with `--dev`

My action item from this:
1.) Prevent UX to change archived index midflight

@GuillaumeMiralles can you confirm either option works for you?

**Comment by raphpa** [comment] 2020-06-06 15:28
Have the same issue. 
`level=error msg="flag provided but not defined: -slots-per-archived-point" prefix=main`

**Comment by terencechain** [comment] 2020-06-06 15:30
> Have the same issue.
> `level=error msg="flag provided but not defined: -slots-per-archived-point" prefix=main`

Sorry, it's `slots-per-archive-point`.   `--slots-per-archive-point=256`

**Comment by raphpa** [comment] 2020-06-06 16:05
Works, it now started about 230 slots before the point it was stopped 👍

**Comment by terencechain** [comment] 2020-06-06 17:55
Thanks @raphpa for confirming. I opened: 
https://github.com/prysmaticlabs/prysm/issues/6158

Will close this once @GuillaumeMiralles confirm the workarounds are ok

**Comment by GuillaumeMiralles** [comment] 2020-06-06 19:49
I still get 35.000 slots not synced with this command:
```c:/prysm/prysm.bat beacon-chain --datadir=c:/prysm --dev --slots-per-archive-point=256```

![image](https://user-images.githubusercontent.com/23481418/83953286-8d954f00-a83f-11ea-9770-74a9bf76af72.png)

**Comment by GuillaumeMiralles** [comment] 2020-06-06 20:28
Ok so option 2 did work.
I had to restart a first time with the new flag, as expected it started back 35.000 slots behind. Then half way (so around 10.000 slots behind still) I restarted it again, expecting it to restart with only 10.000 slots behind, but instead I was back at the beginning of alpha 9 release.
For it to work I had to wait until the node was fully sync with head again, and when I restarted it for the third time, it worked
![image](https://user-images.githubusercontent.com/23481418/83953940-ffbc6280-a844-11ea-99f7-2e5ec8b1d4e0.png)

**Comment by nisdas** [comment] 2020-06-07 12:53
I think we can close this now the bug seems resolved, what do you think
@terencechain @GuillaumeMiralles @raphpa ?

**Comment by GuillaumeMiralles** [comment] 2020-06-07 13:05
I don't know if the changes have been made or not for alpha 10 yet, but yeap --slots-per-archive-point=256 fixed the issue.
Also, this has fixed #6123 . The error on this issue was `Failed to get attestation pre state` which is what we just fixed here

**Comment by nisdas** [comment] 2020-06-07 13:18
This will all be included in alpha.10. In that case I will close this issue as it seems resolved. Thanks for clarifying @GuillaumeMiralles

**Closed by nisdas** 2020-06-07 13:18 UTC
Labels: Bug
