### ISSUE TITLE
web ui logging breaks prometheus and other loggers

### ISSUE THREAD

**Issue by potuz** [prysmaticlabs/prysm#7506] opened 2020-10-12 12:57 UTC
Running the validator with the web ui interface the logs get sent to the ui and are lost from other system loggers like journald. This also breaks existing monitoring tools like prometheus and grafana. Logs should be replicated perhaps.

**Comment by 0xKiwi** [comment] 2020-10-15 16:30
Hello @potuz thank you for reporting!

This seems like an issue with the web ui and how it handles logs. Any ideas to handle this? @rauljordan

**Comment by potuz** [comment] 2020-10-15 16:35
For the logs simply doubling them would be a solution. I'm not sure about Prometheus but it seems to me that you are hooking it to logrus so that may also be solved by doubling.

**Comment by bidlocode** [comment] 2020-10-17 02:15
It's already there: `mw := io.MultiWriter(logrus.StandardLogger().Out, w)`

Just tested it looks like logs go both destinations (with journald hook and without) and  monitoring port gives metrics.
@potuz Can you give more info on how to reproduce?

**Comment by potuz** [comment] 2020-10-17 19:00
Oh it may well be invalid. My system became unusable when I tried to run with `--web` and the first thing I noticed is that the grafana endpoint of my (other) running validator lost all data. I currently can't check this cause I'm trying to keep my node in sync and it's taking over all my resources

**Comment by bidlocode** [comment] 2020-10-17 19:09
`--web` has different initializaion sequence, startup process woun't advance untill you unlock it with password from webui. Have you had it unlocked?

**Comment by potuz** [comment] 2020-10-17 19:12
That may be it, I didn't want to unlock the wallet on the browser, (that's why I opened #7505) so I hit "create a new wallet" or whatever the option was to create a different one and create some accounts.

**Comment by rauljordan** [comment] 2020-10-22 21:20
This is resolved by #7471

**Closed by rauljordan** 2020-10-22 21:20 UTC
Labels: Bug, web-ui
