### ISSUE TITLE
Batch is not processed error=beacon node doesn't have a parent in db 

### ISSUE THREAD

**Issue by garyng2000** [prysmaticlabs/prysm#10383] opened 2022-03-17 02:43 UTC
This problem is roaring its head again.

I am in the process of setting up the kiln testnet(using that branch) and encountered this problem and seeing that it is a repeated issues both reported here as well as seeing it in my early days.

Once getting into this, the sync just stuck there and would not proceed further.

Just FYI, lighthouse(again kiln) sync fine(from the same machine/network), and we have production setup using prysm which is also running fine.

**Comment by potuz** [comment] 2022-03-17 11:39
Closing as duplicate of #10037 please provide logs in that issue to further diagnose

**Closed by potuz** 2022-03-17 11:39 UTC
