### ISSUE TITLE
Display in Validator Client if Deposit Was Processed Before Chainstart

### ISSUE THREAD

**Issue by Phistr90** [prysmaticlabs/prysm#5450] opened 2020-04-16 01:05 UTC
Would be very nice to get the feedback that the validator deposit has been processed and that the validator is ready to validate.

**Comment by xrow** [comment] 2020-04-16 05:26
I like the idea...

**Comment by prestonvanloon** [comment] 2020-04-21 21:23
We should add feedback that the validator is part of the genesis validator set when the chain is pre-genesis. Great suggestion and thanks for filing!

**Comment by ShawkiS** [comment] 2020-04-22 12:12
I'll take this one, it seems cool and will learn many things. @prestonvanloon can you please assign it to me?

**Comment by ShawkiS** [comment] 2020-04-22 12:44
Know the network => query the account on the network => take the amount he has => compare it on the amount he must has => and print it 

Where I have to print it?

-How do I know the network that the validator client is connected to?

-And when I know it's network x, how I query to check the balance of an account?

-Is there a constant about how much the validator client must have?

**Comment by rauljordan** [comment] 2020-04-22 14:54
1. First of all, let's look at the problem. Validators can be active _before_ the genesis time if they deposited pre-genesis. Say that genesis is tomorrow at midnight, the problem is if you're running a validator, you dont get any logs or feedback that you are ready once that time tomorrow comes.
2. Then, I would look at the lifecycle of a validator: what does a validator do when it starts up? It follows these steps: https://github.com/prysmaticlabs/prysm/blob/9e6b6bc0094c2bd9d3f15336f67886b9c692899e/validator/client/runner.go#L48.  Seems like it waits for genesis, then waits for activation. Once it receives a genesis time, it waits to see if the validator is active. What we can do is check if the validator is part of the genesis state and perhaps include that as part of the API response necessary.
3. Then, we verify what happens today to see where we could add this log:
I have this script to be able to run a local node for basic testing: https://gist.github.com/rauljordan/50302db7bb175c713d004cec8be601ea. You can make it so the genesis time is in the future and observe what the validator client logs. We want to make those logs more informative if a validator is active and prepared for genesis. 
4. Before writing any code, write up a brief design doc about how you plan on tackling this feature in a detailed manner. This way, we can give you feedback as a team before you begin coding in case you need to change your course. 
5. Write tests to ensure the feature works as expected.

**Comment by 0xKiwi** [comment] 2020-05-14 19:44
Hey @rauljordan, does #5849 help with this?

**Comment by rauljordan** [comment] 2020-05-14 20:09
Yep! You'll be receiving duties and show Validator activated pre-genesis time successfully. I think we can close this with that PR.

**Comment by fabdarice** [comment] 2020-11-15 22:17
I can take a look a this if needed. I recently look at `client/runner.go run()` so familiar with the life cycle of a validator.

**Comment by prestonvanloon** [comment] 2020-11-20 20:23
Can anyone confirm this issue is still relevant? 

Removing from v1 milestone since this isn't a release blocker.

**Comment by rauljordan** [comment] 2020-11-29 02:03
Unfortunately we did not get a chance to implement this feature, and since chainstart is in a few days and we have already created our final release before genesis, we are closing this

**Closed by rauljordan** 2020-11-29 02:03 UTC
Labels: Enhancement, Good First Issue, Help Wanted
