### ISSUE TITLE
 Unable to cache headers for execution client votes error

### ISSUE THREAD

**Issue by redhatlg** [prysmaticlabs/prysm#11464] opened 2022-09-19 00:24 UTC
Unable to cache headers for execution client votes error=(1663463511 > 1663224162): provided time is later than the current eth1 head。Hello, how to deal with the error reported in the latest version? Thank you

**Comment by prestonvanloon** [comment] 2022-09-20 16:55
Consolidating this as a duplicate of #11466.

**Closed by prestonvanloon** 2022-09-20 16:55 UTC
