### ISSUE TITLE
Handle Attester and Proposer Slashings in Operations Service

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#3259] opened 2019-08-21 14:12 UTC
Currently neither of the attester or proposer slashing objects are handled in the beacon node. If we receive the objects from other peers, there is no specific service to which we can hand it off to so that it is validated and then able to be packaged into a block by a proposer. This issue is to track the implementation of handlers for slashing messages in the operations service. 

Relevant to #2766

**Comment by rauljordan** [comment] 2019-12-16 16:22
This is a duplicate of #2766, closing

**Closed by rauljordan** 2019-12-16 16:22 UTC
Labels: Priority: High, Tracking
