### ISSUE TITLE
Add regression for `AttestationDelta` test

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#3458] opened 2019-09-12 22:01 UTC
We should add a test case where passing in duplicated attestations in state for `AttestationDelta` don't increment validator's profit more than once

**Comment by 0xKiwi** [comment] 2019-09-15 19:29
I can work on this!

**Comment by 0xKiwi** [comment] 2019-09-15 19:49
Closing due to regression test being added in #3469

**Closed** 2019-09-19 02:11 UTC
Labels: Enhancement
