### ISSUE TITLE
Beacon cannot be restarted after genesis event, before genesis block

### ISSUE THREAD

**Issue by yorickdowne** [prysmaticlabs/prysm#7366] opened 2020-09-28 19:54 UTC
# 🐞 Bug Report

### Description

On spadina testnet, prysm beacon was running and got to generating genesis state. It was then stopped and restarted.

This produces an error, see below.
Recovery by deleting the contents of the data directory and starting over worked.

```
thorsten@ethlinux:~/eth2-spadina$ sudo docker-compose run beacon
[2020-09-28 19:49:52]  WARN flags: Running Node on Spadina Testnet
[2020-09-28 19:49:52]  INFO flags: Using "max_cover" strategy on attestation aggregation
[2020-09-28 19:49:52]  INFO node: Checking DB database-path=/var/lib/prysm/beaconchaindata
[2020-09-28 19:49:53]  INFO node: Starting beacon node version=Prysm/v1.0.0-alpha.26/c7ff3a4f22409888838231e8205167e0220238d3. Built at: 2020-09-25 12:33:01+00:00
[2020-09-28 19:49:53]  INFO rpc: RPC-API listening on port address=0.0.0.0:4000
[2020-09-28 19:49:53]  WARN rpc: You are using an insecure gRPC server. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc
[2020-09-28 19:49:53]  INFO gateway: Starting JSON-HTTP API address=127.0.0.1:3500
[2020-09-28 19:49:53]  INFO blockchain: Blockchain data already exists in DB, initializing...
[2020-09-28 19:49:53]  INFO initial-sync: Genesis time has not arrived - not syncing genesisTime=2020-09-29 12:00:13 +0000 UTC
[2020-09-28 19:49:53] FATAL blockchain: Could not set up chain info: finalized state and block can't be nil
```

**Comment by prestonvanloon** [comment] 2020-09-28 20:04
Duplicate of #7356.

This is fixed, we are going to cherry pick into today's release (v1.0.0-alpha.27).

**Closed by prestonvanloon** 2020-09-28 20:04 UTC

**Comment by ChuckNorrison** [comment] 2020-09-29 12:14
Hits me...

Could not set up chain info: finalized state and block can't be nil
