### ISSUE TITLE
Validator status "PARTIALLY_DEPOSITED" though 32 Eth deposited

### ISSUE THREAD

**Issue by rofra** [prysmaticlabs/prysm#7174] opened 2020-09-04 12:08 UTC
# 💎 Issue

### Background

I just created my validator node, connected to my beacon node fully synced, all set. The 2 nodes are running the *v1.0.0-alpha.24* release

### Description

In my Validator's log, I see multiple lines with some kind on line like this:
```
time="2020-09-04 12:00:37" level=info msg="Waiting for deposit to be observed by beacon node" prefix=validator pubKey=0x88170e3e5db8 status="UNKNOWN_STATUS"
time="2020-09-04 12:00:49" level=info msg="Waiting for deposit to be observed by beacon node" prefix=validator pubKey=0xb1508b861268 status="UNKNOWN_STATUS"
time="2020-09-04 12:00:49" level=info msg="Waiting for deposit to be observed by beacon node" prefix=validator pubKey=0x93b66bfd7846 status="UNKNOWN_STATUS"
time="2020-09-04 12:00:49" level=info msg="Waiting for deposit to be observed by beacon node" prefix=validator pubKey=0x88d57d22842d status="UNKNOWN_STATUS"
time="2020-09-04 12:00:49" level=info msg="Validator status" activationEpoch=18446744073709551615 index=56423 prefix=validator pubKey=0xb65148cfde8a status="PARTIALLY_DEPOSITED"

```
Here the logs for transition from DEPOSITED to PARTIALLY_DEPOSITED:
```
time="2020-09-04 01:48:08" level=info msg="Deposit processed, entering activation queue after finalization" index=5642
3 positionInActivationQueue=9785 prefix=validator pubKey=0xb65148cfde8a status=DEPOSITED
time="2020-09-04 01:48:08" level=info msg="Waiting for deposit to be observed by beacon node" prefix=validator pubKey=
0x88170e3e5db8 status="UNKNOWN_STATUS"
time="2020-09-04 01:48:20" level=info msg="Waiting for deposit to be observed by beacon node" prefix=validator pubKey=
0xb1508b861268 status="UNKNOWN_STATUS"
time="2020-09-04 01:48:20" level=info msg="Waiting for deposit to be observed by beacon node" prefix=validator pubKey=
0x93b66bfd7846 status="UNKNOWN_STATUS"
time="2020-09-04 01:48:20" level=info msg="Waiting for deposit to be observed by beacon node" prefix=validator pubKey=
0x88d57d22842d status="UNKNOWN_STATUS"
time="2020-09-04 01:48:20" level=info msg="Validator status" activationEpoch=18446744073709551615 index=56423 prefix=validator pubKey=0xb65148cfde8a status="PARTIALLY_DEPOSITED"
```

I do not understand why it is named Paritally deposited becouse I sent exactly 32 ETH to the validator contract
See my validator page: https://beaconcha.in/validator/b65148cfde8a702579d5e2e2f5f7044a41f6d4bd83728500d92cf39d44ea417f77e4f1276e86fb76de0820c2be98a581#overview

It looks like my node is in "Pending" state (https://notes.ethereum.org/@hww/lifecycle#42-Step-2-Eligible-to-be-activated-Pending) with the node not activated yet. Though, the ETH balance dedicated to staking seems to be considered as 0, wich could be a sign of Partial Deposit => False Positive

### Improvement Proposal

Maybe we should improve the logs in that way to distinguish the case of Pending Node with no ETH in Stake, and Activated Node with less the MIN Deposit value ?

**Comment by alexfisher** [comment] 2020-09-09 12:52
Came here to report this and found this issue.  Noticed my validator is scheduled to become active in 2 days and is showing PARTIALLY_DEPOSITED.  I was confused because there are definitely 32 ETH that were deposited on Goerli:

https://medalla.beaconcha.in/validator/b661350862b5c283f981154eb4c900dabcd1c4c7356bc63d6461aceccd28828ef66e704371dc0b6f14d67e3dcc349b21#deposits

**Comment by alexfisher** [comment] 2020-09-09 12:56
Taking another look at logs, and it looks like Activation Epoch is messed up?

```
Sept 09 08:54:12 validator time="2020-09-09 12:54:12" level=info msg="Validator status" activationEpoch=18446744073709551615 index=53641 prefix=validator pubKey=0xb661350862b5 status="PARTIALLY_DEPOSITED"
```

**Comment by nivBlox** [comment] 2020-09-10 07:04
@All our pending validators has PARTIALLY_DEPOSITED status too. some have exactly 32 balance and some have more than 32 so the status should not be PARTIALLY_DEPOSITED.
By the way one of the validators became active even that the status was PARTIALLY_DEPOSITED.


--------------------------------------------------------------
@alexfisher use the "positionInActivationQueue" in order to get the position in queue. Using that you can calculate the activation epoch.  This is not related to the PARTIALLY_DEPOSITED changes.

request - 
https://api.prylabs.neteth/v1alpha1/validator/status?publicKey=tmE1CGK1woP5gRVOtMkA2rzRxMc1a8Y9ZGGs7M0ogo72bnBDcdwLbxTWfj3MNJsh
response - 
`{
    "status": "PARTIALLY_DEPOSITED",
    "eth1DepositBlockNumber": "0",
    "depositInclusionSlot": "0",
    "activationEpoch": "18446744073709551615",
    "positionInActivationQueue": "2071"
}`

**Comment by raphpa** [comment] 2020-09-10 09:35
Duplicate of #7137 
Fix is not in the precompiled binaries yet.

**Comment by rauljordan** [comment] 2020-09-16 19:54
Resolved in alpha.25

**Closed by rauljordan** 2020-09-16 19:54 UTC
