### ISSUE TITLE
Prsym Validator Does Not "Wait" On Beacon Chain and Resume as Expected

### ISSUE THREAD

**Issue by allsilent** [prysmaticlabs/prysm#6325] opened 2020-06-20 13:44 UTC
# 🐞 Bug Report

### Description

 
**Situation:** Two services - prysmbc and prysmval. They simply call the prsym.sh script for the beacon chain node and the validators, respectively. Services are set to auto-restart on failure or reboot. Both are stable and nominal save for this issue.
**Expected Behavior based on Topaz:** If restarting the services or the machine, the beacon chain and validators should restart and resume from where they left off, with a minor lapse for the BC node to re-sync up from its downtime. 
**Actual Behavior, New to Onyx:** With any restart of the machine or individual processes, prysmbc and prysmval restart appropriately, but prysmval is stuck on waiting for the BC, despite the BC getting back in sync, until I manually restart prsymval following that re-sync. See the output and explanation to follow.
### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: All releases on Topaz

## 🔬 Minimal Reproduction

Prysm BC Service
<pre></code>
[Unit]
Description=Prysm Beacon Chain Node
After=syslog.target network.target
Wants=network.target

[Service]
WorkingDirectory=/home/ubuntu
ExecStart=/mnt/ssd/prysm/prysm.sh beacon-chain --datadir /mnt/ssd/prysm --p2p-host-dns allsilent.ddns.net --grpc-gateway-port 3500 --skip-regen-historical-states
User=ubuntu
Group=ubuntu
Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target
</pre></code>

Prysm Val Service
<pre><code>
[Unit]
Description=Prysm Validator Node
After=syslog.target network.target prysmbc.service
Wants=network.target

[Service]
WorkingDirectory=/home/ubuntu
ExecStart=/mnt/ssd/prysm/prysm.sh validator --datadir /mnt/ssd/prysm --keymanager=wallet --keymanageropts=/mnt/ssd/prysm/wallet.json --graffiti "This validator action brought to you by allsilent!"
User=ubuntu
Group=ubuntu
Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target
</pre></code>

Start/Restart the services either manually via systemctl, or by restarting the system, as they are enabled to run automatically. Any method will create this issue, as long as the BC is offline long enough to require even a few seconds of re-syncing.

## 🔥 Error
<pre><code>

.....
Jun 20 08:42:25 raspi2 prysm.sh[1338]: time="2020-06-20 08:42:25" level=info msg="Checking DB" databasePath="/mnt/ssd/prysm" prefix=node
Jun 20 08:42:25 raspi2 prysm.sh[1338]: time="2020-06-20 08:42:25" level=info msg="Starting validator node" prefix=node version="Prysm/v1.0.0-alpha.12/802bdf5561a8c713fc2a8ae5b16cdb02b192e94a. Built at: 2020-06-17 21:46:03+00:00"
Jun 20 08:42:25 raspi2 prysm.sh[1338]: time="2020-06-20 08:42:25" level=warning msg="You are using an insecure gRPC connection. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc" prefix=validator
Jun 20 08:42:25 raspi2 prysm.sh[1338]: time="2020-06-20 08:42:25" level=info msg="Waiting for beacon chain start log from the ETH 1.0 deposit contract" prefix=validator

***Right here, prysmval will just sit and wait, even after the BC is fully synced and ready to go. Instead of just starting off on its own, it then requires me to systemctl restart prysmval, at which point it gets right back to validating***

***That is, I issue the restart prysmval command, and then it has no problem***
> sudo systemctl restart prysmval
.....
Jun 20 08:44:19 raspi2 prysm.sh[1825]: time="2020-06-20 08:44:19" level=info msg="Waiting for beacon chain start log from the ETH 1.0 deposit contract" prefix=validator
Jun 20 08:44:19 raspi2 prysm.sh[1825]: time="2020-06-20 08:44:19" level=info msg="Beacon chain started" genesisTime=2020-06-14 05:17:24 +0000 UTC prefix=validator
Jun 20 08:44:19 raspi2 prysm.sh[1825]: time="2020-06-20 08:44:19" level=info msg="Validator activated" index=5536 prefix=validator publicKey=0xb804b8630143
Jun 20 08:44:19 raspi2 prysm.sh[1825]: time="2020-06-20 08:44:19" level=info msg="Validator activated" index=9990 prefix=validator publicKey=0x97b95a4f2da0
.....
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04 LTS Raspberry Pi 4
Linux raspi2 5.4.0-1012-raspi #12-Ubuntu SMP Wed May 27 04:08:35 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Prysm/v1.0.0-alpha.12/802bdf5561a8c713fc2a8ae5b16cdb02b192e94a
  </code>
</pre>

**Comment by shayzluf** [comment] 2020-06-24 12:39
@farazdagi please reassign to me if it seems inappropriate

**Comment by prestonvanloon** [comment] 2020-06-26 20:15
This is related to new state management. Reassigning to @terencechain.

@terencechain what can we do to solve this problem when a user shuts down their node brief (for an update) and starts resyncing from the last state checkpoint, which can be a non-trivial amount of time?

What about saving the current finalized state as a new checkpoint upon Stop() for some service? This would allow the user to sync from the last finalized state instead of the last snapshot in the new state management.

**Comment by terencechain** [comment] 2020-06-26 20:33
> This is related to new state management. Reassigning to @terencechain.
> 
> @terencechain what can we do to solve this problem when a user shuts down their node brief (for an update) and starts resyncing from the last state checkpoint, which can be a non-trivial amount of time?
> 
> What about saving the current finalized state as a new checkpoint upon Stop() for some service? This would allow the user to sync from the last finalized state instead of the last snapshot in the new state management.

There's nothing we can do without having to significantly redesign the new state mgmt. A node always start from last archived point which was the agreed design choice since day 0. (LH does this too) Starting from last finalized checkpoint means falling back to the old state design area which there's further tradeoff to explore. Sync an extra 2048 slots (worst case) is an extra 30 seconds of time. Given there's higher priority items around, I personally won't pursue this until mainnet.

**Comment by prestonvanloon** [comment] 2020-06-26 22:28
I think we should consider this before mainnet launch. It is optimistic to think 2048 adds only 30 seconds of time to the start up. It could be several minutes or even more than 1 epoch for a beacon node to restart, find peers, and sync to head. 

There must be some solution. Do we save blocks at least? 
At a minimum, replaying the blocks would be faster than fetching them via sync.

**Comment by terencechain** [comment] 2020-06-26 22:48
> I think we should consider this before mainnet launch. It is optimistic to think 2048 adds only 30 seconds of time to the start up (in the user report, it took two minutes). It could be several minutes or even more than 1 epoch for a beacon node to restart, find peers, and sync to head.
> 
> There must be some solution. Do we save blocks at least?
> At a minimum, replaying the blocks would be faster than fetching them via sync.

We do save the blocks. The replay of 2048 slots (worst case) is much faster. 30s was my pessimistic estimate. It's around 15s In my set up:
 * via sync, no blocks in db - ~40bps
 * recompute to catch up, blocks in db - ~90bps

**Comment by terencechain** [comment] 2020-06-26 22:49
Agree on considering this before mainnet launch. The UX can be better here. I have bumped up the priority

**Comment by prestonvanloon** [comment] 2020-06-26 23:16
I have a solution for this https://github.com/prysmaticlabs/prysm/pull/6431

Let me know what you think @terencechain

**Comment by prestonvanloon** [comment] 2020-06-27 03:09
After offline discussion with @terencechain, we are considering a bigger change to support the idea in #6431. The issue with accepting #6431 in its current state is that hot/cold state mgmt assumes there will be only one state stored per checkpoint interval. Since the change in #6431 overwrites the existing checkpoint index in the database, it may cause another regression where look ups involving regenerating state from a cold state checkpoint may take significantly longer. 

Working design doc here: https://hackmd.prylabs.network/0I7wLGC4TZa50BtZcz0Mng?view

**Comment by prestonvanloon** [comment] 2020-07-03 18:41
Related PRs:
- #6486 
- #6480 
- #6464 (to be closed, split into smaller PRs)
- #6460 (closed)
- #6461 
- #6457 
- #6431

**Comment by remyroy** [comment] 2020-07-14 19:32
I believe I just experienced this issue on _v1.0.0-alpha.15_ and on _Ubuntu 20.04 LTS (GNU/Linux 5.4.0-1013-raspi aarch64)_ . My workaround was to restart the validator after the beacon chain was fully synced.

**Comment by nisdas** [comment] 2020-08-06 12:49
This has been reported again, re-opening the issue

**Comment by WMEth** [comment] 2020-08-06 13:15
Still occasionally experiencing the same problem originally reported here:

If validator and beacon chain are started together e.g. with systemd (calling prysm.sh), the validator prints "Waiting for beacon chain start log from the ETH 1.0 deposit contract" and stays there.

Restarting the validator resolves the issue, but the system does not boot to a functional state.

The validator is failing to notice when the beacon node has finished syncing.

**Comment by nisdas** [comment] 2020-08-26 10:55
Closed by #7112

**Closed by nisdas** 2020-08-26 10:55 UTC
Labels: Bug, Priority: Medium
