### ISSUE TITLE
"./prysm.sh beacon-chain" command freezes in case beacon chain is already running and internet connection is unavailable

### ISSUE THREAD

**Issue by Pacittos** [prysmaticlabs/prysm#5719] opened 2020-05-02 21:50 UTC
# 🐞 Bug Report

### Description

In case a user has a beacon-chain running, and tries to start a second beacon chain it should fail with the following output:
`ERROR main: cannot obtain database lock, database may be in use by another process. `
However, when a user has the first beacon chain running, then loses internet connection, and tries to start a beacon chain in a new terminal (maybe the user doesn't realize the beacon chain is already running in another terminal), `./prysm.sh beacon-chain` freezes

### Has this worked before in a previous version?

Don't know

## 🔬 Minimal Reproduction

Terminal 1:` /prysm.sh beacon-chain` -> Successfully syncs and keeps running
Turn off internet connection -> In background terminal 1 loses it peers
Terminal 2:` /prysm.sh beacon-chain` -> Try starting 2nd beacon chain, which should return an error

Effect: 
Terminal 2 never outputs an error message and seems to be stuck in the prysm.sh script and ctrl+c is required to terminate the script.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 18.04.4
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
 v1.0.0-alpha.6
  </code>
</pre>

**Comment by shayzluf** [comment] 2020-05-04 15:58
tried to reproduce process wasn't seem to get stuck but no error message was received

**Comment by shayzluf** [comment] 2020-05-04 16:02
Duplicate of #5718

**Comment by shayzluf** [comment] 2020-05-04 16:04
@Pacittos closing this in favour of #5718

**Closed by shayzluf** 2020-05-04 16:04 UTC
Labels: Bug, Help Wanted
