### ISSUE TITLE
API endpoint does not yet allow fetching NEXT sync committee members using future slot number

### ISSUE THREAD

**Issue by emptymindgit** [prysmaticlabs/prysm#9941] opened 2021-11-24 22:28 UTC
API endpoint does not yet allow fetching NEXT sync committee members using future slot number, even though next sync committee members are already known.

**Example:**
`curl http://localhost:3500/eth/v1/beacon/states/2572288/sync_committees`
_(In this case, '2572288' was the first slot in the next sync committee after the current chain head)_

**Returns:**
`{"message":"Could not fetch beacon state using request: rpc error: code = Internal desc = Invalid state ID: slot cannot be in the future","code":500}`

**Comment by potuz** [comment] 2021-11-24 23:44
Thanks for filing this. We better keep track of the issues together, marking as duplicate of #9940 . This should be fixed right away

**Closed by potuz** 2021-11-24 23:44 UTC
