### ISSUE TITLE
Add capability to narrow down to which signature fails 

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#11582] opened 2022-10-26 21:10 UTC
For performance reasons, we batch-verify all the signatures in the block. The downside of this is if any of the signatures are invalid, the process block will fail and there's no way to which signature was invalid on what object. It may be nice to provide an option to Prysm state transition cmd to identify precisely which signature is invalid. This could also be part of prysmctl util

**Comment by dyng** [comment] 2022-12-07 03:14
Hi, I'm willing to fix this issue, please assign it to me.

After exploring the code, I found all signatures are rolled up in `ProcessBlockNoVerifyAnySig` then verified as a batch in `ExecuteStateTransition` and `onBlockBatch`, if the verification fails, error `signature in block failed to verify` is returned.

I have an idea to approach the problem is that **verify each signature one by one if batch verification failed, and returns an error when anyone is invalid**. But the error message is vague because there is no description attached with the signature. How about we add a new field in `SignatureBatch` to hold a description about signature?

```go
type SignatureBatch struct {
	Signatures [][]byte
	PublicKeys []PublicKey
	Messages   [][32]byte
	Descriptions []string
}
```

**Closed** 2022-12-20 10:41 UTC
Labels: Enhancement, Help Wanted
