### ISSUE TITLE
Handle gRPC Disconnections Gracefully in Validator Client

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#632] opened 2018-10-09 02:17 UTC
Hi all,

Currently, validator does not attempt to restart its main workflow if it disconnects from a running beacon node. Thus, the beacon node sleeping can lead to issues similar to what Danny encountered in #622. If gRPC disconnects or we encounter some sort of fatal error, the validator should attempt to reset and start again from scratch as if it just connected to a beacon node. A PR for this would resolve the problem and work correctly at runtime.

**Comment by prestonvanloon** [comment] 2018-10-09 02:31
Can you elaborate more on how to reproduce this issue? 

I think gRPC will attempt to reconnect automatically unless the server explicitly states that it is shutting down. https://github.com/grpc/grpc-go/blob/8d75951f9be037a31565f412b01a632032fc4a5a/clientconn.go#L1174

See onGoAway (when the server goes away and the client attempts to reconnect): https://github.com/grpc/grpc-go/blob/8d75951f9be037a31565f412b01a632032fc4a5a/clientconn.go#L1059

The caveat is that we don't use a context with a timeout to dial the server and this is the case for our code since we are not using DialContext, but Dial (which uses context.Background()). 

In fact, looking at #622, it was the Beacon chain node that crashed and you can see the validator attempt to reconnect. The relevant logging is:
```
[2018-10-03 16:52:12] ERROR beacon: Could not receive latest attestation from stream: rpc error: code = Unavailable desc = transport is closing
```

This means the server is offline on the reconnection attempt.

**Comment by prestonvanloon** [comment] 2018-10-09 10:29
I'm closing this since gRPC gracefully handles client reconnections. 
I believe the underlying issue in #622 is server side.

**Closed by prestonvanloon** 2018-10-09 10:29 UTC
Labels: Bug, Good First Issue
