### ISSUE TITLE
validator reports incorrect prevBalance with multiple accounts

### ISSUE THREAD

**Issue by ethDreamer** [prysmaticlabs/prysm#2772] opened 2019-06-09 21:32 UTC
When staking with multiple keys, the validator thinks each account started with the sum of all account balances.  This causes it to calculate losses incorrectly.

![weirdstart](https://user-images.githubusercontent.com/37123614/59164554-87f61380-8adc-11e9-9466-c6482644651a.png)

**Comment by zediir** [comment] 2019-06-09 23:08
duplicate of https://github.com/prysmaticlabs/prysm/issues/2573

**Comment by prestonvanloon** [comment] 2019-06-10 16:54
Closing as duplicate of #2573

**Closed by prestonvanloon** 2019-06-10 16:54 UTC
