### ISSUE TITLE
SIGILL: illegal instruction

### ISSUE THREAD

**Issue by alexstaj** [prysmaticlabs/prysm#8411] opened 2021-02-08 17:25 UTC
HI All

Trying to follow the guide but can't start beacon-chain for some reason.  This is running in a proxmox 6.2-11 container.  CPU is E5-2680-v2.  GETH is running with syncmode=fast and --http option is on.  Please help.

```
root@eth:~/prysm# ./prysm.sh beacon-chain --http-web3provider=http://localhost:8545
Latest Prysm version is v1.2.0.
Beacon chain is up to date.
Verifying binary integrity.
beacon-chain-v1.2.0-linux-amd64: OK
gpg: Signature made Fri Feb  5 18:43:26 2021 UTC
gpg:                using RSA key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E
gpg: Good signature from "Preston Van Loon <preston@prysmaticlabs.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0AE0 051D 647B A3C1 A917  AF40 72E3 3E4D F1A5 036E
Verified /root/prysm/dist/beacon-chain-v1.2.0-linux-amd64 has been signed by Prysmatic Labs.
Starting Prysm beacon-chain --http-web3provider=http://localhost:8545
SIGILL: illegal instruction
PC=0x16f7784 m=0 sigcode=2
signal arrived during cgo execution
instruction bytes: 0xc4 0x62 0xbb 0xf6 0xe 0xc4 0x62 0xfb 0xf6 0x56 0x8 0x49 0x1 0xc1 0xc4 0x62

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x167aa80, 0xc0003a9de8, 0x8)
	GOROOT/src/runtime/cgocall.go:133 +0x5b fp=0xc0003a9db8 sp=0xc0003a9d80 pc=0x42417b
github.com/herumi/bls-eth-go-binary/bls._Cfunc_blsInit(0xf600000005, 0xc000000000)
	_cgo_gotypes.go:422 +0x4d fp=0xc0003a9de8 sp=0xc0003a9db8 pc=0xcd5aed
github.com/herumi/bls-eth-go-binary/bls.Init(0x5, 0x0, 0x0)
	bls.go:63 +0x45 fp=0xc0003a9e40 sp=0xc0003a9de8 pc=0xcdad65
github.com/prysmaticlabs/prysm/shared/bls/herumi.init.0()
	shared/bls/herumi/init.go:6 +0x2e fp=0xc0003a9e68 sp=0xc0003a9e40 pc=0xce47ee
runtime.doInit(0x29620e0)
	GOROOT/src/runtime/proc.go:5652 +0x8a fp=0xc0003a9e98 sp=0xc0003a9e68 pc=0x4681ca
runtime.doInit(0x295cc00)
	GOROOT/src/runtime/proc.go:5647 +0x57 fp=0xc0003a9ec8 sp=0xc0003a9e98 pc=0x468197
runtime.doInit(0x296af00)
	GOROOT/src/runtime/proc.go:5647 +0x57 fp=0xc0003a9ef8 sp=0xc0003a9ec8 pc=0x468197
runtime.doInit(0x2970860)
	GOROOT/src/runtime/proc.go:5647 +0x57 fp=0xc0003a9f28 sp=0xc0003a9ef8 pc=0x468197
runtime.doInit(0x29648c0)
	GOROOT/src/runtime/proc.go:5647 +0x57 fp=0xc0003a9f58 sp=0xc0003a9f28 pc=0x468197
runtime.doInit(0x296d8c0)
	GOROOT/src/runtime/proc.go:5647 +0x57 fp=0xc0003a9f88 sp=0xc0003a9f58 pc=0x468197
runtime.main()
	GOROOT/src/runtime/proc.go:191 +0x1c5 fp=0xc0003a9fe0 sp=0xc0003a9f88 pc=0x45ae45
runtime.goexit()
	GOROOT/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0003a9fe8 sp=0xc0003a9fe0 pc=0x491881

goroutine 21 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc00025e420)
	external/com_github_dgraph_io_ristretto/policy.go:96 +0xc5
created by github.com/dgraph-io/ristretto.newDefaultPolicy
	external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 22 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc0001130e0)
	external/com_github_dgraph_io_ristretto/cache.go:314 +0xed
created by github.com/dgraph-io/ristretto.NewCache
	external/com_github_dgraph_io_ristretto/cache.go:162 +0x22f

goroutine 50 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc000122fc0)
	external/com_github_dgraph_io_ristretto/policy.go:96 +0xc5
created by github.com/dgraph-io/ristretto.newDefaultPolicy
	external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 51 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc000388300)
	external/com_github_dgraph_io_ristretto/cache.go:314 +0xed
created by github.com/dgraph-io/ristretto.NewCache
	external/com_github_dgraph_io_ristretto/cache.go:162 +0x22f

goroutine 66 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc000418030)
	external/com_github_dgraph_io_ristretto/policy.go:96 +0xc5
created by github.com/dgraph-io/ristretto.newDefaultPolicy
	external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 67 [runnable]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc0004419e0)
	external/com_github_dgraph_io_ristretto/cache.go:312
created by github.com/dgraph-io/ristretto.NewCache
	external/com_github_dgraph_io_ristretto/cache.go:162 +0x22f

rax    0x7fc
rbx    0x331c5d0
rcx    0x2af2f68
rdx    0xc999e990f3f29c6d
rdi    0x16f7390
rsi    0x7ffe9078c360
rbp    0x16f7401
rsp    0x7ffe9078c300
r8     0x331c5d0
r9     0x2af2f60
r10    0x6e2a5bb9c8db33e9
r11    0xc999e990f3f29c6d
r12    0x4
r13    0x7ffe9078c368
r14    0x2af2f60
r15    0x33205b0
rip    0x16f7784
rflags 0x10206
cs     0x33
fs     0x0
gs     0x0

```

**Comment by prestonvanloon** [comment] 2021-02-08 17:33
Thanks for the report! I've filed one just before you, so let's consolidate into one issue.

Duplicate of #8410

**Closed by prestonvanloon** 2021-02-08 17:33 UTC
