### ISSUE TITLE
Killed every once in a while

### ISSUE THREAD

**Issue by 953446** [prysmaticlabs/prysm#13270] opened 2023-12-05 18:13 UTC
### Describe the bug

geth version 1.13.3-unstable-f988b233-20230929

Prysm version v4.1.1

![image](https://github.com/prysmaticlabs/prysm/assets/128539227/504c57e8-2b00-4558-885b-2acb78f33ec7)

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

v4.1.1

**Comment by prestonvanloon** [comment] 2023-12-05 18:16
@953446 can you give some details about your system? How much RAM do you have?

**Comment by 953446** [comment] 2023-12-05 18:46
> @953446您能提供一些有关您的系统的详细信息吗？你有多少内存？

Hello, the following is my system information
CentOS 7.9.2009 x86_64
CPU 16 cores
64G running memory
2TB storage space, currently about 900GB free

**Comment by prestonvanloon** [comment] 2023-12-08 15:25
Thanks for the reports. It could be related to state replays. I'll try to reproduce this and grab a memory profile

**Comment by 953446** [comment] 2023-12-09 03:14
> 感谢您的报告。这可能与状态重播有关。我将尝试重现此内容并获取内存配置文件

Thanks for your reply, I usually get killed once every 4-5 days

**Comment by 953446** [comment] 2023-12-13 13:45
May I ask if the problem has been solved? I was killed again @prestonvanloon

**Comment by 953446** [comment] 2023-12-13 13:46
![image](https://github.com/prysmaticlabs/prysm/assets/128539227/7f8609d7-c65d-40df-a756-94bb9bfc8e0f)
This forced me to reboot

**Comment by prestonvanloon** [comment] 2023-12-18 21:03
Thanks @953446, I still have not been able to reproduce the issue yet. I'll update here when I can replicate it and understand where the memory usage is.

**Comment by 953446** [comment] 2023-12-22 13:52
@prestonvanloon Hello, have you reproduced this problem? I was killed again.This picture has my startup information, please check it out
![image](https://github.com/prysmaticlabs/prysm/assets/128539227/9cdc4984-bc38-4ef3-9872-850d88bbe898)

**Comment by 953446** [comment] 2023-12-22 14:11
My server resource monitor shows that prysm occupied too many resources and was killed.
CPU
![image](https://github.com/prysmaticlabs/prysm/assets/128539227/95caf1e0-df85-48de-8490-d7754ed02cfc)
Memory
![image](https://github.com/prysmaticlabs/prysm/assets/128539227/596a0d48-d263-44ce-bcb2-f4f7222828fd)
disk
![image](https://github.com/prysmaticlabs/prysm/assets/128539227/02e74b1d-1abc-4ecc-a1d3-b7373aba560c)

**Comment by 953446** [comment] 2023-12-22 14:26
I think you can find the problem with the information I provided. Please help me solve it as soon as possible.
@prestonvanloon  Thank you so much

**Comment by 953446** [comment] 2023-12-30 23:18
![image](https://github.com/prysmaticlabs/prysm/assets/128539227/781ca793-a02c-4ae3-ae76-921c62f4fabd)
Memory

**Comment by Piradoxlanieve** [comment] 2024-01-27 07:27
![nodo](https://github.com/prysmaticlabs/prysm/assets/10765838/6e98f6d8-c35a-4510-be9a-012a88b84023)
I think I have a similar problem, since I turned off the virtual machine in Promox a few days ago to do maintenance on the main computer almost every day the node stays off, losing attestations and I have to restart all the services manually many times since it automatically usually left with problems
I have increased from 16GB of ram to 24GB, this did not happen before.
Sorry my english

**Comment by prestonvanloon** [comment] 2024-03-20 20:49
I think this issue has been resolved in the changes for v5. Please reply to the issue if you are still facing memory issues. 

@jsvisa if you are still having issues with that particular endpoint, please file a new issue.

**Closed by prestonvanloon** 2024-03-20 20:49 UTC
Labels: Bug

**Comment by Fantasim** [comment] 2024-04-03 14:03
Same problem in the version v5.0.1 and 5.0.2 both @prestonvanloon
