### ISSUE TITLE
Can't create accounts using windows 10 if username has spaces

### ISSUE THREAD

**Issue by wgknowles** [prysmaticlabs/prysm#5716] opened 2020-05-02 15:25 UTC
# 🐞 Bug Report

When attempting to run 'validator create accounts' on Windows 10 with a username with a space in it validator throws a "Permission Denied" error.

**Comment by wgknowles** [comment] 2020-05-04 18:13
Report is on behalf of another user: 
Crypto_Thoughts05/03/2020
Hi! I ran into a bug that could prevent some users from being able to create accounts on Windows 10. My User has a space in its name. For some reason this causes the create accounts script throw an error. I was getting "Permission Denied" from my command prompt. I then created a new user that did not contain a space. I re-cloned the repository and ran the script and it worked. -- Thanks

**Comment by wgknowles** [comment] 2020-05-04 18:15
C:\Prysm\prysm>prysm.bat validator accounts create --keystore="C:\Prysm\validator folder"
A subdirectory or file C:\Prysm\prysm\dist already exists.
Latest prysm release is v1.0.0-alpha.6.
Using prysm version v1.0.0-alpha.6.
'Validator' is not recognized as an internal or external command,
operable program or batch file.
WARN GPG verification is not natively available on Windows.
WARN Skipping integrity verification of downloaded binary
Verifying binary authenticity with SHA256 Hash.
SHA256 Hash Match
Starting Prysm validator accounts create --keystore="C:\Prysm\validator folder"
2020/05/05 04:14:38 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
Incorrect Usage: flag provided but not defined: -keystore

NAME:
   validator accounts create -

USAGE:
   validator accounts create [command options] [arguments...]

DESCRIPTION:
   creates a new validator account keystore containing private keys for Ethereum Serenity -
this command outputs a deposit data string which can be used to deposit Ether into the ETH1.0 deposit
contract in order to activate the validator client

OPTIONS:
   --keystore-path value  Path to the desired keystore directory
   --password value       String value of the password for your validator private keys
   --help, -h             show help (default: false)

[2020-05-05 04:14:38] ERROR main: flag provided but not defined: -keystore
ERROR FAILED
an error has occured, set PRYSM_AUTORESTART=1 to automatically restart

**Comment by wgknowles** [comment] 2020-05-04 18:17
prysm.bat validator accounts create --keystore-path="C:\Prysm\validator folder"

Above command works fine.

**Comment by wgknowles** [comment] 2020-05-04 18:19
Perhaps user error?

**Comment by wgknowles** [comment] 2020-05-04 18:20
pragmatics05/03/2020
Thanks for the report.  did you happen to specify a --keystore path explicitly?
Crypto_Thoughts05/03/2020
No I did not

**Comment by wgknowles** [comment] 2020-05-04 18:21
duplicate of #5538

**Comment by prestonvanloon** [comment] 2020-05-04 18:48
Closing as duplicate of  #5538

**Comment by fabdarice** [comment] 2020-06-06 03:20
I'm on mac, unfortunately, but was trying to reproduce it by setting:
```
func homeDir() string {
	return "C:/Users/User With Space"
```
This doesn't appear to be failing.

**Comment by fabdarice** [comment] 2020-06-06 05:39
oh nvm, it attempts to create a folder, which is probably what is causing a "Permission Denied" for Windows User.
I'll investigate more tomorrow.

**Comment by shayzluf** [comment] 2020-08-06 14:48
assigned to @0xKiwi due to having windows machine

**Comment by rauljordan** [comment] 2020-08-06 16:20
No longer relevant

**Closed by rauljordan** 2020-08-06 16:20 UTC
Labels: Bug, Good First Issue
