### ISSUE TITLE
ERROR sync: Failed to close stream error=EOF

### ISSUE THREAD

**Issue by tunlong** [prysmaticlabs/prysm#5875] opened 2020-05-15 23:57 UTC
I have an issue with ERROR sync: Failed to close stream error=EOF. This error will appear every few seconds. The programme is the lastst version beacon-chain-v1.0.0-alpha.8-linux-amd64. Any suggestion? Thanks.

![image](https://user-images.githubusercontent.com/32350461/82104966-8650b900-974b-11ea-9e43-74100f6dc5df.png)

**Comment by 0xKiwi** [comment] 2020-05-16 01:53
Hey @tunlong ! Thanks for submitting an issue! 
@farazdagi , any clue on what could be causing this?

**Comment by farazdagi** [comment] 2020-05-16 11:24
I looks lot like sth writing into a closed stream. Since message refers to "failure to close stream" it seems we are closing sth that has already been closed (say peer disconnects too early).
 
Will try to figure this out, but overall this shouldn't prevent from syncing - and mostly cosmetic issue for now.

**Comment by rauljordan** [comment] 2020-06-11 18:56
Duplicate of #5763

**Closed by rauljordan** 2020-06-11 18:56 UTC
Labels: Bug, Sync
