### ISSUE TITLE
OOM on 16gb machine

### ISSUE THREAD

**Issue by lil0uuu** [prysmaticlabs/prysm#13543] opened 2024-01-27 08:28 UTC
### Describe the bug

Prysm keeps OOming when running geth + prysm on the same 16gb machine. It seems like it's OOming even more when it needs to catch up. I couldn't find any flag to limit the ram usage. Is there any?

Can prysm not run on a 16gb machine anymore?

thanks 

### Has this worked before in a previous version?

It was OOming maybe once a month or so before. Now basically every day or multiple times a day.

### What version of Prysm are you running? (Which release)

v4.2.0

**Comment by yorickdowne** [comment] 2024-01-31 08:35
Not a bug. You can try and make this fit by reducing Geth cache to 3072 or 2048.

RAM is cheap: If you can, do 32 GiB RAM.

There are few client combos that fit into 16 GiB without tweaks to reduce memory use.

**Comment by prestonvanloon** [comment] 2024-02-09 17:17
Closing this issue. As Yorick mentioned, running both EL and CL clients on a machine with only 16Gb is not recommended.

**Closed by prestonvanloon** 2024-02-09 17:17 UTC
Labels: Bug
