### ISSUE TITLE
k8s.io/client-go ,the version is too low

### ISSUE THREAD

**Issue by easydo666** [prysmaticlabs/prysm#14372] opened 2024-08-22 07:05 UTC
### Describe the bug

../../../../pkg/mod/github.com/prysmaticlabs/prysm/v5@v5.0.3/beacon-chain/cache/common.go:10:23: cannot use popProcessNoopFunc (value of type func(_ interface{}) error) as "k8s.io/client-go/tools/cache".PopProcessFunc value in argument to queue.Pop

The version of k8s.io/client-go referenced is too low, and the function "type PopProcessFunc func(obj interface{}, isInInitialList bool) error" has an extra bool

**Comment by prestonvanloon** [comment] 2024-08-22 19:08
Closing as duplicate of #13958

**Closed by prestonvanloon** 2024-08-22 19:08 UTC
Labels: Bug
