### ISSUE TITLE
cannot compile kiln branch on windows.

### ISSUE THREAD

**Issue by galaxy4627** [prysmaticlabs/prysm#10476] opened 2022-04-02 13:10 UTC
# 🐞 Bug Report

### Description

I am trying to compile Kiln branch on Windows but it fails everytime

### Has this worked before in a previous version?

 dk what to say

## 🔬 Minimal Reproduction
git clone -b kiln https://github.com/prysmaticlabs/prysm.git
cd prysm
bazel build  //cmd/beacon-chain:beacon-chain

## 🔥 Error
 Starting local Bazel server and connecting to it...
WARNING: ignoring _JAVA_OPTIONS in environment.
DEBUG: C:/users/e/_bazel_e/7x5kcfdx/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: C:/users/e/_bazel_e/7x5kcfdx/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:100:14: rbe_ubuntu_clang_gen not using checked in configs as user set attr to 'False'
DEBUG: C:/users/e/_bazel_e/7x5kcfdx/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: C:/users/e/_bazel_e/7x5kcfdx/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:100:14: rbe_ubuntu_gcc_gen not using checked in configs as user set attr to 'False'
DEBUG: C:/users/e/_bazel_e/7x5kcfdx/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: C:/users/e/_bazel_e/7x5kcfdx/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: rbe_ubuntu_clang not using checked in configs; Bazel version 4.2.0 was picked/selected but no checked in config was found in map {"5.0.0": ["clang"]}
WARNING: C:/users/e/prysm/beacon-chain/BUILD.bazel:3:14: target '//beacon-chain:beacon-chain' is deprecated: This target has moved to //cmd/beacon-chain:beacon-chain
INFO: Repository com_github_ethereum_go_ethereum instantiated at:
  C:/users/e/prysm/WORKSPACE:354:11: in <toplevel>
  C:/users/e/prysm/deps.bzl:858:18: in prysm_deps
  C:/users/e/prysm/tools/go/def.bzl:73:10: in go_repository
  C:/users/e/prysm/tools/go/def.bzl:61:18: in maybe
Repository rule go_repository defined at:
  C:/users/e/_bazel_e/7x5kcfdx/external/bazel_gazelle/internal/go_repository.bzl:214:32: in <toplevel>
DEBUG: C:/users/e/_bazel_e/7x5kcfdx/external/bazel_gazelle/internal/go_repository.bzl:209:18: com_github_ethereum_go_ethereum: gazelle: C:\Users\e\_bazel_e\7x5kcfdx\external\com_github_ethereum_go_ethereum\accounts\usbwallet\trezor: directory contains multiple proto packages. Gazelle can only generate a proto_library for one package.
ERROR: An error occurred during the fetch of repository 'com_github_ethereum_go_ethereum':
   Traceback (most recent call last):
        File "C:/users/e/_bazel_e/7x5kcfdx/external/bazel_gazelle/internal/go_repository.bzl", line 212, column 10, in _go_repository_impl
                patch(ctx)
        File "C:/users/e/_bazel_e/7x5kcfdx/external/bazel_gazelle/internal/go_repository.bzl", line 310, column 17, in patch
                fail("Error applying patch %s:\n%s%s" %
Error in fail: Error applying patch //third_party:com_github_ethereum_go_ethereum_secp256k1.patch:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("bash" -c "patch '-p1' < C:/users/e/prysm/third_party/com_github_ethereum_go_ethereum_secp256k1.patch"): The system cannot find the file specified.
 (error: 2)
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/users/e/_bazel_e/7x5kcfdx/external/bazel_gazelle/internal/go_repository.bzl", line 212, column 10, in _go_repository_impl
                patch(ctx)
        File "C:/users/e/_bazel_e/7x5kcfdx/external/bazel_gazelle/internal/go_repository.bzl", line 310, column 17, in patch
                fail("Error applying patch %s:\n%s%s" %
Error in fail: Error applying patch //third_party:com_github_ethereum_go_ethereum_secp256k1.patch:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("bash" -c "patch '-p1' < C:/users/e/prysm/third_party/com_github_ethereum_go_ethereum_secp256k1.patch"): The system cannot find the file specified.
 (error: 2)
ERROR: C:/users/e/prysm/cmd/beacon-chain/BUILD.bazel:8:11: //cmd/beacon-chain:go_default_library depends on @com_github_ethereum_go_ethereum//log:go_default_library in repository @com_github_ethereum_go_ethereum which failed to fetch. no such package '@com_github_ethereum_go_ethereum//log': Error applying patch //third_party:com_github_ethereum_go_ethereum_secp256k1.patch:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("bash" -c "patch '-p1' < C:/users/e/prysm/third_party/com_github_ethereum_go_ethereum_secp256k1.patch"): The system cannot find the file specified.
 (error: 2)
ERROR: Analysis of target '//beacon-chain:beacon-chain' failed; build aborted: no such package '@com_github_ethereum_go_ethereum//log': Error applying patch //third_party:com_github_ethereum_go_ethereum_secp256k1.patch:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("bash" -c "patch '-p1' < C:/users/e/prysm/third_party/com_github_ethereum_go_ethereum_secp256k1.patch"): The system cannot find the file specified.
 (error: 2)
INFO: Elapsed time: 4.625s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (108 packages loaded, 8164 targets configured)

## 🌍  Your Environment

**Operating System:**

Windows 11

**What version of Prysm are you running? (Which release)**

kiln-branch

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment] 2022-04-02 13:29
@galaxy4627 Try without the release flag. Also make sure you have the `patch` tool installed. 

This link may be helpful for installing `patch` on your machine: http://gnuwin32.sourceforge.net/packages/patch.htm 
I'm not a windows user so you may have to do some searching of your own.

**Comment by galaxy4627** [comment] 2022-04-02 13:52
> @galaxy4627 Try without the release flag. Also make sure you have the `patch` tool installed.
> 
> This link may be helpful for installing `patch` on your machine: http://gnuwin32.sourceforge.net/packages/patch.htm I'm not a windows user so you may have to do some searching of your own.
Issue still occurs `
C:\Users\e\prysm>refreshenv
Refreshing environment variables from registry for cmd.exe. Please wait...Finished..

C:\Users\e\prysm>bazel build  //cmd/beacon-chain:beacon-chain
DEBUG: C:/users/e/_bazel_e/7x5kcfdx/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: C:/users/e/_bazel_e/7x5kcfdx/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:100:14: rbe_ubuntu_clang_gen not using checked in configs as user set attr to 'False'
DEBUG: C:/users/e/_bazel_e/7x5kcfdx/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: C:/users/e/_bazel_e/7x5kcfdx/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:100:14: rbe_ubuntu_gcc_gen not using checked in configs as user set attr to 'False'
DEBUG: C:/users/e/_bazel_e/7x5kcfdx/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: C:/users/e/_bazel_e/7x5kcfdx/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: rbe_ubuntu_clang not using checked in configs; Bazel version 4.2.0 was picked/selected but no checked in config was found in map {"5.0.0": ["clang"]}
INFO: Repository com_github_ethereum_go_ethereum instantiated at:
  C:/users/e/prysm/WORKSPACE:354:11: in <toplevel>
  C:/users/e/prysm/deps.bzl:858:18: in prysm_deps
  C:/users/e/prysm/tools/go/def.bzl:73:10: in go_repository
  C:/users/e/prysm/tools/go/def.bzl:61:18: in maybe
Repository rule go_repository defined at:
  C:/users/e/_bazel_e/7x5kcfdx/external/bazel_gazelle/internal/go_repository.bzl:214:32: in <toplevel>
DEBUG: C:/users/e/_bazel_e/7x5kcfdx/external/bazel_gazelle/internal/go_repository.bzl:209:18: com_github_ethereum_go_ethereum: gazelle: C:\Users\e\_bazel_e\7x5kcfdx\external\com_github_ethereum_go_ethereum\accounts\usbwallet\trezor: directory contains multiple proto packages. Gazelle can only generate a proto_library for one package.
ERROR: An error occurred during the fetch of repository 'com_github_ethereum_go_ethereum':
   Traceback (most recent call last):
        File "C:/users/e/_bazel_e/7x5kcfdx/external/bazel_gazelle/internal/go_repository.bzl", line 212, column 10, in _go_repository_impl
                patch(ctx)
        File "C:/users/e/_bazel_e/7x5kcfdx/external/bazel_gazelle/internal/go_repository.bzl", line 310, column 17, in patch
                fail("Error applying patch %s:\n%s%s" %
Error in fail: Error applying patch //third_party:com_github_ethereum_go_ethereum_secp256k1.patch:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("bash" -c "patch '-p1' < C:/users/e/prysm/third_party/com_github_ethereum_go_ethereum_secp256k1.patch"): The system cannot find the file specified.
 (error: 2)
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/users/e/_bazel_e/7x5kcfdx/external/bazel_gazelle/internal/go_repository.bzl", line 212, column 10, in _go_repository_impl
                patch(ctx)
        File "C:/users/e/_bazel_e/7x5kcfdx/external/bazel_gazelle/internal/go_repository.bzl", line 310, column 17, in patch
                fail("Error applying patch %s:\n%s%s" %
Error in fail: Error applying patch //third_party:com_github_ethereum_go_ethereum_secp256k1.patch:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("bash" -c "patch '-p1' < C:/users/e/prysm/third_party/com_github_ethereum_go_ethereum_secp256k1.patch"): The system cannot find the file specified.
 (error: 2)
ERROR: C:/users/e/prysm/cmd/beacon-chain/BUILD.bazel:8:11: //cmd/beacon-chain:go_default_library depends on @com_github_ethereum_go_ethereum//log:go_default_library in repository @com_github_ethereum_go_ethereum which failed to fetch. no such package '@com_github_ethereum_go_ethereum//log': Error applying patch //third_party:com_github_ethereum_go_ethereum_secp256k1.patch:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("bash" -c "patch '-p1' < C:/users/e/prysm/third_party/com_github_ethereum_go_ethereum_secp256k1.patch"): The system cannot find the file specified.
 (error: 2)
ERROR: Analysis of target '//cmd/beacon-chain:beacon-chain' failed; build aborted: no such package '@com_github_ethereum_go_ethereum//log': Error applying patch //third_party:com_github_ethereum_go_ethereum_secp256k1.patch:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("bash" -c "patch '-p1' < C:/users/e/prysm/third_party/com_github_ethereum_go_ethereum_secp256k1.patch"): The system cannot find the file specified.
 (error: 2)
INFO: Elapsed time: 0.527s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)`

**Comment by galaxy4627** [comment] 2022-04-02 13:54
> @galaxy4627 Try without the release flag. Also make sure you have the `patch` tool installed.
> 
> This link may be helpful for installing `patch` on your machine: http://gnuwin32.sourceforge.net/packages/patch.htm I'm not a windows user so you may have to do some searching of your own.

issue still occurs, tried with bazel build  //cmd/beacon-chain:beacon-chain and I did install patch

**Comment by potuz** [comment] 2022-04-02 14:39
> CreateProcessW("bash" -c "patch '-p1' < C:/users/e/prysm/third_party/com_github_ethereum_go_ethereum_secp256k1.patch"): The system cannot find the file specified.

Is this right? It tries to run bash on windows? I thought we never supported compiling on windows and only cross compiled for it

**Comment by galaxy4627** [comment] 2022-04-02 16:42
> > CreateProcessW("bash" -c "patch '-p1' < C:/users/e/prysm/third_party/com_github_ethereum_go_ethereum_secp256k1.patch"): The system cannot find the file specified.
> 
> Is this right? It tries to run bash on windows? I thought we never supported compiling on windows and only cross compiled for it

so, is there nothing i can do to run a kiln prysm node on windows?

**Comment by nisdas** [comment] 2022-04-03 10:56
@galaxy4627 You can compile it via `go` instead of bazel if you just want to test kiln. We should be having a release soon through which you can run it directly via our binaries/image.

**Comment by galaxy4627** [comment] 2022-04-03 11:19
> @galaxy4627 You can compile it via `go` instead of bazel if you just want to test kiln. We should be having a release soon through which you can run it directly via our binaries/image.

how would i compile prysm via go?

**Comment by nisdas** [comment] 2022-04-04 00:08
> how would i compile prysm via go?

`go run ./cmd/beacon-chain/... --flag1 --flag2`

This is how it would work

**Comment by terencechain** [comment] 2022-04-18 08:02
`kiln` branch has been closed. All its functionality is merged into the `develop` branch. Please try that and feel free to reopen the issue is persists

**Closed by terencechain** 2022-04-18 08:02 UTC
