### ISSUE TITLE
Race Conditions in Tests 

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#572] opened 2018-09-26 12:21 UTC
The tests for the beacon-chain/types package are failing in travis but are unable to be reproduced locally.

Below is the output: 

```golang

time="2018-09-26T11:59:34Z" level=info msg="Constructing attestation message for incoming block 0x75fe617ec147c98a8798abe94ed422bcb8850328f83fc23243a4e359b34a6df3" prefix=types
time="2018-09-26T11:59:34Z" level=info msg="Verifying attestation with public key 0x0000000000000000000000000000000000000000000000000000000000000000" prefix=types
time="2018-09-26T11:59:34Z" level=info msg="successfully verified attestation with incoming block" prefix=types
time="2018-09-26T11:59:34Z" level=debug msg="Attestation message for shard: 0, slot 0, block hash [] is: [10 121 168 129 138 172 90 68 148 48 227 85 69 210 117 24 187 137 208 130 140 253 76 44 211 246 156 166 242 155 229 146]" prefix=types
time="2018-09-26T11:59:34Z" level=info msg="Proposer index: 1" prefix=types
time="2018-09-26T11:59:34Z" level=debug msg="Attestation message for shard: 0, slot 0, block hash [] is: [10 121 168 129 138 172 90 68 148 48 227 85 69 210 117 24 187 137 208 130 140 253 76 44 211 246 156 166 242 155 229 146]" prefix=types
time="2018-09-26T11:59:34Z" level=debug msg="attestation slot number can't be higher than parent block's slot number. Found: 2, Needed lower than: 1" prefix=types
time="2018-09-26T11:59:34Z" level=debug msg="attestation slot number can't be lower than parent block's slot number by one CycleLength. Found: 1, Needed greater than: 2" prefix=types
time="2018-09-26T11:59:35Z" level=debug msg="Applying rewards and penalties for the validators for slot 0" prefix=casper
time="2018-09-26T11:59:35Z" level=debug msg="Applying rewards and penalties for the validators for slot 1" prefix=casper
time="2018-09-26T11:59:35Z" level=debug msg="Applying rewards and penalties for the validators for slot 2" prefix=casper
time="2018-09-26T11:59:35Z" level=debug msg="Applying rewards and penalties for the validators for slot 3" prefix=casper
time="2018-09-26T11:59:35Z" level=debug msg="Applying rewards and penalties for the validators for slot 4" prefix=casper
time="2018-09-26T11:59:35Z" level=debug msg="Applying rewards and penalties for the validators for slot 5" prefix=casper
time="2018-09-26T11:59:35Z" level=debug msg="Applying rewards and penalties for the validators for slot 6" prefix=casper
time="2018-09-26T11:59:35Z" level=debug msg="Applying rewards and penalties for the validators for slot 7" prefix=casper
time="2018-09-26T11:59:35Z" level=debug msg="Applying rewards and penalties for the validators for slot 8" prefix=casper
```

**Comment by rawfalafel** [comment] 2018-10-05 09:36
This looks like a duplicate of #604

**Closed as completed by rawfalafel** 2018-10-05 09:36 UTC
