### ISSUE TITLE
Keystore keymanager no longer usable

### ISSUE THREAD

**Issue by Belkaar** [prysmaticlabs/prysm#6796] opened 2020-07-31 06:54 UTC
# 🐞 Bug Report

### Description

Since 1.0.0-alpha.17 usage of the old keystore is no longer possible.

### Has this worked before in a previous version?

Yes. Worked in 1.0.0-alpha.16 .

## 🔬 Minimal Reproduction

* Put an old key store directory form a 1.0.0-alpha.16 client in /tmp/test-keystore
* Run "prysm.sh validator --keymanager=keystore --keymanageropts='{"path":"/tmp/test-keystore","passphrase":"<passphrase>"}'"

## 🔥 Error

<pre><code>

Enter a wallet directory (default: /root/.eth2validators/prysm-wallet-v2):
test
[2020-07-31 08:43:51] FATAL node: Could not open wallet: no wallet found at path, please create a new wallet using `./prysm.sh validator wallet-v2 create`

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
    Debian 10
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
    1.0.0-alpha.17
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
N/A

**Comment by Belkaar** [comment] 2020-07-31 07:00
Probably related to #6795

**Comment by Belkaar** [comment] 2020-07-31 08:22
Workaround: add --disable-accounts-v2

**Comment by prestonvanloon** [comment] 2020-07-31 20:11
Duplicate of #6795. Sorry about the issue! We'll consider adding some better language in this failure to avoid completely breaking existing keystores.

**Closed by prestonvanloon** 2020-07-31 20:11 UTC
Labels: AccountsV2
