### ISSUE TITLE
ActiveValidatorIndices helper function returns wrong indices

### ISSUE THREAD

**Issue by ppratscher** [prysmaticlabs/prysm#4259] opened 2019-12-11 13:35 UTC
The ActiveValidatorIndices function is supposed to return the indices of the currently active validators.
But when appending to the indices array it appends the index of the validator in the array returned by `activeIndicesCache.ActiveIndicesInEpoch(epoch)` and not the actual index of the validator.

See:
https://github.com/prysmaticlabs/prysm/blob/0326be86b5781b8e9d40d8f003d28a895e71203f/beacon-chain/core/helpers/validators.go#L82-L86

That is why a validator with an index greater than the number of active validators will never get any slot proposal or attestation assignments.

Unfortunately the type `v1alpha1.Validator` that is returned by `activeIndicesCache.ActiveIndicesInEpoch(epoch)` also does not contain the validator index.

**Comment by handelaar2** [comment] 2019-12-11 15:18
validator log as requested by terence

[validator.log](https://github.com/prysmaticlabs/prysm/files/3951056/validator.log)

**Comment by metanull-operator** [comment] 2019-12-11 15:23
[validator.log](https://github.com/prysmaticlabs/prysm/files/3951083/validator.log)

**Comment by terencechain** [comment] 2019-12-11 15:31
Looking at this today

**Comment by prestonvanloon** [comment] 2019-12-11 19:29
Could this be why we experience behavior where we don't see any proposers with an index higher than ~500? Those validators are still selected to attest, but never propose.

**Comment by prestonvanloon** [comment] 2019-12-11 19:30
Bumping priority because I think this is a P0 bug if the above is true.

**Comment by prestonvanloon** [comment] 2019-12-11 19:34
Looking into a regression test for this

**Comment by prestonvanloon** [comment] 2019-12-11 19:35
There is no unit test for helpers.ActiveValidatorIndices. Working on a fix now. 
I am not sure how this is going to affect syncing the existing chain, it might be invalid and require a restart.

**Comment by prestonvanloon** [comment] 2019-12-11 19:48
Confirmed with regression test for `ActiveValidatorIndices`. This is a bug, I'll try to sync a client with the fix and see if it's runtime breaking.

**Comment by prestonvanloon** [comment] 2019-12-11 19:53
Spoke too soon. I cannot confirm this as a bug, even with tests. The `i` value is the validator's index

**Comment by terencechain** [comment] 2019-12-11 19:56
Right I wasn't sure if this was bug, given cache returns empty list if miss and we would have experienced it earlier. Lack of test coverage forsure and we should delete the old cache

**Comment by terencechain** [comment] 2019-12-11 19:57
Have a regression test with existing DB set up, will run it through to get a better picture

**Comment by ppratscher** [comment] 2019-12-11 19:58
But `state.Validators` is an array and not a map hence `i` will always be the array index. I think it might only return the correct validator indices if it returns all validators (active & inactive ones)?

**Comment by prestonvanloon** [comment] 2019-12-11 19:58
This cache doesn't support fork conditions though. When adding feature flag for EnableActiveIndicesCache, this fails with different state Validators. Maybe we need epoch + finalized checkpoint to be confident about a cache hit?

It should be noted that most clients aren't running with this cache on so it would miss 100% of the time, unless they are using experimental caching flags, but even then this seems OK.

**Comment by terencechain** [comment] 2019-12-11 20:00
That cache is old and we were suppose to delete a long time ago. It's not supposed to be used. See #3631

**Comment by terencechain** [comment] 2019-12-11 20:01
There's only one cache for run time and that's the shuffled committee cache

**Comment by prestonvanloon** [comment] 2019-12-11 20:04
Added test here: https://github.com/prysmaticlabs/prysm/pull/4263

I think this is a non-issue. state.Validators returns all validators that ever existed in the system, including active and inactive validators. I am concerned about these caches under forking conditions and finality reversion scenarios, but we'll need to revisit that in a different issue.

**Comment by prestonvanloon** [comment] 2019-12-11 20:13
I'll submit fix to delete old active index cache. If it's not used then should be safe to delete and avoid confusion.

**Comment by terencechain** [comment] 2019-12-11 20:17
Sounds good. Check if it's not done in #3631. Don't wanna duplicate work :)

**Comment by prestonvanloon** [comment] 2019-12-11 20:18
It's probably done in that PR but it looks rotten and does more than delete active index cache, also deletes shuffled indexes.

**Comment by prestonvanloon** [comment] 2019-12-11 20:30
Removing this unused cache entirely in #4264. @ppratscher do you think this is resolved?

**Comment by terencechain** [comment] 2019-12-11 20:34
I am not sure if it solved it. The bug ultimately lies in archival service retrieving proposer and attesters in old epochs. That's what I'm seeing with my tests. With that said, this is a good fix

**Comment by ppratscher** [comment] 2019-12-11 20:53
I think the bug might be in the `ComputeProposerIndex` function.

From what I understand it should return `indices[candidateIndex]` and not just candidateIndex as the return value of `ComputeShuffledIndex` in this case cannot be greater than len(indices). That will also explain why only validators with an index < len(activeIndices) receive a block proposal assignment.

**Comment by prestonvanloon** [comment] 2019-12-11 21:15
Bumping priority based on https://github.com/prysmaticlabs/prysm/issues/4259#issuecomment-564727994. This is another helper with no unit test, I'll try to write a regression test for this scenario.

**Comment by terencechain** [comment] 2019-12-11 21:44
Working on this now

**Comment by prestonvanloon** [comment] 2019-12-11 21:53
This will be resolved in #4265. Waiting to see if this is consensus breaking on current testnet or not. 

If it is, we'll likely merge it into 0.9.2 branch and try to expedite the testnet restart.

**Comment by prestonvanloon** [comment] 2019-12-12 22:44
Confirmed this is consensus breaking and will require a testnet restart. I am out of office until Sunday night, I'll pick this up as my top priority as soon as I can get back online.

**Comment by terencechain** [comment] 2019-12-12 22:47
@prestonvanloon what are the required actions from this? can delegate

**Comment by prestonvanloon** [comment] 2019-12-12 22:52
Thanks @terencechain. Need to get a green PR on #4265. 

Following that, we need to focus on 0.9.2 features (#4154) such that we can start testing this at runtime.

**Comment by terencechain** [comment] 2019-12-12 22:53
Roger that. On the same page with you. Focusing on 0.9.2 features this week

**Comment by rauljordan** [comment] 2019-12-26 17:31
Resolved by #4265

**Closed by rauljordan** 2019-12-26 17:31 UTC
Labels: Bug, Priority: Critical
