### ISSUE TITLE
panic: invalid IP (length 0)

### ISSUE THREAD

**Issue by dv8silencer** [prysmaticlabs/prysm#6255] opened 2020-06-14 19:14 UTC
# 🐞 Bug Report

Beacon node crashes after a 
```console
panic: invalid IP(length 0)
```
I am on the Onyx testnet and the node was running for 5-10 hours prior to crashing.

### Has this worked before in a previous version?

I have only used the recent versions of the beacon-chain.  I have not had this problem before.

## 🔬 Minimal Reproduction

./prysm.sh beacon-chain --p2p-max-peers 999 --p2p-host-ip=$(curl -s v4.ident.me)

## 🔥 Error
<pre><code>
panic: invalid IP (length 0)

goroutine 67502238 [running]:
github.com/ethereum/go-ethereum/p2p/enode.nodeItemKey(0xaf27410898fd780c, 0x4235916104e8634a, 0xf6483e06ae73d196, 0x7011b7d9abe78b44, 0x0, 0x0, 0x0, 0x185f2e8, 0x8, 0xc026693980, ...)
    external/com_github_ethereum_go_ethereum/p2p/enode/nodedb.go:152 +0x491
github.com/ethereum/go-ethereum/p2p/enode.(*DB).FindFails(0xc00000f300, 0xaf27410898fd780c, 0x4235916104e8634a, 0xf6483e06ae73d196, 0x7011b7d9abe78b44, 0x0, 0x0, 0x0, 0x10000000164fbc0)
    external/com_github_ethereum_go_ethereum/p2p/enode/nodedb.go:384 +0x78
github.com/ethereum/go-ethereum/p2p/discover.(*lookup).query(0xc0076c4a20, 0xc01dc34fc0, 0xc028bed9e0)
    external/com_github_ethereum_go_ethereum/p2p/discover/lookup.go:144 +0xc3
created by github.com/ethereum/go-ethereum/p2p/discover.(*lookup).startQueries
    external/com_github_ethereum_go_ethereum/p2p/discover/lookup.go:127 +0x1be
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

Linux myVMWARE 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Prysm/v1.0.0-alpha.11/87ca73d60512ef488fe9551237bc9601c0f34809. Built at: 2020-06-12 19:11:43+00:00
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment] 2020-06-14 22:33
@nisdas what do you think about this? Looks like discv5 bug

**Comment by herweyer** [comment] 2020-06-26 19:19
commenting to re-open this ticket with a new occurrence of this issue:

### Description

Beacon node crashes with error
<pre><code>panic: invalid IP (length 0)
</code></pre>

### Has this worked before in a previous version?

I'm not certain if this error has occurred in a previous version.  This node has crashed three times since the alpha-12 release, but this is the first time I've looked at the logs to investigate.  The node had been running for ~2 days since the last crash.

## 🔬 Minimal Reproduction

.\prysm.bat beacon-chain --http-web3provider=http://localhost:8545/ --p2p-host-ip=$(curl -s v4.ident.me)

## 🔥 Error

<pre><code>
panic: invalid IP (length 0)

goroutine 27642262 [running]:
github.com/ethereum/go-ethereum/p2p/enode.nodeItemKey(0x64c8f2bbeddefa3a, 0xce782ac5907f58f9, 0xab017ce07bb33af, 0x49ba79183df31fc1, 0x0, 0x0, 0x0, 0x19ea07b, 0x8, 0xc02ac856e0, ...)
        external/com_github_ethereum_go_ethereum/p2p/enode/nodedb.go:152 +0x498
github.com/ethereum/go-ethereum/p2p/enode.(*DB).FindFails(0xc004ca22e0, 0x64c8f2bbeddefa3a, 0xce782ac5907f58f9, 0xab017ce07bb33af, 0x49ba79183df31fc1, 0x0, 0x0, 0x0, 0xc00072ea80)
        external/com_github_ethereum_go_ethereum/p2p/enode/nodedb.go:384 +0x7f
github.com/ethereum/go-ethereum/p2p/discover.(*lookup).query(0xc01edd0cf0, 0xc021e122d0, 0xc039732660)
        external/com_github_ethereum_go_ethereum/p2p/discover/lookup.go:144 +0xca
created by github.com/ethereum/go-ethereum/p2p/discover.(*lookup).startQueries
        external/com_github_ethereum_go_ethereum/p2p/discover/lookup.go:127 +0x1c5
ERROR FAILED

</code></pre>


## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 10 Pro Version 2004 (19041.329)
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.0-alpha.12
  </code>
</pre>

**Comment by prestonvanloon** [comment] 2020-06-26 19:34
@nisdas looks like this is still happening in alpha.12. Could you take a look please?

**Comment by rauljordan** [comment] 2020-07-22 14:48
Bump @nisdas

**Comment by rauljordan** [comment] 2020-08-06 16:47
Bump @nisdas

**Comment by nisdas** [comment] 2020-08-06 16:48
Resolved with #6261 .

**Closed by nisdas** 2020-08-06 16:48 UTC
Labels: Bug
