### ISSUE TITLE
INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0

### ISSUE THREAD

**Issue by zq19** [prysmaticlabs/prysm#6779] opened 2020-07-30 02:42 UTC
After i run the below code：./prysm.sh beacon-chain --datadir=$HOME/.eth2

it happening：
INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0
INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0
INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0
.......

**Comment by rauljordan** [comment] 2020-08-06 16:54
Duplicate of  #6746, please follow that issue for updates

**Closed by rauljordan** 2020-08-06 16:54 UTC
