### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by ligi** [prysmaticlabs/prysm#2602] opened 2019-05-14 17:12 UTC
```
[2019-05-14 17:10:47]  INFO blockchain: Slot transition successfully processed slotsSinceGenesis=214295
panic: runtime error: index out of range

goroutine 1595 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*ChainService).saveValidatorIdx(0xc0001783c0, 0xc0003d7600, 0xc0021da9a0, 0x1)
        beacon-chain/blockchain/block_processing.go:323 +0x220
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*ChainService).runStateTransition(0xc0001783c0, 0x16187a0, 0xc00287dda0, 0x82707e4079844aa8, 0x51aadbc235acfc9d, 0xd64100c5647ed7c3, 0x35e24f36496e361, 0x0, 0xc0003d7600, 0xc0003d7600, ...)
        beacon-chain/blockchain/block_processing.go:299 +0x341
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*ChainService).ApplyBlockStateTransition(0xc0001783c0, 0x16187a0, 0xc00287dda0, 0xc00123c460, 0xc0003d7600, 0x0, 0x0, 0x16187a0)
        beacon-chain/blockchain/block_processing.go:169 +0x1dc
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).validateAndSaveNextBlock(0xc000518140, 0x16187a0, 0xc00287dda0, 0xc00123c460, 0x0, 0x0)
        beacon-chain/sync/initial-sync/sync_blocks.go:135 +0x9ac
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).processBlock(0xc000518140, 0x16187a0, 0xc00287dd70, 0xc00123c460, 0xc0016b3830, 0x0, 0x0)
        beacon-chain/sync/initial-sync/sync_blocks.go:35 +0x211
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).processBatchedBlocks(0xc000518140, 0x16187a0, 0xc00287dc20, 0xc0015165a0, 0x22, 0x1610d60, 0xc00123a880, 0xc0016b3830, 0x0, 0x0)
        beacon-chain/sync/initial-sync/sync_blocks.go:63 +0x361
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).syncToPeer(0xc000518140, 0x1618760, 0xc0016e7da0, 0xc0016b3830, 0xc002993c50, 0x22, 0x0, 0x0)
        beacon-chain/sync/initial-sync/service.go:291 +0x6c7
```

**Comment by prestonvanloon** [comment] 2019-05-24 16:21
I think this was caused by syncing some fork. Going to close this while we focus on relaunching with spec 0.6.1+ and hope that this issue is resolved in the new launch.

Thanks for reporting! :)

**Closed by prestonvanloon** 2019-05-24 16:21 UTC
