### ISSUE TITLE
Panic when serving `GetBlockV2`

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#12856] opened 2023-09-06 15:28 UTC
Commit: https://github.com/prysmaticlabs/prysm/commit/48a391484271d67ed4a5a8dd0b0994846d8186c3

```
time="2023-09-06 15:24:24" level=error msg="gRPC panicked!" error="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 115831 [running]:
runtime/debug.Stack()
	GOROOT/src/runtime/debug/stack.go:24 +0x65
github.com/prysmaticlabs/prysm/v4/monitoring/tracing.RecoveryHandlerFunc({0xe0e8b8?, 0xc0028c5770?}, {0x4430e0?, 0x366eb20})
	monitoring/tracing/recovery_interceptor_option.go:29 +0x1f7
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom({0xe0e8b8?, 0xc0028c5770?}, {0x4430e0?, 0x366eb20?}, 0xc003ebcbc0?)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:61 +0x36
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1()
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:29 +0x7b
panic({0x4430e0, 0x366eb20})
	GOROOT/src/runtime/panic.go:884 +0x213
github.com/prysmaticlabs/prysm/v4/proto/engine/v1.(*ExecutionBlock).UnmarshalJSON(0xc015f2f340, {0xc0014c8700, 0x697, 0x700})
	proto/engine/v1/json_marshal_unmarshal.go:117 +0x6d9
encoding/json.(*decodeState).object(0xc00943abd0, {0x59cd00?, 0xc015f2f340?, 0xc003ebd0d0?})
	GOROOT/src/encoding/json/decode.go:613 +0x6ef
encoding/json.(*decodeState).value(0xc00943abd0, {0x59cd00?, 0xc015f2f340?, 0x7f2c88e1e5b8?})
	GOROOT/src/encoding/json/decode.go:374 +0x45
encoding/json.(*decodeState).unmarshal(0xc00943abd0, {0x59cd00?, 0xc015f2f340?})
	GOROOT/src/encoding/json/decode.go:181 +0x168
encoding/json.Unmarshal({0xc0014c8700, 0x697, 0x700}, {0x59cd00, 0xc015f2f340})
	GOROOT/src/encoding/json/decode.go:108 +0x125
github.com/ethereum/go-ethereum/rpc.(*Client).CallContext(0xc002ab4510, {0xe0e8b8, 0xc0028c5a70}, {0x59cd00, 0xc015f2f340}, {0x878db5?, 0x12?}, {0xc000759060, 0x2, 0x2})
	external/com_github_ethereum_go_ethereum/rpc/client.go:374 +0x285
github.com/prysmaticlabs/prysm/v4/beacon-chain/execution.(*Service).ExecutionBlockByHash(0xc00321c0d0, {0xe0e8b8?, 0xc0028c58c0?}, {0x5c, 0x8, 0x6f, 0x25, 0x82, 0x4c, 0x80, ...}, ...)
	beacon-chain/execution/engine_client.go:479 +0x1d0
github.com/prysmaticlabs/prysm/v4/beacon-chain/execution.(*Service).retrievePayloadFromExecutionHash(0x1db5b01?, {0xe0e8b8, 0xc0028c58c0}, {0x5c, 0x8, 0x6f, 0x25, 0x82, 0x4c, 0x80, ...}, ...)
	beacon-chain/execution/engine_client.go:687 +0x21d
github.com/prysmaticlabs/prysm/v4/beacon-chain/execution.(*Service).ReconstructFullBlock(0xdf5640?, {0xe0e8b8, 0xc0028c58c0}, {0xe2af50, 0xc000756bd0})
	beacon-chain/execution/engine_client.go:605 +0x34c
github.com/prysmaticlabs/prysm/v4/beacon-chain/rpc/eth/beacon.(*Server).getBlockDeneb(0xc0031fc300, {0xe0e8b8, 0xc0028c58c0}, {0xe2af50?, 0xc000756bd0})
	beacon-chain/rpc/eth/beacon/blocks.go:822 +0x3d7
github.com/prysmaticlabs/prysm/v4/beacon-chain/rpc/eth/beacon.(*Server).GetBlockV2(0xc0031fc300, {0xe0e8b8?, 0xc0028c5890?}, 0xc0026f00c0)
	beacon-chain/rpc/eth/beacon/blocks.go:505 +0x769
```

**Comment by kasey** [comment] 2023-09-07 13:01
duplicate of #12830

**Closed by kasey** 2023-09-07 13:01 UTC
Labels: Bug, Deneb
