### ISSUE TITLE
`--cache-proposer-indices` causes OOM for long chains at beacon startup

### ISSUE THREAD

**Issue by garyschulteog** [prysmaticlabs/prysm#4727] opened 2020-02-03 16:28 UTC
With a beaconchain sync'd up to about 166k slots, enabling `--cache-proposer-indices` will quickly run my node out of memory (4gb).  Running without the proposer cache, the memory requirement is stable at ~2.7gb.  On another machine without as tight a memory constraint, it appears the proposer cache gets pruned (during? after?) the initial sync and resident mem usage is <3gb.

> [2020-02-03 16:10:01]  WARN flags: Enabled unsafe ssz cache
[2020-02-03 16:10:01]  WARN flags: Enabled proposer index caching.
[2020-02-03 16:10:01]  WARN flags: Enabled using proto array fork choice over spec fork choice.
[2020-02-03 16:10:01]  INFO node: Using custom chain parameters config=demo
[2020-02-03 16:10:12]  INFO node: Checking DB database-path=/home/ubuntu/.eth2/beaconchaindata
[2020-02-03 16:10:12]  INFO node: Fetching testnet cluster address endpoint=https://prylabs.net/contract
[2020-02-03 16:10:13]  INFO node: Starting beacon node version=Prysm/Git commit: 00a6361c66da467ae6d91fd35905e8f9968931ae. Built at: 2020-02-03T16:10:01Z
...
[2020-02-03 16:13:35]  INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=2
[2020-02-03 16:13:40]  INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=2
fatal error: runtime: out of memory
.
runtime stack:
runtime.throw(0x14f67af, 0x16)
        GOROOT/src/runtime/panic.go:774 +0x54
runtime.sysMap(0x40b4000000, 0x4000000, 0x24d6098)
        GOROOT/src/runtime/mem_linux.go:169 +0xbc
runtime.(*mheap).sysAlloc(0x24a1b80, 0xbc0000, 0x249b010, 0x100000002)
        GOROOT/src/runtime/malloc.go:701 +0x168
runtime.(*mheap).grow(0x24a1b80, 0x5e0, 0xffffffff)
        GOROOT/src/runtime/mheap.go:1255 +0x9c
runtime.(*mheap).allocSpanLocked(0x24a1b80, 0x5e0, 0x24d60a8, 0x7f945a06d0)
        GOROOT/src/runtime/mheap.go:1170 +0x230
runtime.(*mheap).alloc_m(0x24a1b80, 0x5e0, 0x101, 0x7f94097778)
        GOROOT/src/runtime/mheap.go:1022 +0xc0
runtime.(*mheap).alloc.func1()
        GOROOT/src/runtime/mheap.go:1093 +0x48
runtime.(*mheap).alloc(0x24a1b80, 0x5e0, 0x7259010101, 0x401a983200)
        GOROOT/src/runtime/mheap.go:1092 +0x6c
runtime.largeAlloc(0xbc0000, 0x7f94090101, 0x1)
        GOROOT/src/runtime/malloc.go:1138 +0x8c
runtime.mallocgc.func1()
        GOROOT/src/runtime/malloc.go:1033 +0x44
runtime.systemstack(0x7259077930)
        GOROOT/src/runtime/asm_arm64.s:237 +0xa0
runtime.mstart()
        GOROOT/src/runtime/proc.go:1146

**Comment by nisdas** [comment] 2020-02-03 16:43
The offending code is here 
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/helpers/committee.go#L458 .

Getting all the proposers for the epoch leads to a runtime complexity of O(m *n ^2) . This is because we are still using the inefficient shuffling method here:
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/helpers/shuffle.go#L67

when we should be using the optimised algorithm here:
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/helpers/shuffle.go#L152

With 35,000 validators it can lead to frequent OOMs, the solution for this would be to just compute the assignments for the epoch once using the optimized algorithm, and determine the proposers from that set.

**Comment by terencechain** [comment] 2020-02-03 16:50
Are you suggesting `precomputeProposerIndices` to use the optimized algorithm in L152?

**Comment by nisdas** [comment] 2020-02-03 16:57
@terencechain yeap that is correct, that should resolve this issue

**Comment by terencechain** [comment] 2020-02-03 17:03
Great. Thanks!

**Comment by nisdas** [comment] 2020-02-04 12:13
Looking at this again, I am not sure why `preComputeIndices` leads to an OOM. We do this for every epoch and have not had an OOM till slot 166,000 in the above case. While it may be inefficient in its current iteration, I do not see how there are OOMs from it. I cant reproduce the above situation. @garyschulteog Is it consistently reproducible for you ?

**Comment by rauljordan** [comment] 2020-02-04 17:20
Struggling to reproduce as well - do you get the same results without the flag @garyschulteog ?

**Comment by nisdas** [comment] 2020-02-10 14:49
I dont think this should be an issue anymore, can you confirm it is resolved now ? @garyschulteog 
For this, I think I have an idea for the OOM, at slot 166,000 we had a long period without finality. So running with ```initial-sync-cache-state``` can easily lead to your node storing 1000 states in memory which would have led your node seeing that OOM. This is being tracked in #4813

**Comment by rauljordan** [comment] 2020-02-10 17:30
Closing in favor of #4813

**Closed by rauljordan** 2020-02-10 17:30 UTC
