### ISSUE TITLE
docs for mitigating insecure gRPC

### ISSUE THREAD

**Issue by ethers** [prysmaticlabs/prysm#4124] opened 2019-11-26 23:25 UTC
[2019-11-26 23:24:45]  WARN rpc: You are using an insecure gRPC connection! Provide a certificate and key to connect securely

**Comment by prestonvanloon** [comment] 2019-11-28 04:38
Relevant: https://grpc.io/docs/guides/auth/

**Comment by rauljordan** [comment] 2019-12-16 16:53
This is a duplicate of #791, also see attached link above ^

**Closed by rauljordan** 2019-12-16 16:53 UTC
Labels: Enhancement
