### ISSUE TITLE
Feature request: Ability to use different --graffiti="" for each validator

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#5586] opened 2020-04-23 09:15 UTC

**Comment by Buttaa** [comment] 2020-04-24 07:07
pretty much a duplicate of https://github.com/prysmaticlabs/prysm/issues/5597

**Comment by shayzluf** [comment] 2020-04-27 19:53
Duplicate of #5597

**Closed by shayzluf** 2020-04-27 19:53 UTC
Labels: Needs Design
