### ISSUE TITLE
Nodes Without Attached Validator Clients Missing Key Metrics

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#5868] opened 2020-05-15 16:38 UTC
# 🐞 Bug Report

### Description

Brought up in our discord, it has been observed nodes without attached validator clients via RPC are missing several key metrics they should be able to report, namely, values such as `beacon_clock_time_slot` or `beacon_head_slot`.

## 🔥 Error

https://pastebin.com/7JfnSBcy -> node with attached validator client
https://pastebin.com/0A4YAAVQ -> node **without** attached validator client

The second node is missing the `beacon_clock_time_slot` prom metric despite that metric being updated in the typical block processing path of a beacon node.

**Comment by terencechain** [comment] 2020-05-15 21:25
Looking into this now!

**Comment by terencechain** [comment] 2020-05-15 21:31
Both nodes have `beacon_head_slot ` but the second log misses `beacon_clock_time_slot`

**Comment by terencechain** [comment] 2020-05-15 22:10
This works for me every time. Please keep in mind that `clock_time` metric only shows up after a node has successfully processed a block. The `clock_time` metric won't show up if the node is stuck peering. 

![Screen Shot 2020-05-15 at 3 10 02 PM](https://user-images.githubusercontent.com/21316537/82100308-35df4a00-96be-11ea-8e8a-89f285c05148.png)

Will close this in a day if no one else has comments

**Comment by mbrivio** [comment] 2020-05-18 14:00
I initially reported the issue, then deployed another node on a new vm and couldn't reproduce the same behavior. I guess there was something funky about that particular node. For reference it was a db started time ago with a shell script installation, than switched to building with bazel keeping the same db.

**Closed** 2020-05-18 21:25 UTC
Labels: Bug, Priority: Medium
