### ISSUE TITLE
Sudden increase in RAM usage

### ISSUE THREAD

**Issue by raphpa** [prysmaticlabs/prysm#6338] opened 2020-06-22 07:10 UTC
# 💎 Issue

Not a bug, but maybe something to keep an eye on.

### Description

Sudden increase in RAM usage of beacon-chain on two independent systems for about 800MB on one, 500MB on the other system. This happened at June 21st at around 1700h UTC. It is staying at this level.

![image](https://user-images.githubusercontent.com/18283997/85258216-5f328900-b467-11ea-8ffb-4910e451defd.png)

![image](https://user-images.githubusercontent.com/18283997/85258279-7f624800-b467-11ea-837a-fa7147daec32.png)

This corresponds to epoch 1704 starting and also an increase in the pending validator queue for about 1000 new validators.

![image](https://user-images.githubusercontent.com/18283997/85258463-d49e5980-b467-11ea-8ffa-2ae97b5ead1a.png)

**Comment by shayzluf** [comment] 2020-06-24 12:05
@terencechain please reassign it to me if the assignment seems inappropriate

**Comment by prestonvanloon** [comment] 2020-06-26 20:11
Maybe related: #6104

**Comment by prestonvanloon** [comment] 2020-06-26 20:11
@nisdas do you think this is a duplicate of #6104?

**Comment by rauljordan** [comment] 2020-08-06 16:44
Really difficult to understand this one and take action. The best we can do is suspect #6104. Closing

**Closed by rauljordan** 2020-08-06 16:44 UTC
Labels: Bug
