### ISSUE TITLE
Beacon client repeatedly processing slots during init sync

### ISSUE THREAD

**Issue by torfbolt** [prysmaticlabs/prysm#4969] opened 2020-02-29 22:19 UTC
The latest beacon client (af5cc31565629f3e766b11caf7d8a7560d6c8901) processes each block lots of times before moving on to the next one during init sync:

```
[2020-02-29 22:10:36]  INFO initial-sync: Processing block 362641/366652 - estimated time remaining 8m21s blocksPerSecond=8.0 peers=13/17
[2020-02-29 22:10:36]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m18s blocksPerSecond=8.1 peers=13/17
[2020-02-29 22:10:36]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m15s blocksPerSecond=8.1 peers=13/17
[2020-02-29 22:10:36]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m34s blocksPerSecond=7.8 peers=13/17
[2020-02-29 22:10:36]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m31s blocksPerSecond=7.8 peers=13/17
[2020-02-29 22:10:36]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m27s blocksPerSecond=7.9 peers=13/17
[2020-02-29 22:10:36]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m24s blocksPerSecond=8.0 peers=13/17
[2020-02-29 22:10:36]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m21s blocksPerSecond=8.0 peers=13/17
[2020-02-29 22:10:36]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m18s blocksPerSecond=8.1 peers=13/17
[2020-02-29 22:10:37]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m15s blocksPerSecond=8.1 peers=13/17
[2020-02-29 22:10:37]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m12s blocksPerSecond=8.2 peers=13/17
[2020-02-29 22:10:37]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m34s blocksPerSecond=7.8 peers=13/17
[2020-02-29 22:10:37]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m31s blocksPerSecond=7.8 peers=13/17
[2020-02-29 22:10:37]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m27s blocksPerSecond=7.9 peers=13/17
[2020-02-29 22:10:37]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m24s blocksPerSecond=8.0 peers=13/17
[2020-02-29 22:10:37]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m21s blocksPerSecond=8.0 peers=13/17
[2020-02-29 22:10:37]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m18s blocksPerSecond=8.1 peers=13/17
[2020-02-29 22:10:38]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m15s blocksPerSecond=8.1 peers=13/17
[2020-02-29 22:10:38]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m12s blocksPerSecond=8.2 peers=13/17
[2020-02-29 22:10:38]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m31s blocksPerSecond=7.8 peers=13/17
[2020-02-29 22:10:38]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m27s blocksPerSecond=7.9 peers=13/17
[2020-02-29 22:10:38]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m24s blocksPerSecond=8.0 peers=13/17
[2020-02-29 22:10:38]  INFO initial-sync: Processing block 362641/366653 - estimated time remaining 8m21s blocksPerSecond=8.0 peers=13/17
[2020-02-29 22:10:38]  INFO initial-sync: Processing block 362642/366653 - estimated time remaining 8m18s blocksPerSecond=8.1 peers=13/17
[2020-02-29 22:10:39]  INFO initial-sync: Processing block 362642/366653 - estimated time remaining 8m40s blocksPerSecond=7.7 peers=13/17
[2020-02-29 22:10:39]  INFO initial-sync: Processing block 362642/366653 - estimated time remaining 8m37s blocksPerSecond=7.8 peers=13/17
[2020-02-29 22:10:39]  INFO initial-sync: Processing block 362642/366653 - estimated time remaining 8m34s blocksPerSecond=7.8 peers=13/17
[2020-02-29 22:10:39]  INFO initial-sync: Processing block 362642/366653 - estimated time remaining 8m30s blocksPerSecond=7.8 peers=13/17
[2020-02-29 22:10:40]  INFO initial-sync: Processing block 362642/366653 - estimated time remaining 8m27s blocksPerSecond=7.9 peers=13/17
[2020-02-29 22:10:40]  INFO initial-sync: Processing block 362642/366653 - estimated time remaining 8m24s blocksPerSecond=8.0 peers=13/17
[2020-02-29 22:10:40]  INFO initial-sync: Processing block 362642/366653 - estimated time remaining 8m51s blocksPerSecond=7.5 peers=13/17
[2020-02-29 22:10:40]  INFO initial-sync: Processing block 362642/366653 - estimated time remaining 8m47s blocksPerSecond=7.6 peers=13/17
```

This is unexpected and looks like a regression to me, earlier versions did not do this.

Edit: After restarting the client it continued syncing with the normal 1 log message per slot.

**Comment by prestonvanloon** [comment] 2020-03-06 06:34
@farazdagi could you please take a look. Is this related to your recent changes?

**Comment by farazdagi** [comment] 2020-03-06 09:57
@torfbolt can you please provide more information about flags you are using (so that we know that the issue is not a duplicate of #4964)

**Comment by torfbolt** [comment] 2020-03-06 10:02
The command I used was
`docker run -m 8G -it -v ~/.prysm/:/data -p 4000:4000 -p 13000:13000 gcr.io/prysmaticlabs/prysm/beacon-chain:latest --datadir=/data`

So no flags, default settings for that build.

**Comment by farazdagi** [comment] 2020-03-17 10:39
Yes, this should be resolved by the refactored init-sync (currently toggled with `--enable-initial-sync-queue` flag). 

While it can happen that all peers return invalid block, and we get stuck (for a moment), the general queueing of requests is more sophisticated, and system will re-try fetching with different parameters (bigger batch size, reset start slot), so should not remain stuck for too long, and should be able to proceed w/o requiring manual node restart.

**Closed** 2020-03-17 17:27 UTC
Labels: Bug, Networking
