### ISSUE TITLE
Sync stuck at head_slot 4700031

### ISSUE THREAD

**Issue by nitikas99** [prysmaticlabs/prysm#11474] opened 2022-09-20 07:38 UTC
[2022-09-20 04:41:21]  WARN initial-sync: Skip processing batched blocks error=beacon node doesn't have a parent in db with root: xxxxxxxxxxxxxxxxxxxxxxxxxx (in processBatchedBlocks, slot=4700351)

**Comment by prestonvanloon** [comment] 2022-09-20 14:04
Duplicate of #11471

**Closed by prestonvanloon** 2022-09-20 14:04 UTC
