### ISSUE TITLE
Validator crash SIGSEGV after clock offset warning

### ISSUE THREAD

**Issue by timjp87** [prysmaticlabs/prysm#6887] opened 2020-08-05 09:24 UTC
# 🐞 Bug Report

### Description

I updated my client to alpha18 as soon as it was released. After this i left it unattended on my machine which does not run any other service (other than the beaconchain). This morning I imported more validators and attached to my validator tmux session to restart it and saw that it has crashed yesterday evening. There was a clock offset warning. I check "timedatectl".

I checked timedatectl:
alarm@atlas01 ~ % sudo timedatectl
[sudo] password for alarm:
               Local time: Wed 2020-08-05 09:13:12 UTC
           Universal time: Wed 2020-08-05 09:13:12 UTC
                 RTC time: Sun 2020-08-09 09:12:58
                Time zone: UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

And NTP seems to be active. However, when I tried to check "systemctl status ntpd" it did not find this service. So I installed the ntp package and started and enabled this service after this.

I'm not sure if the SIGSEGV crash is directly related to this warning though. Stack Trace is included in the log.

### Has this worked before in a previous version?

First time encountering this problem.

## 🔬 Minimal Reproduction

I have restarted the validator and so far it seems to run, but it also ran for hours before the crash.

## 🔥 Error

https://pastebin.com/45vs6Txv

## 🌍  Your Environment

**Operating System:**

Arch Linux ARM (aarch64)

**Machine**
PINE Rock64

**What version of Prysm are you running? (Which release)**

alpha18

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment] 2020-08-05 09:28
Duplicate of https://github.com/prysmaticlabs/prysm/issues/6468

I don’t think the roughtime offset warning is related to the panic you observed.

**Closed by prestonvanloon** 2020-08-05 09:28 UTC
