### ISSUE TITLE
validators-external-signer-public-keys as a list

### ISSUE THREAD

**Issue by nalepae** [prysmaticlabs/prysm#11009] opened 2022-07-08 08:02 UTC
# 🚀 Feature Request

### Description

When using configuration file, it would be nice to be able to set validators external signer public keys as a list.

**Exemple of wished configuration file:**
```
accept-terms-of-use: true
log-format: json
prater: true
<... other configuration ...>
validators-external-signer-public-keys:
- key1
- key2
- key3
- ...
```

Teku does support it this way.

When I try to do it right now, I have this kind of error:
```
time="2022-07-08T07:49:25Z" level=error msg="Mismatched type for flag 'validators-external-signer-public-keys'. Expected 'string' but actual is ''" prefix=main
```

**Comment by james-prysm** [comment] 2022-07-08 20:49
Will try to take a look next week.

**Comment by james-prysm** [comment] 2022-07-14 20:11
Feature is added to develop, if you get a chance to test I'll close this ticket, otherwise I'll close when we release

**Comment by nalepae** [comment] 2022-08-02 14:34
@james-prysm do you have an example of how this could work?

With `v2.1.4-rc.0`, the previous version (with a string) does not work any more.

I tried different solution (with the list), and I always get this result:
```
time="2022-08-02 14:29:33" level=warning msg="No validating keys fetched. Trying again" prefix=validator
```

With, for example, the following configuration file:
```
prater: true
validators-external-signer-public-keys:
- 0x8001xxxx
- 0x804yyyy
- ...
```

If I use the former way (string), I get this error:
```
time="2022-08-02T14:33:50Z" level=error msg="Mismatched type for flag 'validators-external-signer-public-keys'. Expected '[]interface{}' but actual is 'string'" prefix=main
```

**Comment by james-prysm** [comment] 2022-08-02 14:36
taking a look right now. very odd error

**Comment by nalepae** [comment] 2022-08-02 14:50
@james-prysm It's quite blocking for me for the Goerli/Prater Merge, since I use Web3Signer (without about 500 keys for Prysm).

Please let me know if I misconfigured the keys.
I tried with/without `0x`.
With without space before each `-` item.
Maybe should I add `"` or `'`?

It works with `v2.1.3`.
It does not work with `v2.1.4-rc.0`.

**Comment by james-prysm** [comment] 2022-08-02 14:54
@nalepae rerunning e2e tests right now so i can give a definitive answer.
i tried locally in develop running. with ` --validators-external-signer-public-keys=
"0xa2b5aaad9c6efexxxxxxxx,0xa2b5aaad9c6efexxxxxxx"`and it seems to be working

**Comment by james-prysm** [comment] 2022-08-02 14:59
our tests are also running without the quotes I used i.e. `--validators-external-signer-public-keys=0xa99a76ed7796f7be22d5b7e85deeb7c5677e88e511e0b337618f8c4eb61349b4bf2d153f649f7b53359fe8b94a38e44c,0xb89bebc699769726a318c8e9971bd3171297c61aea4a6578a7a4f94b547dcba5bac16a89108b6b6a1fe3695d1a874a0b,0xa3a32b0f8b4ddb83f1a0a853d81dd725dfe577d4f4c3db8ece52ce2b026eca84815c1a7e8e92a4de3d755733bf7e4a9b,`

**Comment by nalepae** [comment] 2022-08-02 15:05
@james-prysm  I confirm it does **not** work on my side.
However, I use configuration file, not command line option.

My configuration file:
```
accept-terms-of-use: true
rpc-host: 0.0.0.0
grpc-gateway-host: 0.0.0.0
monitoring-host: 0.0.0.0
validators-external-signer-public-keys: 0x8001dae5feb4e12923d94bd0ec267e7bb9733d37ba96cda435b12ae4ebc278fd148b3c903280d0d56b8dbcfb998fb892,0x804fe32845ac9c3bd4c66d425908616a6cb3682b7c838273b1dcff3a7b73d369aa4b7c4fb7b6f41cc672456bda6b56d2,0x80c5ace9c54a4f22294f6ccbe37f1ee1655deba2912370440076a065b6e988340e7019193aecd05c031c85e1944e66a0,0x8131a00e218392773582a4b066d634b16e81f2c0a4d7f21dee6d3a23523fd6d403040bf1327744db89d0f752771bea0c,0x817ce8dddb61c5b5977df6e3f91bc97beb133cccd926b99f4b26ed544d9e25b43922d9b0d29a5a9e28f499a5bb378a8e,0x8190e874e3c06b715ff9eb17129ee690ac7f3542a93cdf07e9fd66739f82eb3c675829f7294790f5aec95c429c4309bf,0x81e55a6ab23fa3552f94966fa2c6a53a8b56269c01de244c0922603912b73291ce41cf116b528d58fbccfc662502eee7,0x8274d4d1099ffa1d503f66ddbc1900c6d9acc5a98d6ff6bf16b3445741afaa6daec6f516feed27948b9f9a4d9dd0206d,0x82a697b959e4b76b0e5acd93f982cf2862abcca0fdb17fef504a4546320f75edc4782cfa3fd6e4ad0c0a8f0d80cd652e,0x835a6a1cfc5996c885f39ed693e42518ba147aa0f557799db0318ead6034de47f11c5d4a1bfaca2de792f082119a29b5,0x837875a530008c112410ded2c6c9bf72945c639b1cf6106fad6f7d32bc3c9df4beafac7b3e39e01f22e883b5cda6a46c,0x839452c4ec9792d4e7fd03625db79c28ab83ba6c769cd550f8ed8774fc466c7104745f107e75f3bf2687b06cb443aa05,0x83fb0063283b032443d4e31b542abeab278db5616a5a69bd378e1ad808baa02ece73b1303f7ff97c3952e844c5372bb1,0x841e41d9c42ec738259176e7a32f041096aee878be09f03a217780792ceedf4f8d5a891b60d5eacbeccbb22e21931d47,0x84485cd267df5df159fdc83a444991c3d8b46f01acd7a4e0060cd4dff8dcfa5a71fddedf2a7972a080a4b18602380e2d,0x849de24c59751fe37add2da7d77ba713016f2d9f8095091a0f9fac5bb53ae2480c867e13b3e5a68760d4d8fcecf8a189,0x8519250b12647cc839e09a9f196bc60c8605548605e32aa6e78b4af093b3b54e3c9ae5010a23f33e131b859ca2decbe4,0x8534ed78319627857c2c5d2dddea9d966b0b8db343ec852413a586a68dac141e3e0af2c9533f68a34094c8c510b3c614,0x8536abb6ab90b0d60561060b5f8e9532c2c45e38c2db33b14836c429335fbcd2d476f0a39ff3f5aaca514797737ebf02,0x8554254f04cdbc9a51f70f0f20bd695b3bea7db13529960a46e9f1ecfd7525c9504ca4e3b6beb5af94dd57fcd68d56a5,0x859193d3a99b9e9666374035efa1dd6a508b0968bc6689eb4fb627ad2e74976713cb9c6f64ccb6c632d18c814c567235,0x85c6c09da922f3e99c4004cec151c44c2724c9c99dd518d56b479ee685d97bfd74dbb1a9e2e4a38075b3a5c83885bdda,0x85f8dc11b83532e90ea701f626b3a54a5b674d16f28b66aef5ac1ced3e77027889673fb5bceab2260cfdb90448ff5f8d,0x861a513b3c0ce14bafca00689ca456b9aecf36305467f813b9fa7d29f523ef8dcc2dca12e4784ee28bba0bfa58c3d091,0x86659a9ef84f85fdb70b071755ebef7e606a371455bfeb637aa7cff91afe4cc6d1bb70bf33316993e4031e80d119e8e3,0x86a15afa155e1e686a7604f18f95358ffd058a0d3bea13b8e8189114c16438b90aca34b081ffcf0120ed67202212b954,0x86dc357aa692680ca116c3dcb2c52721326f2bb2630881771a5a82e9ddbc8d9391528ac1f37f38857fc81da3aa385cff,0x86f6120761032dbf16267fda0ee6612e215718a012a883dec82a6b3fd121dcf3905c5f3e12fb314008da6c28cd722c3b,0x87347646e01289633a0650060aba1c85e2515d28ff01846c693f9159d7e67b0cf56472015468bfa6928bb58f86990b0b,0x873591ae746902f267b5e6929b5ce8e3f880e2f3113252cce992c9b777062ff03b0e5b1621f65a7faef4ad9669be6ed9,0x873a822386e041c186755a70cffd61bd17b4650a56e1091ba3bd648c54c...
```

The error:
```
time="2022-08-02T15:03:25Z" level=error msg="Mismatched type for flag 'validators-external-signer-public-keys'. Expected '[]interface{}' but actual is 'string'" prefix=main
```

And I still confirm it works well with `v2.1.3`, not with `v2.1.4-rc.0`

**Comment by james-prysm** [comment] 2022-08-02 15:05
but something like
```
validators-external-signer-public-keys:
 - 0x8001xxxx
 - 0x804yyyy
 - ...
```
should also work with the space in front

**Comment by james-prysm** [comment] 2022-08-02 15:10
@nalepae can you also try with brackets if you think the dashes are not working?
```
validators-external-signer-public-keys: [0x8001dae5feb4e12923d94bd0ec267e7bb9733d37ba96cda435b12ae4ebc278fd148b3c903280d0d56b8dbcfb998fb892,0x804fe32845ac9c3bd4c66d425908616a6cb3682b7c838273b1dcff3a7b73d369aa4b7c4fb7b6f41cc672456bda6b56d2]
```

**Comment by nalepae** [comment] 2022-08-02 15:12
With the list version, here is my configuration file (with the space before `-`):
```
config.yaml:
----
accept-terms-of-use: true
rpc-host: 0.0.0.0
grpc-gateway-host: 0.0.0.0
monitoring-host: 0.0.0.0
beacon-rpc-gateway-provider: goerli-prysm-beacon-0.goerli-prysm-beacon.ethereum-common:3500
beacon-rpc-provider: goerli-prysm-beacon-0.goerli-prysm-beacon.ethereum-common:4000
datadir: /data/db
enable-doppelganger: false
graffiti: Kiln
log-format: text
prater: true
validators-external-signer-public-keys:
 - 0x8001dae5feb4e12923d94bd0ec267e7bb9733d37ba96cda435b12ae4ebc278fd148b3c903280d0d56b8dbcfb998fb892
 - 0x804fe32845ac9c3bd4c66d425908616a6cb3682b7c838273b1dcff3a7b73d369aa4b7c4fb7b6f41cc672456bda6b56d2
validators-external-signer-url: http://goerli-web3signer.ethereum-web3signer:9000
```

And I get 
```
time="2022-08-02 15:09:38" level=warning msg="No validating keys fetched. Trying again" prefix=validator
```

**Comment by nalepae** [comment] 2022-08-02 15:15
Same result with:
```
config.yaml:
----
accept-terms-of-use: true
rpc-host: 0.0.0.0
grpc-gateway-host: 0.0.0.0
monitoring-host: 0.0.0.0
beacon-rpc-gateway-provider: goerli-prysm-beacon-0.goerli-prysm-beacon.ethereum-common:3500
beacon-rpc-provider: goerli-prysm-beacon-0.goerli-prysm-beacon.ethereum-common:4000
datadir: /data/db
enable-doppelganger: false
graffiti: Kiln
log-format: text
prater: true
validators-external-signer-public-keys: [0x8001dae5feb4e12923d94bd0ec267e7bb9733d37ba96cda435b12ae4ebc278fd148b3c903280d0d56b8dbcfb998fb892, 0x804fe32845ac9c3bd4c66d425908616a6cb3682b7c838273b1dcff3a7b73d369aa4b7c4fb7b6f41cc672456bda6b56d2]
validators-external-signer-url: http://goerli-web3signer.ethereum-web3signer:9000
```

**Comment by james-prysm** [comment] 2022-08-02 15:16
@nalepae can we try to isolate this issue? what happens with only 1 key value?

**Comment by nalepae** [comment] 2022-08-02 15:23
> @nalepae can we try to isolate this issue? what happens with only 1 key value?
OK I'll try.
Meanwhile, I tried with the command line, instead of the config file:

```
--config-file=/config/config.yaml --validators-external-signer-public-keys=0x8001dae5feb4e12923d94bd0ec267e7bb9733d37ba96cda435b12ae4ebc278fd148b3c903280d0d56b8dbcfb998fb892,0x804fe32845ac9c3bd4c66d425908616a6cb3682b7c838273b1dcff3a7b73d369aa4b7c4fb7b6f41cc672456bda6b56d2
```

and it works well.

**Comment by nalepae** [comment] 2022-08-02 15:35
Now with this all following configuration files, I get this result:
```
time="2022-08-02 15:25:08" level=warning msg="No validating keys fetched. Trying again" prefix=validator
```

The tried conf files:

**Without space before `-`**
```
log-format: text
prater: true
validators-external-signer-public-keys:
- 0x8001dae5feb4e12923d94bd0ec267e7bb9733d37ba96cda435b12ae4ebc278fd148b3c903280d0d56b8dbcfb998fb892
validators-external-signer-url: http://goerli-web3signer.ethereum-web3signer:9000
```

**With 1 space before `-`**
```
log-format: text
prater: true
validators-external-signer-public-keys:
 - 0x8001dae5feb4e12923d94bd0ec267e7bb9733d37ba96cda435b12ae4ebc278fd148b3c903280d0d56b8dbcfb998fb892
validators-external-signer-url: http://goerli-web3signer.ethereum-web3signer:9000
```

**With 2 spaces before `-`**
```
log-format: text
prater: true
validators-external-signer-public-keys:
  - 0x8001dae5feb4e12923d94bd0ec267e7bb9733d37ba96cda435b12ae4ebc278fd148b3c903280d0d56b8dbcfb998fb892
validators-external-signer-url: http://goerli-web3signer.ethereum-web3signer:9000
```

**JSON like**
```
log-format: text
prater: true
validators-external-signer-public-keys: [0x8001dae5feb4e12923d94bd0ec267e7bb9733d37ba96cda435b12ae4ebc278fd148b3c903280d0d56b8dbcfb998fb892]
validators-external-signer-url: http://goerli-web3signer.ethereum-web3signer:9000
```

**Comment by nalepae** [comment] 2022-08-02 15:35
As I see right now, only the command-line-string-version seems to work.

**Comment by james-prysm** [comment] 2022-08-02 15:55
I'll go investigate this further, please use this workaround in the mean time I'll update when I can.

**Comment by james-prysm** [comment] 2022-08-02 18:32
I was able to recreate this but still in the process of identifying root cause

**Comment by james-prysm** [comment] 2022-08-02 21:10
@nalepae I believe I may have found the reason this is happening, I am still in the process of testing different cases. I apologize for the distruption this caused you and will try to fix this ASAP.

**Comment by nalepae** [comment] 2022-08-02 21:14
Thank you for your investigation!

For information as a workaround I modified my Helm charts so that all keys are given as a big string to the command line option. It is not very elegant but at least it works ;)

**Comment by rauljordan** [comment] 2022-08-17 15:48
hi @james-prysm is this resolved?

**Comment by james-prysm** [comment] 2022-08-17 15:51
> hi @james-prysm is this resolved?

Yes this should be resolved but it's not released yet.
I was waiting for @nalepae to return from OOO before closing.

**Comment by nalepae** [comment] 2022-08-19 09:51
Is there a Docker image where I can test it?

**Comment by james-prysm** [comment] 2022-08-19 16:45
@nalepae I think you can get it from here https://hub.docker.com/r/prysmaticlabs/prysm-validator/tags changes are in develop

**Comment by skrbug** [comment] 2022-08-29 08:43
Same issue in v2.1.4.           
v3.0.0 works well.

**Comment by james-prysm** [comment] 2022-08-29 16:25
going to close this now that v3.0.0 works

**Closed by james-prysm** 2022-08-29 16:25 UTC
Labels: Web3Signer, UX

**Comment by nalepae** [comment] 2022-09-01 14:21
It works, thanks!

**Comment by thevops** [comment] 2023-11-23 08:42
Just for general information.
I tried the same with v4, and `validators-external-signer-public-keys` has to be a YAML list, not a string.
