### ISSUE TITLE
Beacon Chain Client crashed after genesis transition

### ISSUE THREAD

**Issue by torfbolt** [prysmaticlabs/prysm#4476] opened 2020-01-10 08:20 UTC
Tonight some minutes after the testnet genesis transition my beacon client crashed spectacularly, with lots of debug output. Unfortunately it crashed so hard that I couldn't kill it and had to reboot my machine, so I lost the error messages.

The client was running since ~30h before genesis and showed no problems before 2020-01-10 00:00Z, just a message that it was waiting for genesis.

**Comment by prestonvanloon** [comment] 2020-01-11 01:35
Closing as duplicate of #4482. We are pretty certain these issues are related. Thanks!

**Closed by prestonvanloon** 2020-01-11 01:35 UTC
