### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by KuDeTa** [prysmaticlabs/prysm#4875] opened 2020-02-16 16:07 UTC
[2020-02-16 01:24:16]  WARN blockchain: Could not receive attestation in chain service aggregationCount=40 beaconBlockRoot=0x9637ba8b4fa7 committeeIndex=3 error=head at slot 266784 with weight 10119 is not eligible, finalizedEpoch 8335 != 8335, justifiedEpoch 8336 != 8337
could not process attestation
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveAttestationNoPubsub
	beacon-chain/blockchain/receive_attestation.go:37
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).processAttestation
	beacon-chain/blockchain/receive_attestation.go:90
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357 slot=266817 targetRoot=0x9637ba8b4fa7
[2020-02-16 01:24:16]  WARN blockchain: Could not receive attestation in chain service aggregationCount=48 beaconBlockRoot=0x9637ba8b4fa7 committeeIndex=0 error=head at slot 266784 with weight 10121 is not eligible, finalizedEpoch 8335 != 8335, justifiedEpoch 8336 != 8337
could not process attestation
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveAttestationNoPubsub
	beacon-chain/blockchain/receive_attestation.go:37
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).processAttestation
	beacon-chain/blockchain/receive_attestation.go:90
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357 slot=266817 targetRoot=0x9637ba8b4fa7
[2020-02-16 01:24:16]  WARN blockchain: Could not receive attestation in chain service aggregationCount=16 beaconBlockRoot=0x9637ba8b4fa7 committeeIndex=6 error=head at slot 266784 with weight 10122 is not eligible, finalizedEpoch 8335 != 8335, justifiedEpoch 8336 != 8337
could not process attestation
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveAttestationNoPubsub
	beacon-chain/blockchain/receive_attestation.go:37
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).processAttestation
	beacon-chain/blockchain/receive_attestation.go:90
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357 slot=266817 targetRoot=0x9637ba8b4fa7
[2020-02-16 01:24:16]  INFO p2p: Peer disconnected active=3 peer=16Uiu2HAmEmBrydi6J7FyVyX1uootTNULWYPS3mW4JgCTAANbHJTt
[2020-02-16 01:24:18]  INFO p2p: Peer connected activePeers=1 direction=1 multiAddr=/ip4/3.83.228.44/tcp/33655/p2p/16Uiu2HAm43K7ieBWVYspWbR8pKMED86dyLHMWpMUynQgjsY2Bd19 peer=16Uiu2HAm43K7ieBWVYspWbR8pKMED86dyLHMWpMUynQgjsY2Bd19
panic: runtime error: integer divide by zero

goroutine 234 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).processPendingAtts(0xc00082df00, 0x1bc3dc0, 0xc01fc93ec0, 0x0, 0x0)
	beacon-chain/sync/pending_attestations_queue.go:120 +0x1558
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).processPendingAttsQueue.func1()
	beacon-chain/sync/pending_attestations_queue.go:30 +0x72
github.com/prysmaticlabs/prysm/shared/runutil.RunEvery.func1(0xc015d4a870, 0x25f36c8, 0x59, 0xc0161779e0, 0x1bc3d00, 0xc015d47900)
	shared/runutil/every.go:22 +0xec
created by github.com/prysmaticlabs/prysm/shared/runutil.RunEvery
	shared/runutil/every.go:17 +0x136

**Running:** sha256:a26a1ac18ae72875ec978cb04167910546c3452451592a87877a49ed275ace33

**Comment by prestonvanloon** [comment] 2020-02-16 16:56
Duplicate of #4777

**Closed by prestonvanloon** 2020-02-16 16:56 UTC

**Comment by aranhaagency** [comment] 2020-02-16 20:58
Hi @prestonvanloon, I'm waiting for the review of the pull request.
