### ISSUE TITLE
Checkpoint sync does not work with Infura

### ISSUE THREAD

**Issue by yorickdowne** [prysmaticlabs/prysm#10601] opened 2022-05-02 08:20 UTC
# 💎 Issue

Prysm 2.1.0 does not use the projectid and secret when querying the version of the CL, if those are present, and thus checkpoint sync towards an Infura "ETH2" project fails. Log output:

```
consensus_1         | time="2022-05-02 08:16:22" level=info msg="requesting http://eth2-beacon-prater.infura.io/eth/v1/beacon/weak_subjectivity"
consensus_1         | time="2022-05-02 08:16:23" level=info msg="falling back to generic checkpoint derivation, weak_subjectivity API not supported by server"
consensus_1         | time="2022-05-02 08:16:23" level=info msg="requesting http://eth2-beacon-prater.infura.io/eth/v1/node/version"
consensus_1         | time="2022-05-02 08:16:24" level=error msg="Error retrieving checkpoint origin state and block: unable to proceed with fallback method without confirming node version: error requesting node version: code=401, url=https://eth2-beacon-prater.infura.io:443/eth/v1/node/version, body=response body:
consensus_1         | project id required
consensus_1         | : did not receive 2xx response from API" prefix=main
```

`checkpoint_sync_url` is set to `https://{projectid}:{secret}@eth2-beacon-${NETWORK}.infura.io/`

**Comment by nisdas** [comment] 2022-05-02 08:27
cc @kasey

**Comment by kasey** [comment] 2022-05-04 22:59
Thank you for the bug report! This is a duplicate of https://github.com/prysmaticlabs/prysm/issues/10467

**Closed by kasey** 2022-05-04 22:59 UTC
Labels: Bug
