### ISSUE TITLE
Broadcasting/Sending P2P Msgs Is Broken

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#465] opened 2018-09-02 22:31 UTC
Hi all,

A recent change to accept proto.Message instead of generic `interface{}` for p2p messages over topics led to some breaking issues at runtime.

### What Went Wrong and How to Reproduce?

If we run the beacon-chain on the master branch with a simulator flag on, we get unknown topics. We can address this issue by making sure every `.Send(), .Broadcast()` call in the beacon chain project uses pointers of protos: `p2p.Broadcast(&pb.SomeProto{})`. We also have to update the topic mappings in `node/` package to use pointers instead of values in the mapping.

Once we do this, we get this following new issue:

```bash
[2018-09-02 17:10:45] DEBUG simulator: Announcing block hash announcedBlockHash=0x53b6738547051e47c9f35d9ece4bd278080aa4c66e003c4f3d8ef74c22b1fa00
[2018-09-02 17:10:45] DEBUG p2p: Broadcasting msg hash:"S\266s\205G\005\036G\311\363]\236\316K\322x\010\n\244\306n\000<O=\216\367L\"\261\372\000"  topic=BEACON_BLOCK_HASH_ANNOUNCE
[2018-09-02 17:10:45] ERROR p2p: Received message is not a protobuf message
```

**Comment by prestonvanloon** [comment] 2018-09-02 22:45
Currently investigating this issue. The primary suspicion is that the changes to the API for broadcasting messages might be related or something with the adapter changes.

Trying to reproduce within a test and I hope to resolve this soon or revert the breaking changes.

**Comment by rauljordan** [comment] 2018-09-08 10:35
Hey @prestonvanloon have you had a chance to look into this more?

**Comment by prestonvanloon** [comment] 2018-09-08 22:29
I have been unable to reproduce with a test. For whatever reason, libp2p is not cooperating with me.

I have subscriber tests here: https://github.com/prysmaticlabs/prysm/blob/d4209b7357101642a17dd8e4f3326fe73c89c0bb/shared/p2p/service_test.go#L187

These currently send an empty message on a topic, just to see if the adapters run. The reason I am using an empty message is that if I pass a non-empty message then the test no longer works unless the test is run by it self. 

```bash
# Works
bazel test //shared/p2p:go_default_test --test_output=streamed --test_filter=TestRegisterTopic_withoutAdapters --cache_test_results=no

# Does not work
bazel test //shared/p2p:go_default_test --test_output=streamed  --cache_test_results=no
```

I have been toying on this for about a week now and making zero progress. I can't tell if it's something wrong with libp2p or our code, but it doesn't make any sense. 

I'll stop trying to reproduce in the test and just work on a fix for runtime.

**Comment by prestonvanloon** [comment] 2018-09-08 23:55
The above issues can be reproduced in this branch: https://github.com/prestonvanloon/prysm/commit/ca35a6fabb0711f07b627d22c03634f4f35412e0

**Comment by prestonvanloon** [comment] 2018-09-09 15:34
I have identified the issue with reflect types. Since proto.Message is a pointer to the underlying struct, i.e. `*pb.BeaconBlockAnnounce`, and reflect.New creates a new pointer to the given type, we ended up with `**pb.BeaconBlockAnnounce` which ended up resolving to a nil ptr. 

I have the fix ready, I'm just trying to resolve new test breakages with libp2p.

**Closed** 2018-09-09 22:15 UTC
Labels: Beacon Chain, Bug
