### ISSUE TITLE
Attestation Signature Does Not Verify

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#4773] opened 2020-02-06 06:47 UTC
A non-trivial amount of attestations fail with 
```
 WARN blockchain: Could not receive attestation in chain service aggregationCount=1 beaconBlockRoot=0x7fbdf4ae245d committeeIndex=5 error=signature did not verify
```
This most likely is caused because of a bug in our aggregation code.

**Comment by princesinha19** [comment] 2020-02-07 06:44
@nisdas I think this is duplicate of #4630

**Comment by rauljordan** [comment] 2020-02-10 17:16
Closing in favor of #4630

**Closed by rauljordan** 2020-02-10 17:16 UTC
Labels: Bug, Priority: Critical
