### ISSUE TITLE
Add naive p2p chain handshake

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2293] opened 2019-04-18 16:50 UTC
When two peers connect, they should communicate what chain they are on. This can be identified by the deposit contract address. If peers are on different deposit contracts, they should disconnect and not attempt to re-peer with that peer.

**Comment by 0xKiwi** [comment] 2019-04-18 17:29
Closing as this is a duplicate of #2283

**Closed by 0xKiwi** 2019-04-18 17:29 UTC
