### ISSUE TITLE
Validator: Invalid attester slots + strange things

### ISSUE THREAD

**Issue by AlexSSD7** [prysmaticlabs/prysm#5912] opened 2020-05-19 18:58 UTC
# 🐞 Bug Report

### Description
Random invalid attester slots warnings and other strange things.

### Has this worked before in a previous version?
Haven't tried

## 🔬 Minimal Reproduction
I don't clearly know how to reproduce it, but I can share my validator setup details. I had 1000 validators running with only ~20 of them active. Other validators were joining the party continuously as some of them we're in queue, and others had the DEPOSITED statuses.

## 🔥 Error

Log screen rec: https://www.youtube.com/watch?v=728SoB4RBYE

#### Additionally:
1. Noticed strange stuff at 0:33 timecode. The validator that is currently pending showed up as ACTIVE, and prysm was is trying to attest using the pending validator. After prysm failed (for obvious reasons), it printed out `Invalid attester slot` warnings.

2. 0:30 timecode. Something is wrong with `Previous epoch voting summary`.

## 🌍  Your Environment
**What version of Prysm are you running? (Which release)**

<pre>
  <code>
        Docker image with tag `latest` downloaded on May 18 ~20:00 UTC.
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

1k validators (pubkeys are seen on the screen rec)

**Comment by terencechain** [comment] 2020-05-19 21:07
root cause has been identified by @rauljordan and @prestonvanloon, please reference this issue in the PR for the fix

**Comment by terencechain** [comment] 2020-05-20 15:28
Addressed in #5913

**Closed by terencechain** 2020-05-20 15:28 UTC
Labels: Bug, Priority: High
