### ISSUE TITLE
[Enhancement] Rescan keypool for new validator keys

### ISSUE THREAD

**Issue by superphiz** [prysmaticlabs/prysm#4222] opened 2019-12-08 17:25 UTC
In its current form the validator scans prysm/validator for validatorprivatekey files once on launch. With this design adding new validators could result in a disruption in validator uptime. Add a feature to enable for new validator key scanning with a minimum disruption to currently running validators.

**Comment by q9f** [comment] 2020-01-29 08:36
I second this, especially if you run more than one validator and the restart could take a while, ref #4683

**Comment by mcdee** [comment] 2020-01-29 08:41
This is something that can be added through the keymanager interface relatively easily, the more pertinent question is when to run such a rescan.  Periodic rescan could take a lot of CPU time in the case where keystores are encrypted.  Will consider how best to tackle this.

**Comment by q9f** [comment] 2020-01-29 08:45
Having some index or cache for already decoded keys could speed this up significantly. So you look at the keys that are loaded already and just decode the ones that aren't. That way, it shouldn't be expensive to run this periodically.

**Comment by mcdee** [comment] 2020-01-29 08:55
It is possible for the individual password stores to be encrypted, so there's no way of knowing what the key inside each file may be without decrypting it first.  And because keymanager is an interface to possibly any implementation (e.g. HSM) we'd need to consider the capabilities of the endpoint so we don't put an unreasonable burden on it (or worse, exclude some potential implementations from being able to support the interface).

This is definitely something we want, it's just a case of finding a way to make it work for both current and future key managers.

**Comment by rauljordan** [comment] 2020-02-18 04:57
This is a really great first issue for our new teammate @farazdagi to get involved in the repo. To outline some of the requirements a bit more, our [validator client](https://github.com/prysmaticlabs/prysm/tree/master/validator) currently uses a `keymanager` interface created by @mcdee [here](https://github.com/prysmaticlabs/prysm/blob/40afef8b9e076fed4200f2aaa1cb2ab7c46b5b57/validator/keymanager/keymanager.go#L16) which can be implemented in a variety of ways, including this simple direct keymanager currently in our validator client code [here](https://github.com/prysmaticlabs/prysm/blob/40afef8b9e076fed4200f2aaa1cb2ab7c46b5b57/validator/keymanager/direct.go#L32). 

Currently, on startup, a validator client fetches the validator keys currently in the store as part of its runtime and uses those throughout its lifecycle. A validator client can manage many keys, even tens of thousands, but those currently need to available on startup of the validator client for it to pick them up.

This issue is requesting to rescan the keystore (either filesystem or anything else that implements the `keymanager` interface) via some polling mechanism to easily add new keys without needing to restart the process. @mcdee here suggest just adding some `RescanKeys()` function in the interface definition and implementing that. There are a few issues that come to mind with a naive solution as mentioned in the comments above:
1. We might need to decrypt the keys to understand if they are valid validator keys, making the rescanning a bit expensive
2. Consider some of the possible keymanager implementations and their limitations, as doing polling on an HSM or other hardware might be inefficient based on how frequent we do it

However, I believe would be nice for this to work in a simple manner for now and we can consider use-case limitations further down the line as they arise or are requested by people interacting with Prysm. To tackle this issue, here's the workflow we would typically take:
1. Open a PR that mentions `resolves #4222` in the description using the default pull request template in the repo
2. Describe your approach in the pull request description carefully
3. Before writing code, talk with the rest of the team on discord regarding a suggested approach
4. Keep the PR simple, scoped, and preferably under 300 lines (excluding tests)
5. Write comprehensive tests that cover most of your logic, run `bazel run //:gazelle` and `bazel test //validator/keymanager:go_default_test` to run the package tests after you add your code
6. Label the PR as `Ready for Review` and request reviews from teammates
7. Mention on discord in our code-review channel your progress on the issue

We'd love to help out get you more accustomed to contributing. As a sample PR that follows these practices, please see: https://github.com/prysmaticlabs/prysm/pull/4866

**Comment by rauljordan** [comment] 2020-02-18 04:58
It is also useful to sometimes add benchmarks for validating assumptions for a feature such as this. Perhaps an encrypted keystore rescan might be really expensive to do compared to a direct, unencrypted keymanager, and those numbers could come in handy if needed.

**Comment by mcdee** [comment] 2020-02-18 10:21
Note that rescanning for information has traditionally been carried out on receipt of a signal in unix land  (commonly SIGHUP); having a user-initiated rescan will cut down on the amount of unnecessary work the validator has to do.

Perhaps this could be an RPC call in to the validator (if the validator even has an RPC interface)?

**Comment by farazdagi** [comment] 2020-02-18 10:34
Idea of having user-initiated rescan is definitely something to keep in mind. It definitely will work quite well with the naive/resource intensive approach to rescan (since we, supposedly, don't have unnecessary runs, our process might be relatively expensive). 

Once I get my head around the validator's code better (and have benchmarks), will get back with more sensible comment.

**Comment by rauljordan** [comment] 2020-04-14 16:33
@farazdagi are you still interested in taking up this issue? Assigning provisionally for now

**Comment by farazdagi** [comment] 2020-04-14 16:38
@rauljordan yep, will start looking into this during tomorrow's session (it is great chance to look into validator code, which I haven't touched so far).

**Comment by rauljordan** [comment] 2020-04-14 17:45
Duplicate of https://github.com/prysmaticlabs/prysm/issues/5202

**Closed by rauljordan** 2020-04-14 17:45 UTC
Labels: Enhancement, Good First Issue, Help Wanted
