### ISSUE TITLE
Estimated time to sync creeps up

### ISSUE THREAD

**Issue by elsampsa** [prysmaticlabs/prysm#11476] opened 2022-09-20 11:32 UTC
### Description

Started a fresh sync more than 24 hrs ago.  Here are some of the logs on the way:
```
-- Logs begin at Mon 2022-09-19 07:20:21 CEST, end at Tue 2022-09-20 13:22:08 CEST. --
syys 19 07:20:25 sampsa-asus systemd[1260]: Started Prysm consensus layer client.
syys 19 07:20:27 sampsa-asus bazel[1296]: Starting local Bazel server and connecting to it...
syys 19 07:20:39 sampsa-asus bazel[1296]: Loading:
syys 19 07:20:39 sampsa-asus bazel[1296]: Loading: 0 packages loaded
syys 19 07:20:40 sampsa-asus bazel[1296]: Loading: 0 packages loaded
syys 19 07:20:41 sampsa-asus bazel[1296]: Loading: 0 packages loaded
syys 19 07:20:43 sampsa-asus bazel[1296]: Loading: 0 packages loaded
syys 19 07:20:45 sampsa-asus bazel[1296]: DEBUG: /home/sampsa/.cache/bazel/_bazel_sampsa/2c79593366c1c4a91e6b88a94f3a237d/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
syys 19 07:20:45 sampsa-asus bazel[1296]: Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
syys 19 07:20:45 sampsa-asus bazel[1296]: DEBUG: /home/sampsa/.cache/bazel/_bazel_sampsa/2c79593366c1c4a91e6b88a94f3a237d/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:100:14: rbe_ubuntu_clang_gen not using checked in configs as user set attr to 'False'
syys 19 07:20:45 sampsa-asus bazel[1296]: DEBUG: /home/sampsa/.cache/bazel/_bazel_sampsa/2c79593366c1c4a91e6b88a94f3a237d/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
syys 19 07:20:45 sampsa-asus bazel[1296]: Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
syys 19 07:20:45 sampsa-asus bazel[1296]: DEBUG: /home/sampsa/.cache/bazel/_bazel_sampsa/2c79593366c1c4a91e6b88a94f3a237d/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:100:14: rbe_ubuntu_gcc_gen not using checked in configs as user set attr to 'False'
syys 19 07:20:45 sampsa-asus bazel[1296]: DEBUG: /home/sampsa/.cache/bazel/_bazel_sampsa/2c79593366c1c4a91e6b88a94f3a237d/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
syys 19 07:20:45 sampsa-asus bazel[1296]: Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
syys 19 07:20:45 sampsa-asus bazel[1296]: Loading: 0 packages loaded
syys 19 07:20:53 sampsa-asus bazel[1296]: Loading: 0 packages loaded
syys 19 07:20:53 sampsa-asus bazel[1296]:     currently loading: beacon-chain
...
...
syys 19 07:24:26 sampsa-asus bazel[1296]: time="2022-09-19 07:24:26" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=2
syys 19 07:24:32 sampsa-asus bazel[1296]: time="2022-09-19 07:24:32" level=info msg="Processing block batch of size 31 starting from  0x3bf792d5... 4245889/4728420 - estimated time remaining 86h28m30s" blocksPerSecond=1.6 peers=6 prefix=initial-sync
syys 19 07:24:36 sampsa-asus bazel[1296]: time="2022-09-19 07:24:36" level=info msg="Connected to new endpoint: /***" prefix=powchain
syys 19 07:24:46 sampsa-asus bazel[1296]: time="2022-09-19 07:24:46" level=info msg="Ready for The Merge" latestDifficulty=58749299012835133516771 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 19 07:24:56 sampsa-asus bazel[1296]: time="2022-09-19 07:24:56" level=info msg="Ready for The Merge" latestDifficulty=58749299012835133516771 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 19 07:25:06 sampsa-asus bazel[1296]: time="2022-09-19 07:25:06" level=info msg="Ready for The Merge" latestDifficulty=58749299012835133516771 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 19 07:25:16 sampsa-asus bazel[1296]: time="2022-09-19 07:25:16" level=info msg="Ready for The Merge" latestDifficulty=58749299012835133516771 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 19 07:25:21 sampsa-asus bazel[1296]: time="2022-09-19 07:25:21" level=info msg="Peer summary" activePeers=23 inbound=0 outbound=23 prefix=p2p
syys 19 07:25:26 sampsa-asus bazel[1296]: time="2022-09-19 07:25:26" level=info msg="Ready for The Merge" latestDifficulty=58749299012835133516771 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 19 07:25:28 sampsa-asus bazel[1296]: time="2022-09-19 07:25:28" level=info msg="Processing block batch of size 64 starting from  0x479311c5... 4245920/4728425 - estimated time remaining 41h53m2s" blocksPerSecond=3.2 peers=25 prefix=initial-sync
syys 19 07:25:36 sampsa-asus bazel[1296]: time="2022-09-19 07:25:36" level=info msg="Ready for The Merge" latestDifficulty=58749299012835133516771 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
...
...
syys 19 08:08:42 sampsa-asus bazel[1296]: time="2022-09-19 08:08:42" level=info msg="Processing block batch of size 63 starting from  0x862251d7... 4259488/4728641 - estimated time remaining 13h43m4s" blocksPerSecond=9.5 peers=44 prefix=initial-sync
syys 19 08:08:50 sampsa-asus bazel[1296]: time="2022-09-19 08:08:50" level=info msg="Processing block batch of size 64 starting from  0xcb0d274f... 4259552/4728642 - estimated time remaining 13h42m57s" blocksPerSecond=9.5 peers=46 prefix=initial-sync
syys 19 08:08:57 sampsa-asus bazel[1296]: time="2022-09-19 08:08:57" level=warning msg="Unable to cache headers for execution client votes" error="(1663488087 > 1663224162): provided time is later than the current eth1 head" prefix=powchain
syys 19 08:08:58 sampsa-asus bazel[1296]: time="2022-09-19 08:08:58" level=info msg="Processing block batch of size 64 starting from  0x371d9f10... 4259616/4728642 - estimated time remaining 13h38m32s" blocksPerSecond=9.6 peers=46 prefix=initial-sync
syys 19 08:09:06 sampsa-asus bazel[1296]: time="2022-09-19 08:09:06" level=info msg="Processing block batch of size 64 starting from  0xc97b8965... 4259680/4728643 - estimated time remaining 13h34m10s" blocksPerSecond=9.6 peers=48 prefix=initial-sync
syys 19 08:09:12 sampsa-asus bazel[1296]: time="2022-09-19 08:09:12" level=warning msg="Unable to cache headers for execution client votes" error="(1663488087 > 1663224162): provided time is later than the current eth1 head" prefix=powchain
syys 19 08:09:14 sampsa-asus bazel[1296]: time="2022-09-19 08:09:14" level=info msg="Processing block batch of size 63 starting from  0xe3852a68... 4259744/4728644 - estimated time remaining 13h38m19s" blocksPerSecond=9.6 peers=42 prefix=initial-sync
syys 19 08:09:21 sampsa-asus bazel[1296]: time="2022-09-19 08:09:21" level=info msg="Peer summary" activePeers=43 inbound=35 outbound=8 prefix=p2p
syys 19 08:09:22 sampsa-asus bazel[1296]: time="2022-09-19 08:09:22" level=info msg="Processing block batch of size 63 starting from  0xfd061ce0... 4259808/4728644 - estimated time remaining 13h42m31s" blocksPerSecond=9.5 peers=44 prefix=initial-sync
...
...
syys 20 00:01:39 sampsa-asus bazel[15521]: time="2022-09-20 00:01:39" level=info msg="Processing block batch of size 61 starting from  0x53796d6d... 1214144/4733406 - estimated time remaining 320h30m56s" blocksPerSecond=3.0 peers=47 prefix=initial-sync
syys 20 00:01:42 sampsa-asus bazel[15521]: time="2022-09-20 00:01:42" level=info msg="Processing block batch of size 64 starting from  0xa65da697... 1214208/4733406 - estimated time remaining 156h24m31s" blocksPerSecond=6.2 peers=46 prefix=initial-sync
syys 20 00:01:45 sampsa-asus bazel[15521]: time="2022-09-20 00:01:45" level=info msg="Processing block batch of size 63 starting from  0x915db0ec... 1214272/4733406 - estimated time remaining 103h59m35s" blocksPerSecond=9.4 peers=48 prefix=initial-sync
syys 20 00:01:46 sampsa-asus bazel[15521]: time="2022-09-20 00:01:46" level=info msg="Ready for The Merge" latestDifficulty=17179869184 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 20 00:01:49 sampsa-asus bazel[15521]: time="2022-09-20 00:01:49" level=info msg="Processing block batch of size 64 starting from  0x4532d78a... 1214336/4733407 - estimated time remaining 77h34m51s" blocksPerSecond=12.6 peers=48 prefix=initial-sync
syys 20 00:01:52 sampsa-asus bazel[15521]: time="2022-09-20 00:01:52" level=info msg="Processing block batch of size 62 starting from  0xc09729a9... 1214400/4733407 - estimated time remaining 62h15m40s" blocksPerSecond=15.7 peers=50 prefix=initial-sync
syys 20 00:01:55 sampsa-asus bazel[15521]: time="2022-09-20 00:01:55" level=info msg="Processing block batch of size 63 starting from  0x180daa51... 1214464/4733407 - estimated time remaining 51h51m21s" blocksPerSecond=18.9 peers=53 prefix=initial-sync
syys 20 00:01:56 sampsa-asus bazel[15521]: time="2022-09-20 00:01:56" level=info msg="Ready for The Merge" latestDifficulty=17179869184 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 20 00:01:58 sampsa-asus bazel[15521]: time="2022-09-20 00:01:58" level=info msg="Processing block batch of size 60 starting from  0xe82e1348... 1214528/4733407 - estimated time remaining 44h44m7s" blocksPerSecond=21.9 peers=53 prefix=initial-sync
syys 20 00:02:03 sampsa-asus bazel[15521]: time="2022-09-20 00:02:03" level=info msg="Saved state in DB" prefix=state-gen root=180daa517d15 slot=1214464
syys 20 00:02:03 sampsa-asus bazel[15521]: time="2022-09-20 00:02:03" level=info msg="Processing block batch of size 64 starting from  0x6e3f9370... 1214592/4733408 - estimated time remaining 51h59m31s" blocksPerSecond=18.8 peers=53 prefix=initial-sync
syys 20 00:02:06 sampsa-asus bazel[15521]: time="2022-09-20 00:02:06" level=info msg="Processing block batch of size 60 starting from  0x80661ef1... 1214656/4733408 - estimated time remaining 52h24m33s" blocksPerSecond=18.6 peers=53 prefix=initial-sync
syys 20 00:02:06 sampsa-asus bazel[15521]: time="2022-09-20 00:02:06" level=info msg="Ready for The Merge" latestDifficulty=17179869184 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
...
...
syys 20 13:23:36 sampsa-asus bazel[15521]: time="2022-09-20 13:23:36" level=info msg="Ready for The Merge" latestDifficulty=17179869184 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 20 13:23:37 sampsa-asus bazel[15521]: time="2022-09-20 13:23:37" level=info msg="Processing block batch of size 63 starting from  0xa662bfd9... 1919872/4737416 - estimated time remaining 61h23m3s" blocksPerSecond=12.8 peers=41 prefix=initial-sync
syys 20 13:23:42 sampsa-asus bazel[15521]: time="2022-09-20 13:23:42" level=info msg="Processing block batch of size 63 starting from  0x578c3d86... 1919936/4737416 - estimated time remaining 61h37m28s" blocksPerSecond=12.7 peers=41 prefix=initial-sync
syys 20 13:23:46 sampsa-asus bazel[15521]: time="2022-09-20 13:23:46" level=info msg="Ready for The Merge" latestDifficulty=17179869184 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 20 13:23:47 sampsa-asus bazel[15521]: time="2022-09-20 13:23:47" level=info msg="Processing block batch of size 63 starting from  0x5e1c3b6b... 1920000/4737417 - estimated time remaining 61h52m0s" blocksPerSecond=12.7 peers=45 prefix=initial-sync
syys 20 13:23:53 sampsa-asus bazel[15521]: time="2022-09-20 13:23:53" level=info msg="Processing block batch of size 64 starting from  0x4ec1b167... 1920064/4737417 - estimated time remaining 61h51m55s" blocksPerSecond=12.7 peers=46 prefix=initial-sync
syys 20 13:23:56 sampsa-asus bazel[15521]: time="2022-09-20 13:23:56" level=info msg="Ready for The Merge" latestDifficulty=17179869184 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 20 13:23:58 sampsa-asus bazel[15521]: time="2022-09-20 13:23:58" level=info msg="Processing block batch of size 64 starting from  0xd543b993... 1920128/4737417 - estimated time remaining 61h37m13s" blocksPerSecond=12.7 peers=45 prefix=initial-sync
syys 20 13:24:03 sampsa-asus bazel[15521]: time="2022-09-20 13:24:03" level=info msg="Processing block batch of size 64 starting from  0x51f6fc50... 1920192/4737418 - estimated time remaining 61h22m38s" blocksPerSecond=12.8 peers=45 prefix=initial-sync
syys 20 13:24:06 sampsa-asus bazel[15521]: time="2022-09-20 13:24:06" level=info msg="Ready for The Merge" latestDifficulty=17179869184 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
```

### Has this worked before in a previous version?

Prysm has _never_ worked for me.

## 🔬 Minimal Reproduction

Ditto

## 🔥 Error

Sync time just keeps creeping up.  Currently at 60+ hrs.

## 🌍  Your Environment

**Operating System:**

```
Ubuntu 18.04 LTS
```

**What version of Prysm are you running? (Which release)**

v3.1.1

**Anything else relevant (validator index / public key)?**

The exec layer client is geth v1.10.25: https://github.com/ethereum/go-ethereum/releases/tag/v1.10.25
..i.e. that version that waits for beacon chain to dl before dl:ing its own stuff (in order to avoid state snapshot spam..?  see release those release notes).   Geth says this:
```
syys 20 12:56:16 sampsa-asus geth[15754]: WARN [09-20|12:56:16.345] Beacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain!
syys 20 13:01:16 sampsa-asus geth[15754]: WARN [09-20|13:01:16.376] Beacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain!
syys 20 13:06:16 sampsa-asus geth[15754]: WARN [09-20|13:06:16.406] Beacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain!
syys 20 13:11:16 sampsa-asus geth[15754]: WARN [09-20|13:11:16.440] Beacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain!
...
```

**Comment by elsampsa** [comment] 2022-09-20 11:36
appendum: running as systemd daemon.  Here you can see the actual command used to run it:
```
prysm.service - Prysm consensus layer client
   Loaded: loaded (/home/sampsa/.config/systemd/user/prysm.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2022-09-19 11:50:31 CEST; 1 day 1h ago
 Main PID: 15521 (bazel)
   CGroup: /user.slice/user-1000.slice/user@1000.service/prysm.service
           ├─15521 /home/sampsa/.local/bin/bazel run //beacon-chain --config=release -- --execution-endpoint=/home/sampsa/.ethereum/geth.ipc --accept-terms-of-use
           └─15527 /home/sampsa/.cache/bazel/_bazel_sampsa/2c79593366c1c4a91e6b88a94f3a237d/execroot/prysm/bazel-out/k8-opt/bin/cmd/beacon-chain/beacon-chain_/beacon-chain --execution-endpoint=/home/sampsa/.ethereum/geth.ipc --accept-terms-of-use

syys 20 13:34:01 sampsa-asus bazel[15521]: time="2022-09-20 13:34:01" level=info msg="Processing block batch of size 64 starting from  0x2a6d5c4a... 1927104/4737468 - estimated time remaining 61h28m8s" blocksPerSecond=12.7 peers=50 prefix=initial-sync
syys 20 13:34:06 sampsa-asus bazel[15521]: time="2022-09-20 13:34:06" level=info msg="Ready for The Merge" latestDifficulty=17179869184 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 20 13:34:07 sampsa-asus bazel[15521]: time="2022-09-20 13:34:07" level=info msg="Processing block batch of size 62 starting from  0x2e9a521d... 1927168/4737468 - estimated time remaining 61h42m38s" blocksPerSecond=12.7 peers=48 prefix=initial-sync
syys 20 13:34:13 sampsa-asus bazel[15521]: time="2022-09-20 13:34:13" level=info msg="Processing block batch of size 63 starting from  0xf9aa31b2... 1927232/4737469 - estimated time remaining 61h42m33s" blocksPerSecond=12.7 peers=50 prefix=initial-sync
syys 20 13:34:16 sampsa-asus bazel[15521]: time="2022-09-20 13:34:16" level=info msg="Ready for The Merge" latestDifficulty=17179869184 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 20 13:34:19 sampsa-asus bazel[15521]: time="2022-09-20 13:34:19" level=info msg="Saved state in DB" prefix=state-gen root=2e9a521d9fc3 slot=1927168
syys 20 13:34:19 sampsa-asus bazel[15521]: time="2022-09-20 13:34:19" level=info msg="Processing block batch of size 63 starting from  0x1e525ff7... 1927296/4737469 - estimated time remaining 61h57m9s" blocksPerSecond=12.6 peers=49 prefix=initial-sync
syys 20 13:34:25 sampsa-asus bazel[15521]: time="2022-09-20 13:34:25" level=info msg="Processing block batch of size 64 starting from  0xf3d4084e... 1927360/4737470 - estimated time remaining 61h57m4s" blocksPerSecond=12.6 peers=48 prefix=initial-sync
syys 20 13:34:26 sampsa-asus bazel[15521]: time="2022-09-20 13:34:26" level=info msg="Ready for The Merge" latestDifficulty=17179869184 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 20 13:34:30 sampsa-asus bazel[15521]: time="2022-09-20 13:34:30" level=info msg="Processing block batch of size 64 starting from  0xdbb42954... 1927424/4737470 - estimated time remaining 61h27m43s" blocksPerSecond=12.7 peers=49 prefix=initial-sync
```

**Comment by prestonvanloon** [comment] 2022-09-20 14:01
Are you running two beacon nodes?

PID 1296 was at 4259808/4728644, very close to the head of the chain. 
And then it seems like you have a second process with PID 15521 that is much farther behind 1920192/4737418.

In any case, I understand the frustration caused by this time remaining estimate. Phase 0 syncs at about 100 blocks per second while Altair or Bellatrix syncs about 10 blocks per second. So the estimated time remaining seems to stay about the same or go up as progress slows. The beacon chain can take 3 to 4 days to sync from genesis.

**Comment by Sreeram1993** [comment] 2022-09-21 06:28
Similar scenarios in my node as well. I have 2 geth archival nodes connected to 2 beacon nodes and both seems to have completed merge. But the geth node seems to be syncing very slowly. PFB the status from both nodes

GETH
node 0 - INFO [09-21|06:25:06.231] Imported new potential chain segment blocks=1 txs=295 mgas=22.221 elapsed=9.974s mgasps=2.228 number=15,559,291 hash=0961a7..1d9571 age=2d21h47m dirty=0.00B
node 1 - INFO [09-21|06:25:07.196] Imported new potential chain segment blocks=1 txs=371 mgas=27.281 elapsed=9.188s mgasps=2.969 number=15,557,806 hash=9b6067..887a31 age=3d2h46m dirty=0.00B

BEACON
node 0 - time="2022-09-21 06:26:27" level=info msg="Processing block batch of size 64 starting from 0xb47a08d1... 4722176/4743130 - estimated time remaining 15m39s" blocksPerSecond=22.3 peers=49 prefix=initial-sync
node 1 - time="2022-09-21 06:25:20" level=info msg="Processing block batch of size 64 starting from 0x2ff82104... 4720690/4743124 - estimated time remaining 29m19s" blocksPerSecond=12.8 peers=45 prefix=initial-sync

The slots in beacon seems to be in sync with the block shown in geth node. Can anyone confirm if this is healthy and our sync is well and good but a bit slow ?

**Comment by elsampsa** [comment] 2022-09-21 19:09
Sorry about the confusion.. It seems I mixed up two different logs: the earlier PID 1296 corresponds to an earlier desperate attempt to run prysm & geth (an older version which I updated) together.  I've cross-checked: there is only one prysm running.

So let's concentrate on that later run (pls dont mind the pid this time: I stopper & restarted the daemon):
```
syys 21 21:01:51 sampsa-asus bazel[27776]: time="2022-09-21 21:01:51" level=info msg="Processing block batch of size 64 starting from  0x6f25dc8d... 2966912/4746907 - estimated time remaining 51h30m16s" blocksPerSecond=9.6 peers=22 prefix=initial-sync
syys 21 21:01:57 sampsa-asus bazel[27776]: time="2022-09-21 21:01:57" level=info msg="Ready for The Merge" latestDifficulty=17179869184 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 21 21:01:58 sampsa-asus bazel[27776]: time="2022-09-21 21:01:58" level=info msg="Processing block batch of size 63 starting from  0x6a113c5b... 2966976/4746907 - estimated time remaining 51h46m20s" blocksPerSecond=9.6 peers=31 prefix=initial-sync
syys 21 21:02:05 sampsa-asus bazel[27776]: time="2022-09-21 21:02:05" level=info msg="Processing block batch of size 63 starting from  0x3405ccf4... 2967104/4746908 - estimated time remaining 52h2m27s" blocksPerSecond=9.5 peers=34 prefix=initial-sync
syys 21 21:02:05 sampsa-asus bazel[27776]: time="2022-09-21 21:02:05" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x25355d8d580c5aef7e6af698a28f46b80cbbc5cf221c1c2239899fe898e5f04b (in processBatchedBlocks, slot=2967104)" prefix=initial-sync
syys 21 21:02:05 sampsa-asus bazel[27776]: time="2022-09-21 21:02:05" level=info msg="Processing block batch of size 63 starting from  0x15aec40b... 2967041/4746908 - estimated time remaining 39h5m0s" blocksPerSecond=12.7 peers=34 prefix=initial-sync
syys 21 21:02:07 sampsa-asus bazel[27776]: time="2022-09-21 21:02:07" level=info msg="Ready for The Merge" latestDifficulty=17179869184 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 21 21:02:12 sampsa-asus bazel[27776]: time="2022-09-21 21:02:12" level=info msg="Processing block batch of size 63 starting from  0x22df6340... 2967168/4746909 - estimated time remaining 39h14m9s" blocksPerSecond=12.6 peers=37 prefix=initial-sync
syys 21 21:02:12 sampsa-asus bazel[27776]: time="2022-09-21 21:02:12" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xda0965de7fb247fc479fea638d2969c023e8177b2dd247824898b350b05f8bfb (in processBatchedBlocks, slot=2967168)" prefix=initial-sync
syys 21 21:02:12 sampsa-asus bazel[27776]: time="2022-09-21 21:02:12" level=info msg="Processing block batch of size 64 starting from  0x126ac151... 2967232/4746909 - estimated time remaining 31h17m17s" blocksPerSecond=15.8 peers=37 prefix=initial-sync
syys 21 21:02:12 sampsa-asus bazel[27776]: time="2022-09-21 21:02:12" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x040e33f8d3a479b20f2f6d54403851155bc43000186922558b4df634f026ded4 (in processBatchedBlocks, slot=2967232)" prefix=initial-sync
syys 21 21:02:12 sampsa-asus bazel[27776]: time="2022-09-21 21:02:12" level=info msg="Processing block batch of size 63 starting from  0x8ffc59f4... 2967296/4746909 - estimated time remaining 26h5m10s" blocksPerSecond=18.9 peers=37 prefix=initial-sync
syys 21 21:02:12 sampsa-asus bazel[27776]: time="2022-09-21 21:02:12" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xe89acb63e13e17bdb73ce00e8db9378708d564d2e5c9bf405019dd3f64d242f6 (in processBatchedBlocks, slot=2967296)" prefix=initial-sync
syys 21 21:02:12 sampsa-asus bazel[27776]: time="2022-09-21 21:02:12" level=info msg="Processing block batch of size 64 starting from  0x1324c511... 2967360/4746909 - estimated time remaining 22h19m0s" blocksPerSecond=22.1 peers=37 prefix=initial-sync
syys 21 21:02:12 sampsa-asus bazel[27776]: time="2022-09-21 21:02:12" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x954cfc514938e8102041fd5a9b2a3f234e35e875f44807dc9653bedcfcf75f20 (in processBatchedBlocks, slot=2967360)" prefix=initial-sync
syys 21 21:02:12 sampsa-asus bazel[27776]: time="2022-09-21 21:02:12" level=info msg="Processing block batch of size 64 starting from  0xc57afba3... 2967424/4746909 - estimated time remaining 19h29m56s" blocksPerSecond=25.4 peers=37 prefix=initial-sync
syys 21 21:02:12 sampsa-asus bazel[27776]: time="2022-09-21 21:02:12" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xf9ffe548d2c448e6161eee962ce287704e4ac920f8a90ec554d25925548bbb22 (in processBatchedBlocks, slot=2967424)" prefix=initial-sync
syys 21 21:02:14 sampsa-asus bazel[27776]: time="2022-09-21 21:02:14" level=info msg="Processing block batch of size 63 starting from  0x3405ccf4... 2967104/4746909 - estimated time remaining 17h20m49s" blocksPerSecond=28.5 peers=37 prefix=initial-sync
syys 21 21:02:17 sampsa-asus bazel[27776]: time="2022-09-21 21:02:17" level=info msg="Ready for The Merge" latestDifficulty=17179869184 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 21 21:02:21 sampsa-asus bazel[27776]: time="2022-09-21 21:02:21" level=info msg="Processing block batch of size 63 starting from  0x641ef762... 2967488/4746909 - estimated time remaining 17h20m35s" blocksPerSecond=28.5 peers=33 prefix=initial-sync
syys 21 21:02:21 sampsa-asus bazel[27776]: time="2022-09-21 21:02:21" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x081e4ecc78796d926e7c58fc060d42c9238dcb4982172530d05f8fb68075b4b9 (in processBatchedBlocks, slot=2967488)" prefix=initial-sync
syys 21 21:02:21 sampsa-asus bazel[27776]: time="2022-09-21 21:02:21" level=info msg="Processing block batch of size 63 starting from  0x2dae1c57... 2967552/4746909 - estimated time remaining 15h36m59s" blocksPerSecond=31.6 peers=33 prefix=initial-sync
syys 21 21:02:21 sampsa-asus bazel[27776]: time="2022-09-21 21:02:21" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x0672215c001155379f187770433bcb913716718f27ae0f7aaecefc4c56ae131c (in processBatchedBlocks, slot=2967552)" prefix=initial-sync
syys 21 21:02:22 sampsa-asus bazel[27776]: time="2022-09-21 21:02:22" level=info msg="Peer summary" activePeers=34 inbound=0 outbound=34 prefix=p2p
syys 21 21:02:24 sampsa-asus bazel[27776]: time="2022-09-21 21:02:24" level=info msg="Processing block batch of size 63 starting from  0x22df6340... 2967168/4746910 - estimated time remaining 14h12m22s" blocksPerSecond=34.8 peers=34 prefix=initial-sync
syys 21 21:02:27 sampsa-asus bazel[27776]: time="2022-09-21 21:02:27" level=info msg="Ready for The Merge" latestDifficulty=17179869184 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 21 21:02:31 sampsa-asus bazel[27776]: time="2022-09-21 21:02:31" level=info msg="Processing block batch of size 64 starting from  0x126ac151... 2967232/4746910 - estimated time remaining 15h35m41s" blocksPerSecond=31.7 peers=36 prefix=initial-sync
syys 21 21:02:37 sampsa-asus bazel[27776]: time="2022-09-21 21:02:37" level=info msg="Ready for The Merge" latestDifficulty=17179869184 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 21 21:02:38 sampsa-asus bazel[27776]: time="2022-09-21 21:02:38" level=info msg="Processing block batch of size 63 starting from  0x8ffc59f4... 2967296/4746911 - estimated time remaining 31h17m13s" blocksPerSecond=15.8 peers=41 prefix=initial-sync
syys 21 21:02:45 sampsa-asus bazel[27776]: time="2022-09-21 21:02:45" level=info msg="Processing block batch of size 64 starting from  0x1324c511... 2967360/4746911 - estimated time remaining 51h45m40s" blocksPerSecond=9.6 peers=42 prefix=initial-sync
syys 21 21:02:47 sampsa-asus bazel[27776]: time="2022-09-21 21:02:47" level=info msg="Ready for The Merge" latestDifficulty=17179869184 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
syys 21 21:02:52 sampsa-asus bazel[27776]: time="2022-09-21 21:02:52" level=info msg="Processing block batch of size 64 starting from  0xc57afba3... 2967424/4746912 - estimated time remaining 51h45m33s" blocksPerSecond=9.6 peers=43 prefix=initial-sync
```

The problem here seems to be that blocks per second is 9.6?

What is the speed of creating new blocks in the beacon chain?  12 bps?

Then I will never catch up, of course.  Why the bps is so slow?

My internet connection is 300mbps.

My laptop has ealier ran at least geth without no problems (a slightly older 8-core penguing with SSD).

The number of peers is quite high.  Could it be a problem?

**Comment by prestonvanloon** [comment] 2022-09-21 19:26
> The problem here seems to be that blocks per second is 9.6?
> 
> What is the speed of creating new blocks in the beacon chain? 12 bps? (bps=as in blocks per second)
> 
> Then I will never catch up, of course. Why the bps is so slow?

A block is produced every 12 seconds. You are syncing at 9 blocks per second, so you will eventually catch up. The bottleneck is likely disk I/O and CPU or memory constraints. That internet connection is sufficient and it seems like you have plenty of peers.

Running multiple instances of beacon chain and geth on the same machine will slow each of them down since they are sharing resources. For Prysm, you could consider using checkpoint sync with a trusted endpoint. https://docs.prylabs.network/docs/prysm-usage/checkpoint-sync

**Comment by elsampsa** [comment] 2022-09-21 21:12
Well, I am _not_ running multiple instances of geth & prysm.  Just one instance of geth (that's at the moment just sitting there, waiting for prysm to sync) and one instance of prysm.

You pointed out that beacon chain produces 0.08 blocks per second.  My client's speed is 9 blocks per second.

What would be an acceptable blocks-per-second speed to sync from scratch within a few days (it's too late & I'm too lazy to do the math, so I just ask for a number instead :) ) .. what is the typical blocks per second _you_ are running in your lab?

**Comment by prestonvanloon** [comment] 2022-09-23 14:53
> Well, I am not running multiple instances of geth & prysm. Just one instance of geth (that's at the moment just sitting there, waiting for prysm to sync) and one instance of prysm.

OK, I was confused why you had two processes originally. One of them was almost entirely synced and the other was about half way. 

> What would be an acceptable blocks-per-second speed to sync from scratch within a few days (it's too late & I'm too lazy to do the math, so I just ask for a number instead :) ) .. what is the typical blocks per second you are running in your lab?

Your results here are typical. The initial sync process is slower in the later phases of the beacon chain. 

Closing this issue now as there doesn't seem to be any technical issues. We are aware that sync slows down over time.

**Closed by prestonvanloon** 2022-09-23 14:53 UTC
Labels: Need-Info
