### ISSUE TITLE
How to debug validator‘s balance decrease

### ISSUE THREAD

**Issue by J1a-wei** [prysmaticlabs/prysm#11697] opened 2022-11-28 09:32 UTC
# 💎 Issue

### Background

I deployed geth+prysm on kubernetes (resources are sufficient). A total of 70 validators are running. But monitoring shows that one or two validators miss att every day.  It will deduct -10320 GWei. statistics show that about 10 validators miss att every week. How should I troubleshoot when I encounter this situation? All logs are normal, not error.

In addition, the monitoring also shows a penalty, although the amount is relatively small, generally -3177. But this penalty is very frequent, among 70 validators, the number of such penalties is about 100 times a week.

### Description

<img width="442" alt="image" src="https://user-images.githubusercontent.com/49090950/204240141-df5445a2-2f1d-4713-9654-28c0c2208b30.png">
-10320

<img width="425" alt="image" src="https://user-images.githubusercontent.com/49090950/204240810-fc94c81d-fee9-4164-bdb3-4e5c2a716311.png">
-3177  

### Reousrces  
- Geth:    4c 32GiB      storage:  EBS-gp2
- Prysm BeaconNode ：  8c 32GiB   storage: EBS-gp2
- Prysm Validator:  4c 8GiB   

#### Geth  
<img width="1855" alt="image" src="https://user-images.githubusercontent.com/49090950/204242008-40fc68ad-b413-4ba0-a8e6-796dda46a85c.png">
<img width="1836" alt="image" src="https://user-images.githubusercontent.com/49090950/204242156-b77c8345-3e91-46f7-a110-af313dc1bbef.png">
<img width="1848" alt="image" src="https://user-images.githubusercontent.com/49090950/204242256-f54edaea-43dc-4b8c-af2f-8ec1db56f828.png">

#### Prysm  BeaconNode
<img width="1847" alt="image" src="https://user-images.githubusercontent.com/49090950/204241713-821affd5-abb1-4d99-a3f7-c59270550d9e.png">

<img width="1834" alt="image" src="https://user-images.githubusercontent.com/49090950/204241788-c009c57b-6e01-4285-a9bc-a726d848fc57.png">

<img width="1858" alt="image" src="https://user-images.githubusercontent.com/49090950/204241859-d2267bd3-de63-49bc-a1ed-11bbf356367d.png">

#### Prysm Validator
<img width="1819" alt="image" src="https://user-images.githubusercontent.com/49090950/204242563-d0c7b66b-a5f3-4531-b157-ffb36a5959eb.png">
<img width="1839" alt="image" src="https://user-images.githubusercontent.com/49090950/204242596-da8ffed7-7f89-46df-87ba-b8a2f742d249.png">
<img width="1806" alt="image" src="https://user-images.githubusercontent.com/49090950/204242667-eadda098-3430-4f9f-aafb-2b732dd67f69.png">

**Any help would be greatly appreciated!**

**Comment by james-prysm** [comment] 2022-11-29 03:23
have you seen anything similar to what was described here? https://github.com/prysmaticlabs/prysm/issues/9913

**Comment by 0xRook1e** [comment] 2022-12-01 03:36
@james-prysm     I found that the CL would log like this about once a day, but it didn't quite match the time we were punished, by many hours. So maybe that's not the cause  
```
level=error msg="Could not handle p2p pubsub" error="could not process block: could not validate new payload: timeout from http.Client: received an undefined ee error" prefix=sync topic="/eth2/4a26c58b/beacon_block/ssz_snappy"
```

**Comment by 0xRook1e** [comment] 2022-12-01 03:45
Geth args 
```
 - command:
    - sh
    - -ac
    - |
      exec geth --authrpc.jwtsecret=/secret/jwtsecret --authrpc.addr=0.0.0.0 --authrpc.port=8551 --authrpc.vhosts=* --http --http.addr=0.0.0.0 --http.port=8599 --http.corsdomain= --http.vhosts=* --http.api=web3,eth,net,engine --nat=extip:$(POD_IP) --port=30303 --ws --ws.addr=0.0.0.0 --ws.port=8546 --ws.origins=* --ws.api=web3,eth,net,engine --datadir=/data/ethereum --ethash.dagdir=/data/ethereum/.ethash --ipcdisable --mainnet "--syncmode=snap" "--cache=12288" "--metrics" "--pprof" "--pprof.addr=0.0.0.0" "--pprof.port=6060"
```

Prysm BeacoNode Args:
```
    - --datadir=/data
    - --rpc-host=0.0.0.0
    - --rpc-port=4000
    - --accept-terms-of-use
    - --config-file=/config/config.yaml
    - --http-web3provider=http://ethereum-mainnet-co6rcodvor33:8551
    - --jwt-secret=/secret/jwtsecret
    - --enable-debug-rpc-endpoints
    - --suggested-fee-recipient=0xCC416b7f92EDd2dC5A5a0aB6D1e060d8298971e3
    - --mainnet
    - --accept-terms-of-use
    - --p2p-max-peers=160
    - --enable-peer-scorer
    - --enable-debug-rpc-endpoints
    - --checkpoint-sync-url=http://ethereum2-mainnet-api:8080/eth/v2/debug/beacon/states/finalized
    - --disable-monitoring
    - --http-mev-relay=http://flashbots-ethereum-mainnet-mev-boost.web3-mev:18550
    - --grpc-gateway-host=0.0.0.0
    - --grpc-gateway-port=8080
```
Prysm Validator Args: 
```
    - --datadir=/data/prysm
    - --accept-terms-of-use
    - --disable-rewards-penalties-logging
    - --disable-account-metrics
    - --mainnet
    - --config-file=/data/config.yaml
    - --validators-external-signer-url=http://web3-signer-mainnet-tls.web3-signer.svc.cluster.local
    - --proposer-settings-file=/data/proposer.json
    - --enable-builder=true
    - --beacon-rpc-provider=ethereum2-mainnet-co6rdwcvfv0o.web3-helm.svc.cluster.local:4000,ethereum2-mainnet-co6reg3uzyc5.web3-helm.svc.cluster.local:4000,ethereum2-mainnet-cnwkcm229tx5.web3-helm.svc.cluster.local:4000
    - --monitoring-port=9090
    - --monitoring-host=0.0.0.0
```

I use web3Signer. It  was deployed  in the same k8s cluster.

**Comment by james-prysm** [comment] 2022-12-02 01:16
`received an undefined ee error` this should mean there was a geth issue , do you see anything there?

**Comment by 0xRook1e** [comment] 2022-12-02 10:28
@james-prysm There is a suspicious log near the punishment  in geth `Checkpoint challenge timed out, dropping id=d084188a45234ec2 conn=dyndial addr=167.235.34.105:31458    `

**Comment by sdalmeida** [comment] 2022-12-05 03:24
Following, as I'm also receiving these messages. 
I managed to bring down the amount of errors by configuring chrony and making sure my clock doesn't drift more than 10ms. While this lowered the amount of missed attestation by a lot, it didn't solve it 100%. 
Both my EL + CL is running on the latest version in docker.

**Comment by james-prysm** [comment] 2022-12-05 16:15
Sorry I don't have a great answer for this yet, but it could be possible that it's related to `Checkpoint challenge timed out`. @0xRook1e do you know if in prysm the response is always `received an undefined ee error` arround the missed attestation? if so there shuold always be an associated log on the execution client side.

**Comment by 0xRook1e** [comment] 2022-12-06 04:41
Dec/1/2022 00:00:00   Dec/6/2022 00:00:00           TimeZone: UTC

### monitor 

(Only statistics greater than 10000+，68 validators were counted)

|Date|ValidaatorCount|
|:---:|:---:| 
|Dec/1/2022 06:09:00|-10300Gwei|
|Dec/1/2022 08:49:00|-10300Gwei|
|Dec/3/2022 15:45:01|-10280Gwei|
|Dec/5/2022 03:10:00|-10280Gwei|
|Dev/5/2022 15:19:00|-10280Gwei|

### validator 



|logDate|logInfo|
|:---:|:---:|
|Dec/5/2022 13:42:50|could not submit signed registrations to beacon node: rpc error: code = InvalidArgument desc = Could not register block builder: could not register validator(s): unsupported error code: 502: did not receive 200 response from API: Builder API validator registration unsuccessful|
|Dec/4/2022 20:13:14| could not submit signed registrations to beacon node: rpc error: code = InvalidArgument desc = Could not register block builder: could not register validator(s): unsupported error code: 502: did not receive 200 response from API: Builder API validator registration unsuccessful|

The validator logs are all caused by the instability of falshbots gateway, which I think has nothing to do with penalties.


### BeaconNode 
error log(sum): 7
warn  log(sum): 0 

|logDate|logInfo|
|:---:|:---:|
|Dec/1/2022 04:23:08|level=error msg="Could not handle p2p pubsub" error="could not process block: could not validate new payload: timeout from http.Client: received an undefined ee error" prefix=sync topic="/eth2/4a26c58b/beacon_block/ssz_snappy"|
|Dec/2/2022 11:01:45|level=error msg="Could not handle p2p pubsub" error="could not process block: could not validate new payload: timeout from http.Client: received an undefined ee error" prefix=sync topic="/eth2/4a26c58b/beacon_block/ssz_snappy"|
|Dec/3/2022 00:31:20|level=error msg="Could not handle p2p pubsub" error="could not process block: could not validate new payload: timeout from http.Client: received an undefined ee error" prefix=sync topic="/eth2/4a26c58b/beacon_block/ssz_snappy"|
|Dec/3/2022 02:40:33|level=error msg="Could not handle p2p pubsub" error="could not process block: could not validate new payload: timeout from http.Client: received an undefined ee error" prefix=sync topic="/eth2/4a26c58b/beacon_block/ssz_snappy"|
|Dec/3/2022 06:43:56|level=error msg="Could not handle p2p pubsub" error="could not process block: could not validate new payload: timeout from http.Client: received an undefined ee error" prefix=sync topic="/eth2/4a26c58b/beacon_block/ssz_snappy"|
|Dec/4/2022 08:19:08|level=error msg="Could not handle p2p pubsub" error="could not process block: could not validate new payload: timeout from http.Client: received an undefined ee error" prefix=sync topic="/eth2/4a26c58b/beacon_block/ssz_snappy"|
|Dec/5/2022 19:57:20|level=error msg="Could not handle p2p pubsub" error="could not process block: could not validate new payload: timeout from http.Client: received an undefined ee error" prefix=sync topic="/eth2/4a26c58b/beacon_block/ssz_snappy"|




### ExecutionNode
error log(sum): 0
warn  log(sum): 44


|logDate|logInfo|
|:---:|:---:|
|Dec/1/2022 20:17:48| Snapshot extension registration failed   peer=7bcee16b err="peer connected on snap without compatible eth support" | 
|Dec/1/2022 20:21:54| Snapshot extension registration failed   peer=7bcee16b err="peer connected on snap without compatible eth support" | 
|Dec/1/2022 20:45:31|  Checkpoint challenge timed out, dropping id=bdfa6602f579b499 conn=dyndial addr=34.202.193.18:30303             type=Geth/v1.10.26-stable... | 
|Dec/1/2022 20:48:05|  Checkpoint challenge timed out, dropping id=fb627f5d906d0b64 conn=dyndial addr=3.80.12.255:30327               type=  | 
|Dec/1/2022 20:52:50|  Snapshot extension registration failed   peer=59d2a329 err="peer connected on snap without compatible eth support"  | 
|Dec/1/2022 20:53:27| Checkpoint challenge timed out, dropping id=1a8f6dc2279f063e conn=dyndial addr=3.225.199.99:30303              type=Geth/v1.10.26-stable...  |
|Dec/1/2022 21:49:03| Checkpoint challenge timed out, dropping id=5970bff24c4defed conn=dyndial addr=3.80.12.255:30766               type=  | 
|Dec/1/2022 21:53:20| Snapshot extension registration failed   peer=ac6f52bd err="peer connected on snap without compatible eth support" | 
|Dec/1/2022 21:54:38| Checkpoint challenge timed out, dropping id=ace2c201cccc0976 conn=dyndial addr=3.80.12.255:30510               type= | 
and so on ...


I only organized the 1st, too many logs not too convenient to organize. All logs are collected by the cloud vendor log collector, there is no log loss.

@james-prysm

**Comment by 0xRook1e** [comment] 2022-12-06 09:05
Dec/1/2022 00:00:00   Dec/6/2022 00:00:00           TimeZone: UTC

### monitor 

(Only statistics greater than 10000+，68 validators were counted)

|Date|ValidaatorCount|
|:---:|:---:| 
|Dec/1/2022 06:09:00|-10300Gwei|
|Dec/1/2022 08:49:00|-10300Gwei|
|Dec/3/2022 15:45:01|-10280Gwei|
|Dec/5/2022 03:10:00|-10280Gwei|
|Dev/5/2022 15:19:00|-10280Gwei|

### validator 



|logDate|logInfo|
|:---:|:---:|
|Dec/5/2022 13:42:50|could not submit signed registrations to beacon node: rpc error: code = InvalidArgument desc = Could not register block builder: could not register validator(s): unsupported error code: 502: did not receive 200 response from API: Builder API validator registration unsuccessful|
|Dec/4/2022 20:13:14| could not submit signed registrations to beacon node: rpc error: code = InvalidArgument desc = Could not register block builder: could not register validator(s): unsupported error code: 502: did not receive 200 response from API: Builder API validator registration unsuccessful|

The validator logs are all caused by the instability of falshbots gateway, which I think has nothing to do with penalties.


### BeaconNode 
error log(sum): 7
warn  log(sum): 0 

|logDate|logInfo|
|:---:|:---:|
|Dec/1/2022 04:23:08|level=error msg="Could not handle p2p pubsub" error="could not process block: could not validate new payload: timeout from http.Client: received an undefined ee error" prefix=sync topic="/eth2/4a26c58b/beacon_block/ssz_snappy"|
|Dec/2/2022 11:01:45|level=error msg="Could not handle p2p pubsub" error="could not process block: could not validate new payload: timeout from http.Client: received an undefined ee error" prefix=sync topic="/eth2/4a26c58b/beacon_block/ssz_snappy"|
|Dec/3/2022 00:31:20|level=error msg="Could not handle p2p pubsub" error="could not process block: could not validate new payload: timeout from http.Client: received an undefined ee error" prefix=sync topic="/eth2/4a26c58b/beacon_block/ssz_snappy"|
|Dec/3/2022 02:40:33|level=error msg="Could not handle p2p pubsub" error="could not process block: could not validate new payload: timeout from http.Client: received an undefined ee error" prefix=sync topic="/eth2/4a26c58b/beacon_block/ssz_snappy"|
|Dec/3/2022 06:43:56|level=error msg="Could not handle p2p pubsub" error="could not process block: could not validate new payload: timeout from http.Client: received an undefined ee error" prefix=sync topic="/eth2/4a26c58b/beacon_block/ssz_snappy"|
|Dec/4/2022 08:19:08|level=error msg="Could not handle p2p pubsub" error="could not process block: could not validate new payload: timeout from http.Client: received an undefined ee error" prefix=sync topic="/eth2/4a26c58b/beacon_block/ssz_snappy"|
|Dec/5/2022 19:57:20|level=error msg="Could not handle p2p pubsub" error="could not process block: could not validate new payload: timeout from http.Client: received an undefined ee error" prefix=sync topic="/eth2/4a26c58b/beacon_block/ssz_snappy"|




### ExecutionNode
error log(sum): 0
warn  log(sum): 44


|logDate|logInfo|
|:---:|:---:|
|Dec/2/2022 04:16:00|Checkpoint challenge timed out, dropping id=2cee3782d734498d conn=dyndial addr=3.80.12.255:30460               type=|
|:---:|:---:|
|Dec/2/2022 04:17:32|Checkpoint challenge timed out, dropping id=bdfa6602f579b499 conn=dyndial addr=34.202.193.18:30303             type=Geth/v1.10.26-stable...|
|Dec/2/2022 12:44:22|Previously seen beacon client is offline. Please ensure it is operational to follow the chain!|
|Dec/2/2022 17:24:20|Checkpoint challenge timed out, dropping id=d084188a45234ec2 conn=dyndial addr=167.235.34.105:31458            type=|
|Dec/2/2022 19:01:45|Ignoring already known beacon payload    number=16,096,692 hash=0513d8..249b28 age=10s|
|Dec/2/2022 21:58:05|Checkpoint challenge timed out, dropping id=1a8f6dc2279f063e conn=dyndial addr=3.225.199.99:30303              type=Geth/v1.10.26-stable...|
|Dec/2/2022 21:59:45|Snapshot extension registration failed   peer=1d4fc8e3 err="peer connected on snap without compatible eth support"|
|Dec/2/2022 22:00:23|Snapshot extension registration failed   peer=1fdbbcbd err="peer connected on snap without compatible eth support"|
|Dec/2/2022 22:02:01|Checkpoint challenge timed out, dropping id=bdfa6602f579b499 conn=dyndial addr=34.202.193.18:30303             type=Geth/v1.10.26-stable...|
|Dec/2/2022 22:03:56|Snapshot extension registration failed   peer=decab1a9 err="peer connected on snap without compatible eth support"|
|Dec/2/2022 22:06:16|Snapshot extension registration failed   peer=35f2159c err="peer connected on snap without compatible eth support"|
|Dec/2/2022 22:07:34|Checkpoint challenge timed out, dropping id=36b443d4f801c752 conn=dyndial addr=3.80.12.255:30361               type=|
|Dec/2/2022 22:07:51| Checkpoint challenge timed out, dropping id=36b48f90c5fa4646 conn=dyndial addr=167.235.34.105:31406            type=|

and so on ...


I only organized the 1st, too many logs not too convenient to organize. All logs are collected by the cloud vendor log collector, there is no log loss.
@james-prysm

**Comment by 0xRook1e** [comment] 2022-12-06 09:06
> Following, as I'm also receiving these messages. I managed to bring down the amount of errors by configuring chrony and making sure my clock doesn't drift more than 10ms. While this lowered the amount of missed attestation by a lot, it didn't solve it 100%. Both my EL + CL is running on the latest version in docker.

Could you share your yaml file?

**Comment by 0xRook1e** [comment] 2022-12-06 09:14
Is it necessary to replace the staking geth node with a better disk, such as nvme, currently geth uses gp2. although iops is sufficient to satisfy, ebs has some network latency.

**Comment by nisdas** [comment] 2022-12-06 09:18
Whats your allocated bandwidth on the machine ? Try running with `--subscribe-all-subnets` , also sometimes missing attestations aren't an issue with your setup. If the block proposer missed their slot (the slot after your attestation), your attestation would take longer to be included on chain or in some cases completely missing.

**Comment by 0xRook1e** [comment] 2022-12-06 09:50
@nisdas Thank you for your advice. Our infrastructure is deployed on aws  . BeaconNode was deployed m5.2xlarge  4c 32GiB 10Gbps .  Geth was deployed r5.xlarge 4c 32GiB  10Gbps. They have exclusive access to this one machine, no other pods are scheduled on.     Also ask what this parameter is for?   Are there any other optimization parameters?

**Comment by 0xRook1e** [comment] 2022-12-08 12:12
@nisdas   We were punished jointly and severally for the situation you mentioned yesterday. There is a verifier 142525 in the network, and the block is not delivered on time in the 5306178 slot. https://mainnet.beaconcha.in/validator/142525#blocks 。 All verifiers who should have been in this slot (5306178) ATT will be punished.  

![532c8bb7-636d-4f3d-a362-a1a0f8d0a111](https://user-images.githubusercontent.com/49090950/206443431-0cd47194-6fa6-4f2e-8f16-8f3d023e8b9c.png)

Btw, how many verifiers are involved in this slot in total and how do I get this data, is it completely random? I want to make a whitelist for our own monitoring, if it is not our reason will no longer alert.

**Comment by 0xRook1e** [comment] 2022-12-09 10:07
One of the verifiers was penalized at 5312006, and after checking the beacon chain logs, there is a gap between the sync time and the browser's, Dec-09-2022 06:41:35 https://beaconcha.in/slot/5312006. But the log I see in the beacon chain is : 
"2022-12-09 06:41:39" level=info msg="Finished applying state transition" attestations=128 payloadHash=0x64b8954c619e prefix=blockchain slot=5312006 syncBitsCount=498 txCount=548

time="2022-12-09 06:41:39" level=info msg="Synced new block" block=0x5698b06e... epoch=166000 finalizedEpoch=165998 finalizedRoot=0xd07eecad... prefix=blockchain slot=5312006

The difference is 4 seconds, but I'm not sure why there is a 4 second difference

**Comment by nisdas** [comment] 2022-12-09 11:39
```
Btw, how many validators are involved in this slot in total and how do I get this data, is it completely random? I want to make a whitelist for our own monitoring, if it is not our reason will no longer alert. If the block should have come out for me, but it didn't due to some kind of failure, is there a corresponding api to check? Appreciated it !
```
Among all committees ? You could just roughly do `total_num_active_validators / 32` to find out the average attesters per slot among all committees.

**Comment by 0xRook1e** [comment] 2022-12-12 02:21
About 60% of all penalties are due to external proposer missed, and I can see from the block browser that the probability of att is 0%. But still 40% is that we did not att on time.

**Comment by okorolov** [comment] 2023-01-02 21:28
Have the same issue, a similar environment with AWS + K8S, and also get random missed attestation. 
Trying to minimize the occurrence. 
@sdalmeida can you please share the chrony configuration you are currently using? 
@0xRook1e did you manage to solve or progress with your investigation? 

Thanks

**Comment by nisdas** [comment] 2023-01-03 00:53
@0xRook1e Another possibility is also very late blocks being included in the canonical chain. Usually that is not the case, but if blocks are late then your attestation could go missing in certain conditions

**Comment by 0xRook1e** [comment] 2023-01-04 07:18
I try to solve it, but am not an expert in this area. Many times I was not sure what the exact cause was, and just did a lot of black box testing, and related monitoring.   @okorolov 

Recently, I connected all the validator and beaconNode Metrics to prometheus. And did monitoring and alerting. The current situation is as follows, we have a total of 122 validators running. We found that when the balance decreases (and we have monitoring for balance decreases), it is not necessarily a miss att (aggr or prop) that occurs. It is suspected that it is not our fault. Of course, if our validator has a miss att (which can be seen by the metrics), the balance must decrease. 

By our phenomenon indicates that there is a miss att of our validators, but this is rare, 122 validators about once or twice a week in total. But we still receive some penalties, which are suspected to be unrelated to us. This is in line with the idea of nisdas @nisdas       
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/49090950/210502172-c16dc265-cf3a-4962-aabf-84657ce9b490.png">


Alert Issue https://github.com/prysmaticlabs/prysm/issues/11102.  I did three kinds of alarm, miss att、 aggr and prop.  


<img width="696" alt="image" src="https://user-images.githubusercontent.com/49090950/210503000-eb8f3e2f-9ea6-4c58-86f9-aa56fa47c377.png">
<img width="957" alt="image" src="https://user-images.githubusercontent.com/49090950/210503054-c08eb670-e375-4915-9d8e-ca56cbcb3943.png">
I will continue to pay attention and learn related knowledge, if there is good related information can be recommended to me, thank you!

**Comment by 0xRook1e** [comment] 2023-01-04 12:35
It's seems beaconNode late. But Idk why it is late.        Relation Issue https://github.com/prysmaticlabs/prysm/issues/11843

**Comment by bert2002** [comment] 2023-04-28 08:23
We have a similar setup and testing in goerli at the moment and can see the same behavior. Did anyone find out why this is happening? Just timing issue or something else?

**Comment by sdalmeida** [comment] 2023-04-28 14:08
@okorolov Sorry for the late reply, I didn't see your message.
I used to run a Cardano validator so I followed this Chrony setup. Just install chrony and use this config: https://github.com/Chris-Graffagnino/Jormungandr-for-Newbs/blob/master/docs/jormungandr_node_setup_guide.md#edit-etcchronychronyconf

To monitor my time skew, I used this Grafana dashboard: https://grafana.com/grafana/dashboards/7496-ntp/

@bert2002 I've brought down my missed attestation to around 1-2 a week by migrating my Beacon Node to an SSD. I also enabled [checkpoint sync](https://docs.prylabs.network/docs/prysm-usage/checkpoint-sync).

**Comment by terencechain** [comment] 2023-08-06 14:31
Closing this discussion. Feel free to reopen or open a new one to continue

**Closed by terencechain** 2023-08-06 14:31 UTC
Labels: Need-Info
