### ISSUE TITLE
Logs in Prysm UI are not the same as the command line

### ISSUE THREAD

**Issue by mrabino1** [prysmaticlabs/prysm#7996] opened 2020-11-30 09:55 UTC
v1.0.1

When you look at the validator logs in the prysm UI they are different than the logs thrown to syslog (for example).. including around which validators are activated.

**Comment by rkapka** [comment] 2020-11-30 15:04
Can you please give a specific example and/or screenshots of the differences?

**Comment by mrabino1** [comment] 2020-11-30 16:10
difficult to do without doxing myself.. summary.. I have more than one validator.. and in the prysm UI log of hte validator.. it shows only one..

**Comment by rauljordan** [comment] 2020-12-02 15:39
Duplicate of https://github.com/prysmaticlabs/prysm-web-ui/issues/94, please track that one for a resolution

**Closed by rauljordan** 2020-12-02 15:39 UTC
