### ISSUE TITLE
ValidatorPerformance RPC returns more public keys than requested

### ISSUE THREAD

**Issue by tsudmi** [prysmaticlabs/prysm#4307] opened 2019-12-17 18:46 UTC
Hi,

Looks like [ValidatorPerfomance](https://github.com/prysmaticlabs/prysm/blob/master/proto/beacon/rpc/v1/services.proto#L29) RPC can return more balances back than the number of public keys requested:

```python
# public keys are unique
request = services_pb2.ValidatorPerformanceRequest(public_keys=public_keys)
response = stub.ValidatorPerformance(request)
if len(response.balances) != len(public_keys):
   # raises ValueError: Requested 10 balances, got 11
    raise ValueError(f'Requested {len(public_keys)} balances, got {len(response.balances)}')
```

**Comment by rauljordan** [comment] 2019-12-26 18:05
Hi @tsudmi can you paste in here the public keys you're requesting so we can reproduce? I believe this is caused by a bug in our testnet where a multiple validators can have the same public key. This will be resolved in our v0.9.3 relaunch of our testnet coming up in January, so would be good to confirm this soon.

**Comment by tsudmi** [comment] 2019-12-27 10:14
Hi @rauljordan ,
I'm running a private network, so the public keys I'm using are not used in a public testnet.
Can you please send a link to this bug? I could try testing from the commit it was fixed in.

**Comment by rauljordan** [comment] 2020-01-02 17:32
Hey @tsudmi try the branch v0.9.2 on commit [5da81125e48387f17699ad3fdfa6f1faf733bb5e](https://github.com/prysmaticlabs/prysm/pull/4154/commits/5da81125e48387f17699ad3fdfa6f1faf733bb5e). The branch has a TON of huge breaking changes which wont go live until our upcoming testnet restart this January, but if it works for you hopefully it will resolve your bug.

**Comment by rauljordan** [comment] 2020-01-02 17:33
Fairly confident this has to do with a known bug regarding multiple validators having the same public key, but curious to see what results you get

**Comment by rauljordan** [comment] 2020-01-17 20:40
Closing this as it has gone stale. If this happens on current master for you please let us know and we can re-open @tsudmi

**Closed by rauljordan** 2020-01-17 20:40 UTC
Labels: Bug
