### ISSUE TITLE
Tests Fail With Race Detection

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#377] opened 2018-08-04 14:48 UTC
```text
bazel test //... --features=race
```
Results
```text
INFO: Build completed, 3 tests FAILED, 4 total actions
//beacon-chain/blockchain:go_default_test                       (cached) PASSED in 0.0s
//beacon-chain/node:go_default_test                             (cached) PASSED in 0.1s
//beacon-chain/powchain:go_default_test                         (cached) PASSED in 0.1s
//beacon-chain/rpc:go_default_test                              (cached) PASSED in 0.3s
//beacon-chain/simulator:go_default_test                        (cached) PASSED in 0.0s
//beacon-chain/sync:go_default_test                             (cached) PASSED in 0.0s
//beacon-chain/utils:go_default_test                            (cached) PASSED in 0.1s
//client/attester:go_default_test                               (cached) PASSED in 0.1s
//client/contracts:go_default_test                              (cached) PASSED in 0.1s
//client/mainchain:go_default_test                              (cached) PASSED in 0.3s
//client/node:go_default_test                                   (cached) PASSED in 0.1s
//client/observer:go_default_test                               (cached) PASSED in 0.1s
//client/params:go_default_test                                 (cached) PASSED in 0.1s
//client/rpcclient:go_default_test                              (cached) PASSED in 0.3s
//client/syncer:go_default_test                                 (cached) PASSED in 0.1s
//client/txpool:go_default_test                                 (cached) PASSED in 0.0s
//client/types:go_default_test                                  (cached) PASSED in 0.1s
//contracts:go_default_test                                     (cached) PASSED in 0.1s
//shared:go_default_test                                        (cached) PASSED in 0.3s
//shared/cmd:go_default_test                                    (cached) PASSED in 0.1s
//shared/database:go_default_test                               (cached) PASSED in 0.5s
//shared/p2p:go_feed_concurrent_write_test                      (cached) PASSED in 0.0s
//client/proposer:go_default_test                                        FAILED in 3.7s
  /home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/execroot/__main__/bazel-out/k8-fastbuild/testlogs/client/proposer/go_default_test/test.log
//client/simulator:go_default_test                                       FAILED in 0.7s
  /home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/execroot/__main__/bazel-out/k8-fastbuild/testlogs/client/simulator/go_default_test/test.log
//shared/p2p:go_default_test                                             FAILED in 1.3s
  /home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/execroot/__main__/bazel-out/k8-fastbuild/testlogs/shared/p2p/go_default_test/test.log
```

This is likely due to some p2p issues where the tests are attempting discovery.

**Comment by terenc3t** [comment] 2018-08-06 15:12
Assigned to @fgimenez

**Comment by IvanTheGreatDev** [comment] 2018-08-17 06:48
Is there more work needed on this?

**Comment by nisdas** [comment] 2018-08-17 06:50
Yeah there are a few more race conditions to fix. I think @fgimenez is working on fixing the remaining conditions.

**Comment by fgimenez** [comment] 2018-08-17 07:40
> I think @fgimenez is working on fixing the remaining conditions.

Not really, currently there's only one remaining data race in `shared/p2p`, but we can't fix it because it is caused by a third-party library, see https://github.com/prysmaticlabs/prysm/pull/390#issuecomment-412415378.

We had some issues recently regarding tests that fail on travis with the race detector enabled, but these seem to be related to travis execution environment (the failure is not from the race detector and they don't fail locally). 

I'm starting looking into #282, hopefully with a remote bazel worker we can have more data to determine if the current problem is actually related to travis. I'll keep you posted.

**Closed** 2018-08-17 14:36 UTC
Labels: Bug, Good First Issue, Help Wanted, Intermediate
