### ISSUE TITLE
Beacon-chain failed to start prior to Spadina genesis

### ISSUE THREAD

**Issue by KevinVitale** [prysmaticlabs/prysm#7356] opened 2020-09-27 16:54 UTC
# 🐞 Bug Report

### Description

I experienced an issue with the `beacon-chain` where it failed to start prior to Spadina genesis. I'm using Docker Compose and I restarted my `beacon-chain`, `validator`, and `slasher` services.

A snippet of the logs is as follows:

<pre><code>
time="2020-09-27 16:25:27" level=info msg="Connected to eth1 proof-of-work chain" endpoint="/root/.ethereum/geth.ipc" prefix=powchain
time="2020-09-27 16:25:27" level=info msg="Blockchain data already exists in DB, initializing..." prefix=blockchain
time="2020-09-27 16:25:27" level=info msg="Genesis time has not arrived - not syncing" genesisTime=2020-09-29 12:00:13 +0000 UTC prefix=initial-sync
time="2020-09-27 16:25:27" level=fatal msg="Could not set up chain info: finalized state and block can't be nil" prefix=blockchain
</code></pre>

Prior to restarting my beacon-chain, I saw this in the logs:
`time="2020-09-27 16:11:25" level=info msg="Currently waiting for chainstart" Extra validators needed=0 Time till minimum genesis=4m47s prefix=powchain`

To fix this issue and get the `beacon-chain` up and running again, I removed its data directory (`rm -fr beaconchaindata`).

### Has this worked before in a previous version?

Yes.

## 🔬 Minimal Reproduction

Not sure. I did `docker-compose pull` and noticed that only the `validator` Docker image needed to be updated. My `validator` service depends on my `beacon-chain`, so when I did `docker-compose up -d --force validator`, the `beacon-chain` was restarted as well. That's when the `beacon-chain` failed to start, with a `fatal` error.

## 🔥 Error

<pre><code>
time="2020-09-27 16:25:27" level=info msg="Connected to eth1 proof-of-work chain" endpoint="/root/.ethereum/geth.ipc" prefix=powchain
time="2020-09-27 16:25:27" level=info msg="Blockchain data already exists in DB, initializing..." prefix=blockchain
time="2020-09-27 16:25:27" level=info msg="Genesis time has not arrived - not syncing" genesisTime=2020-09-29 12:00:13 +0000 UTC prefix=initial-sync
time="2020-09-27 16:25:27" level=fatal msg="Could not set up chain info: finalized state and block can't be nil" prefix=blockchain
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04.1 LTS
Linux 5.4.0-48-generic
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Prysm/v1.0.0-alpha.26/c0c34f3d3a05705e1c553912bc78fcc44c1abe87
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment] 2020-09-27 17:03
Tentatively assigning to @terencechain since they introduced this code.

I was able to reproduce by restarted the node between the time the genesis state was determined and the start of genesis.

**Closed** 2020-09-27 21:09 UTC
Labels: Bug, Priority: Critical

**Comment by ChuckNorrison** [comment] 2020-09-29 12:24
hi my validators do not attest cause of this...

**Comment by nisdas** [comment] 2020-09-29 12:31
@ChuckNorrison 
Please ask us here
https://discord.gg/UE4GWu
