### ISSUE TITLE
Bad Genesis State Due To Active Validator Count Cache

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#6291] opened 2020-06-17 11:17 UTC
# 🐞 Bug Report

### Description

Due to the Active Validator Count Cache being introduced in #6254, this unfortunately leads
to invalid genesis states in restarts. The cache stores a single value for a fixed seed, however
in genesis when we have constant stream of genesis deposits coming in, this stored value will more than often be wrong. The seed doesn't change but the active count does. 

### Has this worked before in a previous version?

Yes before #6254 

## 🔬 Minimal Reproduction

Run a node with an empty db and sync a few deposits before the `min_genesis_validator` count. Then restart the node, after a while the node will not derive the correct genesis state. 

## 🔥 Error

Incorrect active validator count derived from the cache leads to incorrect genesis event being determined.

## 🌍  Your Environment

Ubunutu 18.04.4 LTS

**What version of Prysm are you running? (Which release)**

4740f7ed57490a5a38601a1e66cb8a66f0a6df50

**Anything else relevant (validator index / public key)?**

**Comment by terencechain** [comment] 2020-06-17 14:34
Reproduced:
```
[2020-06-17 07:31:39]  INFO powchain: Processing deposits from Ethereum 1 chain deposits=4608 genesisValidators=4248
[2020-06-17 07:31:40]  INFO powchain: Processing deposits from Ethereum 1 chain deposits=5120 genesisValidators=4248
[2020-06-17 07:31:43]  INFO powchain: Processing deposits from Ethereum 1 chain deposits=5632 genesisValidators=4248
[2020-06-17 07:31:47]  INFO powchain: Processing deposits from Ethereum 1 chain deposits=6144 genesisValidators=4248
```
Marking this as medium since there's a clear guide line how not to reproduce this bug; don't restart beacon node will it's processing deposits before genesis. It's a good 2 mins window. I'll look into this today/tomorrow

**Closed** 2020-06-18 00:48 UTC
Labels: Bug, Priority: Medium
