### ISSUE TITLE
Lower eth1HeaderReqLimit

### ISSUE THREAD

**Issue by mbucci** [prysmaticlabs/prysm#7857] opened 2020-11-18 22:20 UTC
# 🐞 Bug Report

### Description

Given an `eth1HeaderReqLimit` of 1000 it's very easy for log processing to exceed the get_Logs limit of some common web3 providers (e.g. infura limits at 10,000). I believe these types of web3 providers will be a common alternative to running one's own eth1 node. 

### Has this worked before in a previous version?

Wasn't as much of an issue when running a Medalla beacon-chain node

## 🔬 Minimal Reproduction

Run a Pyrmont beacon-chain node with a Infura or similar web3-http-provider

## 🔥 Error

<pre><code>
time="2020-11-18 17:33:24" level=error msg="Unable to process past logs query returned more than 10000 results" prefix=powchain

time="2020-11-18 22:11:48" level=error msg="Could not connect to powchain endpoint" error="could not dial eth1 nodes: 429 Too Many Requests: {"jsonrpc":"2.0","id":1,"error":{"code":-32005,"message":"daily request count exceeded, request rate limited","data":{"rate":{"allowed_rps":1,"backoff_seconds":27,"current_rps":1.1333333333333333},"see":"https://infura.io/dashboard"}}}" prefix=powchain
</code></pre>

**What version of Prysm are you running? (Which release)**

<pre>
v1.0.0-beta.3
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment] 2020-11-18 22:35
Duplicate of #7827

**Closed by prestonvanloon** 2020-11-18 22:35 UTC
