### ISSUE TITLE
Validator data base64 encoded response

### ISSUE THREAD

**Issue by olegshmuelov** [prysmaticlabs/prysm#10068] opened 2022-01-09 14:25 UTC
using the last Prysm v2.0.5

in some cases when requesting validators data `eth/v1/beacon/states/head/validators`
the response data is base64 encoded instead of hex encoded

for example:
`eth/v1/beacon/states/head/validators?id=0x93266152b568d5587878f3590f30ff7e8f1d49cc85a2d71f66ef03efe7527227269b108fac399bb9cce9877845caf829`

response:
```
{
    "data": [
        {
            "index": "212591",
            "balance": "32549533271",
            "status": "ACTIVE_ONGOING",
            "validator": {
                "pubkey": "kyZhUrVo1Vh4ePNZDzD/fo8dScyFotcfZu8D7+dScicmmxCPrDmbuczph3hFyvgp",
                "withdrawal_credentials": "AKNtz2NgvVymHo3rFuKSP1hthz6Z5xhnCed1tWfSHHg=",
                "effective_balance": "32000000000",
                "slashed": false,
                "activation_eligibility_epoch": "20651",
                "activation_epoch": "20658",
                "exit_epoch": "18446744073709551615",
                "withdrawable_epoch": "18446744073709551615"
            }
        }
    ]
}
```
desired response:
```
{
    "data": [
        {
            "index": "212591",
            "balance": "32558754429",
            "status": "active_ongoing",
            "validator": {
                "pubkey": "0x93266152b568d5587878f3590f30ff7e8f1d49cc85a2d71f66ef03efe7527227269b108fac399bb9cce9877845caf829",
                "withdrawal_credentials": "0x00a36dcf6360bd5ca61e8deb16e2923f586d873e99e7186709e775b567d21c78",
                "effective_balance": "32000000000",
                "slashed": false,
                "activation_eligibility_epoch": "20651",
                "activation_epoch": "20658",
                "exit_epoch": "18446744073709551615",
                "withdrawable_epoch": "18446744073709551615"
            }
        }
    ]
}
```

also in some cases getting an error message not related to the passed validator id:
```
{
    "message": "Invalid validator ID: could not decode validator id 'b85f43305dcd7f90355b2e1bf6ee621501ecb7afdc268fdc10f64a17b6a5f06daf881068d9725a3f4f6f30f98db50cd3': strconv.ParseUint: parsing \"b85f43305dcd7f90355b2e1bf6ee621501ecb7afdc268fdc10f64a17b6a5f06daf881068d9725a3f4f6f30f98db50cd3\": invalid syntax",
    "code": 200
}
```

the issue can't be reproduced on previous versions <v2.0.5

**Comment by rkapka** [comment] 2022-01-11 14:36
Hi @olegshmuelov , thanks for the report.

> the response data is base64 encoded instead of hex encoded

Does this always happen for the mentioned validator? I tried to reproduce it, but couldn't.

> also in some cases getting an error message not related to the passed validator id

This is expected. The spec (https://ethereum.github.io/beacon-APIs/#/Beacon/getStateValidator) says "Either hex encoded public key **(with 0x prefix)** or validator index". You need the `0x` prefix.

**Comment by olegshmuelov** [comment] 2022-01-11 14:52
Hi @rkapka, thanks for the reply.

> Does this always happen for the mentioned validator? I tried to reproduce it, but couldn't.

not always, could not find the steps to reproduce the issue. But it's happening for other validators as well. 

> This is expected. The spec (https://ethereum.github.io/beacon-APIs/#/Beacon/getStateValidator) says "Either hex encoded public key (with 0x prefix) or validator index". You need the 0x prefix.

You are right. The issue is that after requesting without 0x prefix, the error message still exist for the upcoming proper requests (with 0x prefix) and no validator data returned but error message with status code 200.

steps to reproduce:
1. GET `eth/v1/beacon/states/head/validators?id=93266152b568d5587878f3590f30ff7e8f1d49cc85a2d71f66ef03efe7527227269b108fac399bb9cce9877845caf829`

```
{
    "message": "Invalid validator ID: could not decode validator id '93266152b568d5587878f3590f30ff7e8f1d49cc85a2d71f66ef03efe7527227269b108fac399bb9cce9877845caf829': strconv.ParseUint: parsing \"93266152b568d5587878f3590f30ff7e8f1d49cc85a2d71f66ef03efe7527227269b108fac399bb9cce9877845caf829\": invalid syntax",
    "code": 400
}
```
2. GET `eth/v1/beacon/states/head/validators?id=0x93266152b568d5587878f3590f30ff7e8f1d49cc85a2d71f66ef03efe7527227269b108fac399bb9cce9877845caf829`
```
{
    "message": "Invalid validator ID: could not decode validator id '93266152b568d5587878f3590f30ff7e8f1d49cc85a2d71f66ef03efe7527227269b108fac399bb9cce9877845caf829': strconv.ParseUint: parsing \"93266152b568d5587878f3590f30ff7e8f1d49cc85a2d71f66ef03efe7527227269b108fac399bb9cce9877845caf829\": invalid syntax",
    "code": 200
}
```

**Comment by rkapka** [comment] 2022-01-13 10:04
Fixed by #10076

**Comment by rkapka** [comment] 2022-01-13 10:05
Reopening because the mentioned PR fixes only a part of the issue.

**Comment by rkapka** [comment] 2022-01-13 10:06
> You are right. The issue is that after requesting without 0x prefix, the error message still exist for the upcoming proper requests (with 0x prefix) and no validator data returned but error message with status code 200.

This is fixed as mentioned above.

**Comment by Ucodia** [comment] 2022-01-31 21:41
> Reopening because the mentioned PR fixes only a part of the issue.

@rkapka Do you still need steps to reproduce in order to look into this issue?

**Comment by rauljordan** [comment] 2022-03-07 19:05
Hi @rkapka and @olegshmuelov is this still an issue?

**Comment by olegshmuelov** [comment] 2022-03-08 12:09
> Hi @rkapka and @olegshmuelov is this still an issue?

Since the latest version, didn't face with this issue anymore
I think we can close it.

**Closed** 2022-03-08 18:15 UTC
Labels: Bug, API
