### ISSUE TITLE
Shapella Hard Fork - Beacon Chain Event Types

### ISSUE THREAD

**Issue by hossein-bitgo** [prysmaticlabs/prysm#11966] opened 2023-02-02 19:45 UTC
# 💎 Question

### Background

The Shapella Hard Fork will finally enable the withdrawal capability from validators. Withdrawal happens in two forms: (1) voluntary full withdrawal (2) excess balance withdrawal (over 32 ETH). The issue I wanted to discuss was potential conflicts with slashing since that is currently an event type on the on the beacon chain that signifies a reduced balance and leads to exiting. 
### Description

To summarize we have 3 cases that lead to a reduced balance:
1) voluntary full withdrawal where the user unstakes and retrieves all funds + rewards. Leads to exiting.
2) an automatic withdraw when the user takes no action after the upgrade. Excess balance (over 32 eth) is automatically returned. Validator remains active.
3) slashing when there is a violation in attestation. Penalty is applied in balance and leads to exiting. Full withdrawal becomes available afterwards.

Will there be event types to help distinguish these three scenarios for validators and the transactions that reduce their balances on the beacon chain? If so what are they and how can I learn more information/documentation on how to view these on the beacon chain.

References:
[https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/validator.md#enabling-validator-withdrawals](https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/validator.md#enabling-validator-withdrawals)

[https://github.com/ethereum/consensus-specs/blob/f2eb5e38e2ad651afe1d55eece2e3d28260c2b4a/specs/phase0/beacon-chain.md#beacon-operations](https://github.com/ethereum/consensus-specs/blob/f2eb5e38e2ad651afe1d55eece2e3d28260c2b4a/specs/phase0/beacon-chain.md#beacon-operations)

[https://www.attestant.io/posts/understanding-the-validator-lifecycle/](https://www.attestant.io/posts/understanding-the-validator-lifecycle/)

**Comment by james-prysm** [comment] 2023-02-02 21:01
we'll have a doc up soon that will answer these questions and more. I can respond with a link once we have this published.
The short answer to the questions:
the process of withdrawals requires a new action to change the withdrawal_credentials field to a value that starts with 0x01 and ends with an execution address, we will be providing the tools and guidance for this action.
Once the withdrawal credentials are changed validator balances over 32 eth will be automatically withdrawn 16 validators at a time each block, and not the complete validator set.
Validators that are fully exited and have their withdrawal address set will be fully withdrawn, again part of the same 16 validators that can withdraw block.
validators that have been slashed can also be withdrawn for whatever remains above 0 Eth given that they are fully exited. 
If the validator is not in an exited status either being in a sync committee or slashed there may be a delay.

I hope this answers your questions.
for now until we publish the full document https://notes.ethereum.org/@launchpad/withdrawals-faq has some useful information.

**Comment by hossein-bitgo** [comment] 2023-02-02 23:19
Thank you for your response! Looking forward to the full discussion whenever it gets published. Just to re-iterate the question and make sure I got the right understanding from your response, I am trying to see if there are any events or APIs on the beacon chain that check rewards, slashes and withdrawals. Do these currently exist? If so, would you happen to know where and if not is there any other support to achieve this?

**Comment by james-prysm** [comment] 2023-02-03 00:00
Perhaps I misunderstood your question, can you direct me to what you meant by event types? Rereading the question it sounds like you'd want some kind of report API that specifies balance changes and the cause of the balance change? ( if that's the question then there are no API endpoints that support it, and you'd have to build your own utilizing the beacon APIs https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/)
The beacon API will only have a new endpoint to check if your withdrawal credential change is in the waiting room so to speak. If this is a question around Execution APIs(json-rpc) I'd be less familiar. the consensus client notifies the execution client via the execution engine APIs and will contain a list of withdrawal messages for the execution client to process https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#executionpayload

I'm not sure if that answers your question though

**Comment by hossein-bitgo** [comment] 2023-02-03 00:43
Yes exactly, I am looking for a way to identify the cause of the balance change once it occurs. I was hoping an API was available for this. So by event types I meant the events that trigger this balance change, namely the voluntary withdrawal, the automatic withdrawal and a slash. I assume there must be a field somewhere in the beacon chain that will show the cause of the balance change? You mentioned no API exists for this but we can build it using beacon chain APIs? Can you be more specific about what you mean by that? It won't be hard to create the API ourselves but I just have no idea where to look on the beacon chain to find these causes. If you can point me in the right direction for that I'd really appreciate it!

**Comment by james-prysm** [comment] 2023-02-03 03:51
you have acess to the validator balances, beacon chain state, and validator state at specific slots you know are finalized
https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/ there is information on the current balance, you can check the pervious balance and check previous state changes.

**Comment by hossein-bitgo** [comment] 2023-02-03 04:39
And in terms of the state and state changes will there be new additional states? 
By that I mean additional ones compared to what is listed here [https://www.attestant.io/posts/understanding-the-validator-lifecycle/](https://www.attestant.io/posts/understanding-the-validator-lifecycle/)
- deposited
- pending
- active
- exiting
- slashing
- exited
I assume something will be introduced for withdrawals?

**Comment by james-prysm** [comment] 2023-02-03 15:39
these "states" are not organized how you may think, it's not marked on the validator state like a tag like type: "withdrawn" or something like that... for withdrawals you'll see the withdraw credential change meaning it has begun the withdrawal process, full withdrawal is only when the validator is both exited as well as having the withdrawal credentials set.

**Comment by james-prysm** [comment] 2023-02-03 20:26
preview of document found here https://github.com/prysmaticlabs/documentation/pull/702 and preview site https://deploy-preview-702--prysmdocs.netlify.app/docs/wallet/withdraw-validator. closing this issue for now.

**Closed by james-prysm** 2023-02-03 20:26 UTC
