### ISSUE TITLE
gRPC error on validator status request

### ISSUE THREAD

**Issue by tsudmi** [prysmaticlabs/prysm#4056] opened 2019-11-19 20:05 UTC
Hi,

I've created a deposit which was successfully received by the beacon node:
```
level=debug msg="Deposit registered from deposit contract" merkleTreeIndex=64 prefix=powchain publicKey=0x0
```
However, validator client cannot get out from them `UNKNOWN_STATUS` for quite some time.
If I fetch validator status directly from the beacon node, I get following response:
```
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "grpc: error unmarshalling request: proto: wrong wireType = 2 for field Slot"
	debug_error_string = "{"created":"@1574192798.596550462","description":"Error received from peer ipv4:10.10.10.23:4000","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"grpc: error unmarshalling request: proto: wrong wireType = 2 for field Slot","grpc_status":13}"
```
This happens randomly and repeats for all the future deposits.

**Comment by prestonvanloon** [comment] 2019-11-20 05:14
How can we reproduce this error? There haven't been proto changes to validator status RPC since #3935, so I'm not sure how you are getting wrong wire type during unmarshalling.

**Comment by rauljordan** [comment] 2019-11-20 05:24
+1 what image / version was used to cause this? Seems like an out of date version

**Comment by tsudmi** [comment] 2019-11-20 12:31
@prestonvanloon The issue seems to occur if the beacon node restarts after the chain started. The genesis validators will reestablish the connection and continue running normally, but the new validator nodes will be stuck in the `unknown` state. It could be that they went successfully through the activation process, but the validator client fails to fetch the new state. This happens to me not the first time, wrote about it on discord some time ago.

 @rauljordan  I've pulled the latest docker images yesterday for both validator and beacon chain.

**Comment by prestonvanloon** [comment] 2019-11-20 17:34
There might be two issues here. 

The first issue you describe about getting in unknown state after restart should have been resolved in #4032. Can you confirm that your running a git commit after 13207a9de5f7b5f499d96f50eea1bda5e9f7d31f? 

The second issue, is this python? How did you compile the protos? Can you share the code?

**Comment by rauljordan** [comment] 2019-11-25 16:19
Bump on this @tsudmi - do you have more info on the failure? It seems to be this is due to running an old, incompatible version of the API

**Comment by tsudmi** [comment] 2019-11-26 21:52
Sorry for the delayed reply.

I was running following versions:
```
beacon-chain version Git commit: 7a22e98c0f715d27a64680dcfd47e769d2306d61. Built at: 2019-11-19 19:39:54+00:00
validator version Git commit: 7a22e98c0f715d27a64680dcfd47e769d2306d61. Built at: 2019-11-19 19:37:43+00:00
```
@prestonvanloon the commit is after `13207a9`.

For protos, I use [python grpc](https://grpc.io/docs/quickstart/python/). The example compile command is the following:
```
python -m grpc_tools.protoc -I. -I$HOME/googleapis --python_out=. --grpc_python_out=. ./eth/v1alpha1/validator.proto
```
I haven't pulled new images since then. I will try to do that during the week and see whether I can still reproduce that.

**Comment by prestonvanloon** [comment] 2019-11-27 23:30
@tsudmi what was the call you were trying to make?

**Comment by tsudmi** [comment] 2019-11-30 13:12
@prestonvanloon I was calling [ValidatorStatus](https://github.com/prysmaticlabs/prysm/blob/master/proto/beacon/rpc/v1/services.proto#L28).
The call usually works, so that's not something that is causing the problem.

**Comment by rauljordan** [comment] 2019-12-03 19:10
Hey @tsudmi can you share the code you used for this? We are having trouble reproducing and would love to get this resolved soon

**Comment by tsudmi** [comment] 2019-12-03 20:57
@rauljordan The problem was not the way I was calling RPC endpoints, but the sequence of actions (chain start, beacon node restart, new validator registered) which leaded beacon node to the state when it was not activating new validators anymore.

However, it looks like recent commits have fixed it as I'm not able to bring the beacon node to that state anymore. We could close this issue for now and I will reopen it again if that problem still exists.

**Comment by rauljordan** [comment] 2019-12-03 21:00
Great, let us know if this pops up again - happy to help

**Closed by rauljordan** 2019-12-03 21:00 UTC
Labels: API
