### ISSUE TITLE
Some output from beacone node dying

### ISSUE THREAD

**Issue by clabornd** [prysmaticlabs/prysm#4807] opened 2020-02-09 18:37 UTC
Dunno what it means, but here's the output from the beacon node and validator, hope it helps.

Running on Ubuntu 16.04 LTS with docker containers.  Died after about 3 days.  Was restarted from an address that had been inactive for a while, and I was basically only getting negative %change in balance for the duration of it successfully running.

**Beacon Node**:

`goroutine 16215307 [semacquire, 121 minutes]:
sync.runtime_SemacquireMutex(0x2883cb4, 0x0, 0x1)
	GOROOT/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0x2883cb0)
	GOROOT/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	GOROOT/src/sync/mutex.go:81
sync.(*RWMutex).Lock(0x2883cb0)
	GOROOT/src/sync/rwmutex.go:98 +0x97
github.com/prysmaticlabs/prysm/shared/stateutil.(*stateRootHasher).arraysRoot(0xc0000100a0, 0xc0136ae000, 0x2000, 0x2000, 0x2000, 0x18119b1, 0xa, 0x0, 0x0, 0x0, ...)
	shared/stateutil/arrays.go:30 +0x66
github.com/prysmaticlabs/prysm/shared/stateutil.(*stateRootHasher).computeFieldRoots(0xc0000100a0, 0xc053f93800, 0x7fe9d06e1008, 0x0, 0x2853dbc109a3df5c, 0x6785dadac401327, 0x702cecc05395d8a)
	shared/stateutil/state_root.go:113 +0x40d
github.com/prysmaticlabs/prysm/shared/stateutil.ComputeFieldRoots(0xc053f93800, 0x16f5500, 0xc0503af980, 0x15ec640, 0x28838b0, 0xc0138095c8)
	shared/stateutil/state_root.go:56 +0xb6
github.com/prysmaticlabs/prysm/beacon-chain/state.(*BeaconState).HashTreeRoot(0xc159d9e500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	beacon-chain/state/types.go:123 +0xdc
github.com/prysmaticlabs/prysm/beacon-chain/core/state.ProcessSlot(0x1bb8ee0, 0xc0503af950, 0xc159d9e500, 0x0, 0x0, 0x0)
	beacon-chain/core/state/transition.go:201 +0x1a4
github.com/prysmaticlabs/prysm/beacon-chain/core/state.ProcessSlots(0x1bb8ee0, 0xc0503af950, 0xc159d9e500, 0x356a0, 0x0, 0x0, 0x0)
	beacon-chain/core/state/transition.go:299 +0x382
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).validateAggregatedAtt(0xc005132000, 0x1bb8ee0, 0xc0503af890, 0xc1389365a0, 0x0)
	beacon-chain/sync/validate_aggregate_proof.go:100 +0x740
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).validateAggregateAndProof(0xc005132000, 0x1bb8ee0, 0xc0503af800, 0xc01aa2fec0, 0x27, 0xc0c59591d0, 0x0)
	beacon-chain/sync/validate_aggregate_proof.go:62 +0x3e6
github.com/prysmaticlabs/prysm/beacon-chain/sync.wrapAndReportValidation.func1(0x1bb8ea0, 0xc00f9f9a40, 0xc01aa2fec0, 0x27, 0xc0c59591d0, 0xc00f188900)
	beacon-chain/sync/subscriber.go:184 +0x1c0
github.com/libp2p/go-libp2p-pubsub.(*topicVal).validateMsg(0xc007ae2de0, 0x1bb8e20, 0xc000082840, 0xc01aa2fec0, 0x27, 0xc0c59591d0, 0x0)
	external/com_github_libp2p_go_libp2p_pubsub/validation.go:335 +0x8a
github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic(0xc0005fc870, 0xc007ae2de0, 0xc01aa2fec0, 0x27, 0xc0c59591d0, 0xfc4c5f)
	external/com_github_libp2p_go_libp2p_pubsub/validation.go:316 +0x18d
github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic(0xc0005fc870, 0xc083f116d8, 0x1, 0x1, 0xc01aa2fec0, 0x27, 0xc0c59591d0, 0x10000c004fb8f00)
	external/com_github_libp2p_go_libp2p_pubsub/validation.go:269 +0x3c8
github.com/libp2p/go-libp2p-pubsub.(*validation).doValidateTopic(0xc0005fc870, 0xc083f116d8, 0x1, 0x1, 0xc01aa2fec0, 0x27, 0xc0c59591d0)
	external/com_github_libp2p_go_libp2p_pubsub/validation.go:258 +0x74
github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1(0xc0005fc870, 0xc083f116d8, 0x1, 0x1, 0xc01aa2fec0, 0x27, 0xc0c59591d0)
	external/com_github_libp2p_go_libp2p_pubsub/validation.go:233 +0x67
created by github.com/libp2p/go-libp2p-pubsub.(*validation).validate
	external/com_github_libp2p_go_libp2p_pubsub/validation.go:232 +0x473

goroutine 16202302 [runnable]:
github.com/prysmaticlabs/prysm/shared/stateutil.ValidatorBalancesRoot(0xc0bc51a000, 0x9a4f, 0x9a4f, 0x0, 0x0, 0x0, 0x0, 0xeb74fdafffae78e1, 0x0)
	shared/stateutil/validators.go:30 +0xa9
github.com/prysmaticlabs/prysm/shared/stateutil.(*stateRootHasher).computeFieldRoots(0xc0000100a0, 0xc048a75980, 0x7fe9d06e1008, 0x0, 0x84eb230b0a9be97d, 0xc7ba383b90b793bc, 0x8a35cf6cd1fe9ce6)
	shared/stateutil/state_root.go:154 +0x8af
github.com/prysmaticlabs/prysm/shared/stateutil.ComputeFieldRoots(0xc048a75980, 0x16f5500, 0xc065c1e3c0, 0x15ec640, 0x28838b0, 0xc0301f75c8)
	shared/stateutil/state_root.go:56 +0xb6
github.com/prysmaticlabs/prysm/beacon-chain/state.(*BeaconState).HashTreeRoot(0xc064c319a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	beacon-chain/state/types.go:123 +0xdc
github.com/prysmaticlabs/prysm/beacon-chain/core/state.ProcessSlot(0x1bb8ee0, 0xc065c1e390, 0xc064c319a0, 0x0, 0x0, 0x0)
	beacon-chain/core/state/transition.go:201 +0x1a4
github.com/prysmaticlabs/prysm/beacon-chain/core/state.ProcessSlots(0x1bb8ee0, 0xc065c1e390, 0xc064c319a0, 0x356a0, 0x0, 0x0, 0x0)
	beacon-chain/core/state/transition.go:299 +0x382
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).validateAggregatedAtt(0xc005132000, 0x1bb8ee0, 0xc065c1e300, 0xc0128307d0, 0x0)
	beacon-chain/sync/validate_aggregate_proof.go:100 +0x740
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).validateAggregateAndProof(0xc005132000, 0x1bb8ee0, 0xc065c1e270, 0xc02e812d20, 0x27, 0xc03d738120, 0x0)
	beacon-chain/sync/validate_aggregate_proof.go:62 +0x3e6
github.com/prysmaticlabs/prysm/beacon-chain/sync.wrapAndReportValidation.func1(0x1bb8ea0, 0xc048a96a20, 0xc02e812d20, 0x27, 0xc03d738120, 0xc00f188900)
	beacon-chain/sync/subscriber.go:184 +0x1c0
github.com/libp2p/go-libp2p-pubsub.(*topicVal).validateMsg(0xc007ae2de0, 0x1bb8e20, 0xc000082840, 0xc02e812d20, 0x27, 0xc03d738120, 0x442b1d63418b7500)
	external/com_github_libp2p_go_libp2p_pubsub/validation.go:335 +0x8a
github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic(0xc0005fc870, 0xc007ae2de0, 0xc02e812d20, 0x27, 0xc03d738120, 0x8)
	external/com_github_libp2p_go_libp2p_pubsub/validation.go:316 +0x18d
github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic(0xc0005fc870, 0xc048251db8, 0x1, 0x1, 0xc02e812d20, 0x27, 0xc03d738120, 0x10000c0da94af00)
	external/com_github_libp2p_go_libp2p_pubsub/validation.go:269 +0x3c8
github.com/libp2p/go-libp2p-pubsub.(*validation).doValidateTopic(0xc0005fc870, 0xc048251db8, 0x1, 0x1, 0xc02e812d20, 0x27, 0xc03d738120)
	external/com_github_libp2p_go_libp2p_pubsub/validation.go:258 +0x74
github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1(0xc0005fc870, 0xc048251db8, 0x1, 0x1, 0xc02e812d20, 0x27, 0xc03d738120)
	external/com_github_libp2p_go_libp2p_pubsub/validation.go:233 +0x67
created by github.com/libp2p/go-libp2p-pubsub.(*validation).validate
	external/com_github_libp2p_go_libp2p_pubsub/validation.go:232 +0x473`

**Validator**

[2020-02-09 18:22:12] ERROR validator: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4000: connect: connection refused"
[2020-02-09 18:22:12] ERROR validator: Failed to update assignments error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4000: connect: connection refused"

**Comment by prestonvanloon** [comment] 2020-02-12 21:20
I think this is a duplicate of #4829. Please download the latest master or docker image and reopen if you are still experiencing issues.

**Closed by prestonvanloon** 2020-02-12 21:20 UTC
