### ISSUE TITLE
Initial sync in a loop

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5502] opened 2020-04-18 23:37 UTC
See screen shot, initial syncing went from `6917 -> 6887` three times before entering the next phase

<img width="1271" alt="Screen Shot 2020-04-18 at 4 34 57 PM" src="https://user-images.githubusercontent.com/21316537/79673886-b16adb80-8192-11ea-8d80-d31222bda5f0.png">

**Comment by torfbolt** [comment] 2020-04-19 22:00
I'm pretty sure I've seen this issue already several weeks ago. Unfortunately I didn't file an issue then, but it might be something that already existed before the new init sync code.

**Comment by farazdagi** [comment] 2020-04-20 08:34
If it doesn't get out of loop - then, it is something unexpected. However, in presence of many skipped blocks, some redundant calls are expected. Here is how it works in `init-sync` state machine:
- blocks are fetched normally, once fetched their parent roots are checked, and blocks are saved
- on skipped and forked slots, system cannot save blocks, but since in specs it is allowed for peer node to return no blocks (that's absence of blocks from peers doesn't mean no blocks exist) and furthermore in presence of evil peers pushing incoherent data, system doesn't know whether the block that can be saved exists **within the range it already fetched or in some future slot**
- when this happens, system will quickly peek the future blocks (moving mostly forward), but constantly and redundantly re-requesting within the existing range as well (so that if some evil peer or peer with missing blocks wasn't providing info, it is obtained now).
- this redundancy tends to increase on many skipped blocks (especially when they are interwoven with many valid blocks) and when we are near the head (as head is constantly moving as well - sync takes time, and by time we are at head we need to re-request to see if chain has progressed)

@terencechain please let me know if you think that sth else is going on here (or if you've got stuck in that loop forever). Otherwise, it is not a bug, it is how I've implemented `init-sync` to guarantee that if there's at least one healthy peer, sync will progress, even in presence of missing/misleading info from other peers.

@torfbolt Thank you for that extra information, previously we had the looping you've mentioned indeed (and pretty bad one for that matter - loop that occurred from time to time and is permanent, and the new sync - albeit with above-mentioned redundancy - was created in part to solve that looping prob as well).

Closing for now, please, feel free to re-open if the explanation above covers the case insufficiently.

**Closed by farazdagi** 2020-04-20 08:34 UTC
