### ISSUE TITLE
GetValidatorPerformance Returns Incorrect Data

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#5377] opened 2020-04-10 11:26 UTC
Currently we have a race condition in `GetValidatorPerformance` where we might miss the appropriate time to retrieve the validator's performance metrics. If for example we have a skip slot during an epoch boundary slot, we will retrieve the incorrect set of data. 

There are also many potential edge cases to how it could be wrong. We use a global variable in the `core/epoch/precompute` package, this has high suspectibility of giving us the wrong data as it is used whenever `ProcessEpochPrecompute` is run. This method is used in a lot of places in prysm, ex: StateGen. So we could end up retrieving the epoch data from an unrelated epoch compared to the head epoch of the chain.
```
{"correctlyVotedHead":true,"correctlyVotedSource":true,"correctlyVotedTarget":true,"epoch":203,"inclusionDistance":1,"inclusionSlot":6453,"level":"info","msg":"Previous epoch voting summary","newBalance":32.07111076,"oldBalance":32.07077256,"percentChange":"0.00105%","prefix":"validator","pubKey":"0x96ef954b331a5341","time":"2020-04-10T06:53:29+01:00"}
{"correctlyVotedHead":true,"correctlyVotedSource":true,"correctlyVotedTarget":true,"epoch":204,"inclusionDistance":1,"inclusionSlot":6507,"level":"info","msg":"Previous epoch voting summary","newBalance":32.071778775,"oldBalance":32.07144896,"percentChange":"0.00103%","prefix":"validator","pubKey":"0x96ef954b331a5341","time":"2020-04-10T06:59:53+01:00"}
{"correctlyVotedHead":true,"correctlyVotedSource":true,"correctlyVotedTarget":true,"epoch":205,"inclusionDistance":1,"inclusionSlot":6507,"level":"info","msg":"Previous epoch voting summary","newBalance":32.07178716,"oldBalance":32.07144896,"percentChange":"0.00105%","prefix":"validator","pubKey":"0x96ef954b331a5341","time":"2020-04-10T07:06:17+01:00"}
```

**Comment by nisdas** [comment] 2020-04-10 11:27
cc @mcdee

**Comment by mcdee** [comment] 2020-04-14 11:17
I spent some time looking at this issue; it basically comes down to a race condition.  Simple mutexing won't help here, and a more comprehensive mutexing would cause long-lasting locks.

The validator client could be changed to wait for a bit before it fetches the stats, but the condition will always exist for whatever value of "a bit" we choose.  As such, I *think* the best solution at this point is to move to a push-based solution.  This would take the form of a stream that sends performance data to the validator whenever said data is ready.

The good news is that we already have an implementation that does some of this, in `ValidatorInfoStream`.  The changes that would be needed to support this would be:

  - add `ValidatorSummary` to the `BlockProcessedData` struct, which is broadcast every time a block is processed
  - add the information in `ValidatorSummary` to the existing infostream
  - add a subscription to the infostream from the validator client

The main downside of this solution is that it adds weight to the `BlockProcessed` event for a single purpose.

I'll play around with an implementation of this to see if it works in reality.  If anyone has other thoughts on if this is a poor idea, or if there are better solutions, I'd love to hear them.

**Comment by nisdas** [comment] 2020-04-14 11:43
i like this idea, and I think in general it would be a good idea to migrate to having a push based stream where we send the updated data when we receive it instead of a more brittle polling based system. 

Although I am slightly wary of doing this
> add ValidatorSummary to the BlockProcessedData struct, which is broadcast every time a block is processe

ValidatorSummary is not lightweight, especially with a mainnet state with 16k+ validators. Doing this for every block processed might be excessive. How about instead we only send it in every epoch transition resulting from the block ? Then we can push this data to our validator clients. 

@prysmaticlabs/core-team does anyone have any thoughts on this ?

**Comment by mcdee** [comment] 2020-04-14 12:00
> ValidatorSummary is not lightweight, especially with a mainnet state with 16k+ validators. Doing this for every block processed might be excessive. 

`ValidatorSummary` is an array of pointers, so not as bad as passing all of the structs around, but yeah agree.

> How about instead we only send it in every epoch transition resulting from the block?

This would make sense, as long as we can know which block we should post it in.  What happens if we miss a block either side of the epoch boundary, for example?

**Comment by nisdas** [comment] 2020-04-14 12:06
Ex: we have 8 slots per epoch

If my current head is in slot 6, and the next 3 slots end up being skip slots. Then we received a block at slot 10, that block would be where the epoch transition was triggered. So at slot 10, we would send our related validator summaries to our validator clients. Basically at which ever block at which we have the next epoch transition triggered.

**Comment by shayzluf** [comment] 2020-04-27 16:52
@mcdee are you still on this issue? 
would you like me to assign it to someone else?

**Comment by rauljordan** [comment] 2020-06-05 04:41
Duplicate of #6070

**Closed by rauljordan** 2020-06-05 04:41 UTC
Labels: Bug, Help Wanted
