### ISSUE TITLE
The error when running beacon chain

### ISSUE THREAD

**Issue by maisuid** [prysmaticlabs/prysm#9675] opened 2021-09-26 10:16 UTC
Just got this error , I am not sure if it was reported

panic: runtime error: index out of range [7299] with length 6546

bufio.(*Reader).Read(0xc07611b2c0, 0xc00b37568a, 0x1992, 0xa976, 0x1c84, 0x0, 0x0)
        GOROOT/src/bufio/bufio.go:218 +0x3f0
io.ReadAtLeast(0x26ceee0, 0xc07611b2c0, 0xc00b373000, 0x401c, 0xd000, 0x401c, 0xd000, 0xf, 0xc00b373000)
        GOROOT/src/io/io.go:328 +0x8e
io.ReadFull(...)
        GOROOT/src/io/io.go:347
github.com/libp2p/go-libp2p-noise.(*secureSession).readNextMsgInsecure(0xc0a97504d0, 0xc00b373000, 0x401c, 0xd000, 0xd000, 0x400000000000000)
        external/com_github_libp2p_go_libp2p_noise/rw.go:148 +0x65
github.com/libp2p/go-libp2p-noise.(*secureSession).Read(0xc0a97504d0, 0xc031899490, 0xc, 0xc, 0x0, 0x0, 0x0)
        external/com_github_libp2p_go_libp2p_noise/rw.go:76 +0x3ff
io.ReadAtLeast(0x16bac075318, 0xc0a97504d0, 0xc031899490, 0xc, 0xc, 0xc, 0xc, 0x0, 0x0)
        GOROOT/src/io/io.go:328 +0x8e
io.ReadFull(...)
        GOROOT/src/io/io.go:347
github.com/libp2p/go-yamux.(*Session).recvLoop(0xc027c002d0, 0x0, 0x0)
        external/com_github_libp2p_go_yamux/session.go:564 +0xe5
github.com/libp2p/go-yamux.(*Session).recv(0xc027c002d0)
        external/com_github_libp2p_go_yamux/session.go:543 +0x32
created by github.com/libp2p/go-yamux.newSession
        external/com_github_libp2p_go_yamux/session.go:129 +0x408
ERROR FAILED

The enviroment:
1.  Windows Server 2019 x64
2.  Intel 8Core 2.5G cpu + 16G memory
3.  beacon chain v1.4.3

**Comment by cryptodeal6** [comment] 2021-09-27 11:23
![prysmfail](https://user-images.githubusercontent.com/91469158/134899080-7566c1e5-14d9-494a-9cbb-ab35100ddbaa.png)
Same issue today. Beaconchain crashed yesterday, downloaded new prsym this morning and tried running the beaconchain got this error.

**Comment by cryptodeal6** [comment] 2021-09-28 01:21
> > ![prysmfail](https://user-images.githubusercontent.com/91469158/134899080-7566c1e5-14d9-494a-9cbb-ab35100ddbaa.png)
> > Same issue today. Beaconchain crashed yesterday, downloaded new prsym this morning and tried running the beaconchain got this error.
> 
> @cryptodeal6 this is a very different issue. Other people on the internet have reported this error may occur when your disk is full. (See [NebulousLabs/Sia#2775 (comment)](https://github.com/NebulousLabs/Sia/issues/2775#issuecomment-366542353)). Is this the case for you? If not, please file a new issue for us to work on.

yup, you were absolutely right, it was hard drive space.  
thanks!
good day

**Comment by nisdas** [comment] 2021-09-28 01:57
Hey @maisuid , 

Thanks for the report, it seems to be a windows specific bug. A few users reported this previously, I raised this here in the microsoft support forum. However, I wasn't able to get anything:
https://docs.microsoft.com/en-us/answers/questions/506180/invalid-data-from-readfile-function.html

How up to date is your windows version ?

**Comment by maisuid** [comment] 2021-09-28 02:46
Here is the version



![图像2021-9-28 上午10 40](https://user-images.githubusercontent.com/12505662/135014176-2ac5c6fe-1139-4b09-873b-b1bf6ee84e89.jpg)

**Comment by nisdas** [comment] 2021-09-28 04:31
That might be an out of date build, please update to the latest one:
https://support.microsoft.com/en-us/topic/november-10-2020-kb4586793-os-build-17763-1577-expired-e6a24f90-5659-8b80-5a50-8752de3d90b7

**Comment by nmuneshwar** [comment] 2022-05-04 13:25
```
panic: runtime error: slice bounds out of range [:7300] with capacity 4096

goroutine 7136189530 [running]:
bufio.(Reader).Read(0xc0657d2a20, 0xc050f25644, 0x9d8, 0x49bc, 0x1c84, 0x0, 0x0)
        GOROOT/src/bufio/bufio.go:238 +0x3da
io.ReadAtLeast(0x2e194e0, 0xc0657d2a20, 0xc050f22000, 0x401c, 0x8000, 0x401c, 0x8000, 0xf, 0xc050f22000)
        GOROOT/src/io/io.go:328 +0x8e
io.ReadFull(...)
        GOROOT/src/io/io.go:347
github.com/libp2p/go-libp2p-noise.(secureSession).readNextMsgInsecure(0xc014400a50, 0xc050f22000, 0x401c, 0x8000, 0x8000, 0x401c)
        external/com_github_libp2p_go_libp2p_noise/rw.go:148 +0x65
github.com/libp2p/go-libp2p-noise.(secureSession).Read(0xc014400a50, 0xc0ac118350, 0xc, 0xc, 0x0, 0x0, 0x0)
        external/com_github_libp2p_go_libp2p_noise/rw.go:76 +0x3ff
io.ReadAtLeast(0x1b8f74d98e0, 0xc014400a50, 0xc0ac118350, 0xc, 0xc, 0xc, 0xc, 0x0, 0x0)
        GOROOT/src/io/io.go:328 +0x8e
io.ReadFull(...)
        GOROOT/src/io/io.go:347
github.com/libp2p/go-yamux/v2.(Session).recvLoop(0xc097758d00, 0x0, 0x0)
        external/com_github_libp2p_go_yamux_v2/session.go:584 +0xe5
github.com/libp2p/go-yamux/v2.(*Session).recv(0xc097758d00)
        external/com_github_libp2p_go_yamux_v2/session.go:563 +0x32
created by github.com/libp2p/go-yamux/v2.newSession
        external/com_github_libp2p_go_yamux_v2/session.go:133 +0x417
ERROR FAILED
an error has occured, set PRYSM_AUTORESTART=1 to automatically restart
```

Got this error running Prysm on Windows

**Comment by prestonvanloon** [comment] 2022-05-04 13:41
@nmuneshwar: What version of prysm?

**Comment by maisuid** [comment] 2022-05-04 14:58
Sorry for no reply.

I had updated my windows to the latest verion, and the error still happened for 2-3 times

I always keep the verion of prysm the latest one.

**Comment by nmuneshwar** [comment] 2022-05-05 16:42
@prestonvanloon 
Hi, unfortunately I don't know the exact version in my case when the crash occurred, I believe it was one version prior but I could be wrong. My validator had been running smoothly with no hiccups since March 8th, so whatever version was current on that day. 
The crash occurred some time on [April 30th](https://gyazo.com/343f2011157e1563b7866933aa27c65c)

**Comment by prestonvanloon** [comment] 2022-05-05 20:17
OK thanks @nmuneshwar.

Let's close this issue for now since we aren't sure how to reliably reproduce it or which version of the code this issue manifests. It is likely that this has already been fixed, but hard to know without the full details. Thanks!

**Closed by prestonvanloon** 2022-05-05 20:17 UTC
Labels: Bug, Windows
