### ISSUE TITLE
"error=could not process slot from the future" error is incorrect

### ISSUE THREAD

**Issue by racer8** [prysmaticlabs/prysm#7315] opened 2020-09-23 07:00 UTC
Regarding the "error=could not process slot from the future" error, I set my system clock to 2 minutes ahead of real time and still got the errors.  I was getting errors for blocks that were well into the past so I think the beacon is incorrectly identifying blocks as being in the future.
It could be that the beacon is getting the time from the wrong place due to the following:
- The stdout timestamps are one hour behind.
- Here in the UK we are in daylight saving and clocks have been put forward one hour.
- My system is clock is synced via windows and correctly set to daylight saving time.

**Comment by terencechain** [comment] 2020-09-25 22:33
you could get these errors if you receive blocks and and attestations from the future. Do you have the error log for example? I'm going to close this because this is very likely a set up issue

**Closed by terencechain** 2020-09-25 22:33 UTC

**Comment by racer8** [comment] 2020-09-26 07:13
If I was truly getting blocks from the future then every beacon would be logging this error which does not seem to be the case.  What is the set up error?  You're guessing.

**Comment by nisdas** [comment] 2020-09-26 11:00
@racer8 I tried setting my local time 10 minutes ahead and got no such error. I am suspecting it might be an issue with time in your local system, how have you synced time on your local machine ?

**Comment by racer8** [comment] 2020-09-26 12:07
You would need to set your clock back to get the error.  I set mine forward to try and remove the error.  I have synced my clock many times (as have others reporting the error) and can be less than a second different to real time but that does not help.

Here is some of the error log
[2020-09-26 12:01:31]  INFO blockchain: Synced new block block=0x741137bd... epoch=11915 finalizedEpoch=11913 finalizedRoot=0x31c0aaf2... slot=381288 slotInEpoch=8
[2020-09-26 12:01:31]  INFO blockchain: Finished applying state transition attestations=106 attesterSlashings=0 deposits=0 proposerSlashings=0 voluntaryExits=0
[2020-09-26 12:01:32]  WARN sync: Rejecting incoming block. blockSlot=381308 error=could not process slot from the future, slot time 2020-09-26 12:01:44 +0000 UTC > current time 2020-09-26 12:01:32.7901034 +0000 UTC m=+153681.466767301

All the above time stamps, slot times and current times are exactly one hour behind my local synced time and real time.  So the beacon thinks the time is one hour behind my local time and real time, that may be the source of the error.  As explained before we are under daylight saving time here in the UK, i.e. one hour ahead of GMT0.  Where does the beacon get it's time from in Windows?  I'd suggest it is a raw time and not the adjusted time?

**Comment by nisdas** [comment] 2020-09-26 12:40
I am not sure if I understand 
```
[2020-09-26 12:01:31] INFO blockchain: Synced new block block=0x741137bd... epoch=11915 finalizedEpoch=11913 finalizedRoot=0x31c0aaf2... slot=381288 slotInEpoch=8
[2020-09-26 12:01:31] INFO blockchain: Finished applying state transition attestations=106 attesterSlashings=0 deposits=0 proposerSlashings=0 voluntaryExits=0
[2020-09-26 12:01:32] WARN sync: Rejecting incoming block. blockSlot=381308 error=could not process slot from the future, slot time 2020-09-26 12:01:44 +0000 UTC > current time 2020-09-26 12:01:32.7901034 +0000 UTC m=+153681.466767301
```
the difference in slots here is 20. With each slot being 12 seconds , The difference between the blocks is 4 minutes, If you were 1 hour behind, then you wouldnt be able to process both  blocks. Instead you are able to process the first one and reject the second one. From the second one's error log, it is 11 seconds off so not a very big difference. System time is usually adjusted for differences in timezone/daylight savings, I am not too familiar with windows but I do know there is a windows time service which does this.

**Comment by racer8** [comment] 2020-09-26 12:54
Thank you for your effort on this problem.  I think the daylight saving may or may not be causing a problem so let's ignore in the meantime.

What I can tell you is that that using https://www.timeanddate.com/ I can see that my system time is within a second of the real time and time.is says my time is exact So I don't understand why the beacon is seeing a 12 second difference.  My system has spare CPU, memory and network resource so it shouldn't be a resource bottleneck.  

It could well be something not right with my system, it's running the latest version of windows 10.  

I don't know enough to understand how the beacon processes blocks and what you mean by the difference in slots is 20?

**Comment by nisdas** [comment] 2020-09-26 13:00
So it isnt the case that your node is behind but that other nodes might also be out of sync. So you get these blocks, unless
you see this happening very often you shouldnt have to worry. When I say difference in slots I am mostly referring to block time, here. A difference in 1 slot is 12 seconds, 2 slots is 24 seconds, etc .

**Comment by racer8** [comment] 2020-09-27 08:20
Where does the timestamp on the future blocks come from?  The peer that provides it or the node that actually creates the original block?

**Comment by prestonvanloon** [comment] 2020-09-28 16:48
@racer8 the blocks don't have a timestamp, but they do have a slot number. From the slot number, we can derive the slot start time. If a block arrives _before_ our determined slot start time, it is considered "from the future" and should not be processed. 

There is a small acceptance/tolerance for blocks that arrive early, but a block that arrives 12 seconds early is not acceptable. 

The root of the problem is either:
- Your system time is skewed (this is obvious if you see this warning very often)
- The block producer's clock was off and they produced the block too early (if you see a 1 off warning, this is more likely).

**Comment by racer8** [comment] 2020-09-28 18:09
Thanks.  Did you see my comments above?  My system time is accurate and I get lots of these errors.  Is there anything I can provide you to help find this error?

**Comment by prestonvanloon** [comment] 2020-09-28 18:21
Could you provide more information? 

What operating system?
What version of Prysm? 
How are you running it? (docker, prysh.sh, prysm.bat, or bazel build/run)

**Comment by racer8** [comment] 2020-09-28 18:27
I'm running Windows 10 Home, version 10.0.19041 Build 19041.  I'm only running the latest Docker version of the Beacon (Alpha.26), no validators.

**Comment by prestonvanloon** [comment] 2020-09-28 18:28
OK great thanks. 

I wonder if there is some drift with docker machine clock on windows. Do you have the same issue if you run with `prysm.bat`?

**Comment by racer8** [comment] 2020-09-28 18:33
I have not run with Prysm.bat - how do you do that?

**Comment by prestonvanloon** [comment] 2020-09-28 18:39
Following the instructions for windows here: https://docs.prylabs.network/docs/install/install-with-script#running-the-prysm-startup-script

**Comment by racer8** [comment] 2020-09-29 06:10
Hi - I've run the docker system info command and it does look like the docker clock is many seconds behind real time so your intuition looks to be correct.  I have run with prysm.bat and it runs error free.  Thanks for your time to solve this problem.

**Comment by ChuckNorrison** [comment] 2020-10-11 14:39
the block i receive comes 2 seconds from the future if i get this right?

> Oct 11 16:26:04 prysm prysm.sh[184602]: time="2020-10-11 16:26:04" level=info msg="Verified and saved pending attestations to pool" blockRoot=65c29cdb0c2c pendingAttsCount=2 prefix=sync
> Oct 11 16:26:35 prysm prysm.sh[184602]: time="2020-10-11 16:26:35" level=warning msg="Rejecting incoming block." blockSlot=87132 error="could not process slot from the future, slot time 2020-10-11 16:26:37 +0200 CEST > current time 2020-10-11 16:26:35.840503794 +0200 CEST m=+11047.531622400" prefix=sync
> Oct 11 16:26:52 prysm prysm.sh[184602]: time="2020-10-11 16:26:52" level=info msg="Synced new block" block=0x333a355f... epoch=2722 finalizedEpoch=1723 finalizedRoot=0x7992a561... prefix=blockchain slot=87132 slotInEpoch=28
> Oct 11 16:26:52 prysm prysm.sh[184602]: time="2020-10-11 16:26:52" level=info msg="Finished applying state transition" attestations=4 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
> Oct 11 16:26:58 prysm prysm.sh[184602]: time="2020-10-11 16:26:58" level=info msg="Verified and saved pending attestations to pool" blockRoot=333a355f586b pendingAttsCount=1 prefix=sync
> Oct 11 16:26:58 prysm prysm.sh[184602]: time="2020-10-11 16:26:58" level=info msg="Peer disconnected" activePeers=4 multiAddr="/ip4/173.249.17.215/tcp/13000/p2p/16Uiu2HAmA7gYJouzoMg7jLGTtQERnvUh1bsRCRML1LA8Jeq2yYek" prefix=p2p
> Oct 11 16:27:22 prysm prysm.sh[184602]: time="2020-10-11 16:27:22" level=warning msg="Rejecting incoming block." blockSlot=87136 error="could not process slot from the future, slot time 2020-10-11 16:27:25 +0200 CEST > current time 2020-10-11 16:27:22.332908625 +0200 CEST m=+11094.024027320" prefix=sync
> Oct 11 16:27:44 prysm prysm.sh[184602]: time="2020-10-11 16:27:44" level=info msg="Synced new block" block=0x169e97bf... epoch=2723 finalizedEpoch=1723 finalizedRoot=0x7992a561... prefix=blockchain slot=87136 slotInEpoch=0
> Oct 11 16:27:44 prysm prysm.sh[184602]: time="2020-10-11 16:27:44" level=info msg="Finished applying state transition" attestations=4 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
> Oct 11 16:27:46 prysm prysm.sh[184602]: time="2020-10-11 16:27:46" level=info msg="Verified and saved pending attestations to pool" blockRoot=169e97bff5eb pendingAttsCount=2 prefix=sync
> Oct 11 16:27:47 prysm prysm.sh[184602]: time="2020-10-11 16:27:47" level=warning msg="Rejecting incoming block." blockSlot=87138 error="could not process slot from the future, slot time 2020-10-11 16:27:49 +0200 CEST > current time 2020-10-11 16:27:47.880815079 +0200 CEST m=+11119.571933759" prefix=sync

Version used is alpha28. i already checked local time and ntp sync, could not find any issues.... some hints on timestamp servers to use?
