### ISSUE TITLE
Show that validator has been slashed

### ISSUE THREAD

**Issue by Phistr90** [prysmaticlabs/prysm#5579] opened 2020-04-22 14:06 UTC
# 🚀 Feature Request

### Description

Currently there is no outout in the validator client that indicates that the validator has been slashed and exited other than an reduced balanced  

### Describe the solution you'd like

Would be nice if you could clearly signal that a validator has been slashed and exited

**Comment by rauljordan** [comment] 2020-04-22 14:09
Hi @Phistr90 your validator client will display status=SLASHED if you are indeed slashed. Are you not seeing this locally? Can you confirm your validator is slashed on https://beaconcha.in? what's your validator index?

**Comment by Phistr90** [comment] 2020-04-22 15:03
On the validator it shows the status during the new assignment. But after the validator is slashed there is no new assignment so it doesnt show the status.

`[2020-04-22 11:55:12]  INFO validator: Previous epoch aggregated voting summary attestationInclusionPercentage=1.00 correctlyVotedHeadPercentage=1.00 correctlyVotedSourcePercentage=1.00 correctlyVotedTargetPercentage=1.00 epoch=992
[2020-04-22 11:55:12]  INFO validator: New assignment attesterSlot=31794 committeeIndex=0 epoch=993 pubKey=0x93f571fdf26b status=ACTIVE validatorIndex=10193
[2020-04-22 11:58:52]  INFO validator: Submitted new attestations AggregatorIndices=[] AttesterIndices=[10193] BeaconBlockRoot=0x0032d69240b5 CommitteeIndex=0 Slot=31794 SourceEpoch=992 SourceRoot=0xf214bdea8168 TargetEpoch=993 TargetRoot=0xcafc41f38e63
[2020-04-22 12:01:36]  INFO validator: Previous epoch voting summary correctlyVotedHead=true correctlyVotedSource=true correctlyVotedTarget=true epoch=993 inclusionDistance=1 inclusionSlot=31734 newBalance=32.071141931 oldBalance=32.071065906 percentChange=0.00024% pubKey=0x93f571fdf26baf24`

It goes on with the previous voting summary. no status shown.

**Comment by rauljordan** [comment] 2020-04-22 15:44
Thanks for the feedback, @0xKiwi is this something we can amend on the status code of the validator client?

**Comment by 0xKiwi** [comment] 2020-04-22 15:57
Totally! I have #5338 open as a tracking issue.

**Comment by rauljordan** [comment] 2020-04-22 16:10
Great, closing as a duplicate of #5338, please follow that issue @Phistr90

**Closed by rauljordan** 2020-04-22 16:10 UTC
