### ISSUE TITLE
Cannot run the Windows exe "This app can't run on your PC" error message on 1.1.0

### ISSUE THREAD

**Issue by exo3000** [prysmaticlabs/prysm#8282] opened 2021-01-18 23:55 UTC
I've tried on two different Windows versions and machines, Server 2016 and Windows 10, and get the exact same error message. "This app can't run on your PC. GUI error here: https://i.imgur.com/WJdKjX7.png

**Comment by prestonvanloon** [comment] 2021-01-18 23:59
May be related to #8283

**Comment by exo3000** [comment] 2021-01-18 23:59
Yes, very likely.

**Comment by prestonvanloon** [comment] 2021-01-19 00:00
Are you running a 32-bit OS or 64-bit OS?

**Comment by exo3000** [comment] 2021-01-19 00:00
64-bit, both machines.

**Comment by prestonvanloon** [comment] 2021-01-19 00:03
Thanks for confirming that. I'm thinking it is some kind of file permissions issue

**Comment by terencechain** [comment] 2021-01-19 00:24
Looks to be duplicated as #8283

**Comment by prestonvanloon** [comment] 2021-01-19 00:53
Yes, closing as duplicate of #8283

**Closed by prestonvanloon** 2021-01-19 00:53 UTC
