### ISSUE TITLE
Interesting public key

### ISSUE THREAD

**Issue by 627965745** [prysmaticlabs/prysm#6320] opened 2020-06-19 19:19 UTC
Not sure if it's a bug
# 💎 Issue
wanted to become a validator and
followed instructions from https://docs.prylabs.network/docs/install/windows/ 
and https://prylabs.net/participate
I then get my public key with all ZEROs
0xc00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
https://beacon.etherscan.io/validator/20390
### Background

Operating System: 64-bit Windows

### Description
![image](https://user-images.githubusercontent.com/25855932/85172934-09dd5880-b26a-11ea-9b67-04c0cf0c9301.png)

**Comment by 627965745** [comment] 2020-06-19 19:26
My password is not empty

**Comment by prestonvanloon** [comment] 2020-06-19 19:46
@nisdas I believe you saw this recently? Can you take a look?

Tentatively assigning to @nisdas, please delegate or unassign as appropriate.

**Comment by handelaar2** [comment] 2020-06-19 21:00
#6301

**Comment by nisdas** [comment] 2020-06-19 22:35
@627965745 do you get the same result when you do 
```
validators account create
```
Also could you provide detailed specs on the machine you are running:
```
Architecture:       
OS version:
Number of Cores:
Processor:
Processor Vendor:
System Memory:
CPU (Mhz):
.
.
```
For windows you can usually find this in system settings or through the `msinfo32` program. 

cc @herumi

**Comment by 627965745** [comment] 2020-06-20 00:18
@nisdas same result when doing "validator accounts create"


[System Summary]

Item	Value	
OS Name	Microsoft Windows 10 Professional
Version	10.0.18363 Build 18363	
Other OS Description 	Not Available	
OS Manufacturer	Microsoft Corporation	
System Name	DESKTOP-LEQGVER	
System Manufacturer	System manufacturer	
System Model	ROG STRIX Z390-E GAMING	
System Type	x64-based PC	
System SKU	SKU	
Processor	Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, 3696 Mhz, 6 Core(s), 12 Logical Processor(s)	
BIOS Version/Date	American Megatrends Inc. 0224, 14/08/2018	
SMBIOS Version	3.1	
Embedded Controller Version	255.255	
BIOS Mode	UEFI	
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.	
BaseBoard Product	ROG STRIX Z390-E GAMING	
BaseBoard Version	Rev 1.xx	
Platform Role	Desktop	
Secure Boot State	Off	
PCR7 Configuration	Binding Not Possible	
Windows Directory	C:\Windows	
System Directory	C:\Windows\system32	
Boot Device	\Device\HarddiskVolume17	
Locale	China	
Hardware Abstraction Layer	Version = "10.0.18362.752"	
Username	DESKTOP-LEQGVER\vampi	
Time Zone	GMT Summer Time	
Installed Physical Memory (RAM)	32.0 GB	
Total Physical Memory	31.9 GB	
Available Physical Memory	26.2 GB	
Total Virtual Memory	40.7 GB	
Available Virtual Memory	33.5 GB	
Page File Space	8.75 GB	
Page File	C:\pagefile.sys	
Kernel DMA Protection	Off

**Comment by nisdas** [comment] 2020-06-20 00:49
Thanks for giving the machine specs @627965745 ,
@herumi does anything stand out over here ? Any idea why random key generation is broken on 
his machine

**Comment by herumi** [comment] 2020-06-20 07:45
Does this mean that it always creates zero secret key?

**Comment by nisdas** [comment] 2020-06-20 07:48
Yes it seems like it, for each account creation we create two sets of keys, and both keys were zero the first time. @627965745 tried this again and got the same result. So i am assuming random key generation is broken somewhere ?

**Comment by herumi** [comment] 2020-06-20 08:28
Could you clone https://github.com/herumi/bls-eth-go-binary/ and exec the following command?

```
go run examples/sample.go
```

```
sample2
sec:XXX
```
If XXX is always different, it is okay.

**Comment by nisdas** [comment] 2020-06-20 08:30
@627965745 do you mind trying the above ?

**Comment by 627965745** [comment] 2020-06-20 08:50
@herumi @nisdas Sure
it stopped at func sample1()
![image](https://user-images.githubusercontent.com/25855932/85197812-69c01780-b2db-11ea-98bb-d2ffe8538181.png)

```
C:\ansicon\x64>cd C:\eth\test\bls-eth-go-binary\examples

C:\eth\test\bls-eth-go-binary\examples>go run sample.go
sample1
panic: err blsSecretKeySetByCSPRNG zero

goroutine 1 [running]:
github.com/herumi/bls-eth-go-binary/bls.(*SecretKey).SetByCSPRNG(0xc00000c460)
        C:/eth/test/bls-eth-go-binary/bls/bls.go:292 +0x76
main.sample1()
        C:/eth/test/bls-eth-go-binary/examples/sample.go:12 +0x8d
main.main()
        C:/eth/test/bls-eth-go-binary/examples/sample.go:67 +0x43
exit status 2

C:\eth\test\bls-eth-go-binary\examples>go run sample.go
sample1
panic: err blsSecretKeySetByCSPRNG zero

goroutine 1 [running]:
github.com/herumi/bls-eth-go-binary/bls.(*SecretKey).SetByCSPRNG(0xc00000a480)
        C:/eth/test/bls-eth-go-binary/bls/bls.go:292 +0x76
main.sample1()
        C:/eth/test/bls-eth-go-binary/examples/sample.go:12 +0x8d
main.main()
        C:/eth/test/bls-eth-go-binary/examples/sample.go:67 +0x43
exit status 2
```
and if I commet out sample1() make it run sample2() straight it shows:
![image](https://user-images.githubusercontent.com/25855932/85197730-d850a580-b2da-11ea-99a6-2e835b4c22b8.png)
```
C:\eth\test\bls-eth-go-binary\examples>go run sample.go
sample2
panic: err blsSecretKeySetByCSPRNG zero

goroutine 1 [running]:
github.com/herumi/bls-eth-go-binary/bls.(*SecretKey).SetByCSPRNG(0xc00000a480)
        C:/eth/test/bls-eth-go-binary/bls/bls.go:292 +0x76
main.sample2()
        C:/eth/test/bls-eth-go-binary/examples/sample.go:22 +0x9b
main.main()
        C:/eth/test/bls-eth-go-binary/examples/sample.go:68 +0x43
exit status 2

C:\eth\test\bls-eth-go-binary\examples>go run sample.go
sample2
panic: err blsSecretKeySetByCSPRNG zero

goroutine 1 [running]:
github.com/herumi/bls-eth-go-binary/bls.(*SecretKey).SetByCSPRNG(0xc00000a480)
        C:/eth/test/bls-eth-go-binary/bls/bls.go:292 +0x76
main.sample2()
        C:/eth/test/bls-eth-go-binary/examples/sample.go:22 +0x9b
main.main()
        C:/eth/test/bls-eth-go-binary/examples/sample.go:68 +0x43
exit status 2
```

**Comment by herumi** [comment] 2020-06-20 09:05
Thank you for the quick reply. It's important information.
Could you modify `example/sample.go` as the followings and run it?

```
diff --git a/examples/sample.go b/examples/sample.go
index a3596e9..ddfd99e 100644
--- a/examples/sample.go
+++ b/examples/sample.go
@@ -4,6 +4,7 @@ import (
        "encoding/hex"
        "fmt"
        "github.com/herumi/bls-eth-go-binary/bls"
+ "crypto/rand"
 )

 func sample1() {
@@ -64,6 +65,7 @@ func sample4() {
 func main() {
        bls.Init(bls.BLS12_381)
        bls.SetETHmode(bls.EthModeDraft07)
+ bls.SetRandFunc(rand.Reader)
        sample1()
        sample2()
        sample3()
```

This patch uses rand.Reader instead of the default random generator.

**Comment by 627965745** [comment] 2020-06-20 09:14
@herumi 

```
C:\eth\test\bls-eth-go-binary\examples>go run sample.go
sample1
verify=true
sample2
sec:5f758f6e76ce4a6a1dd5b580f3fdf551c9f15cb3a4a01c7591529ec6ec53162d
1.pub:b7dcbfcf0f289e8fe0bcff61f280ffec2ea0f44f573292c553ebc322b8178d3d8cb118c11e5a1567a5254b9ef8cae463
1.pub x=&{{{{[1300990f7323f1b3 fcd24ddde6301b3 1a9c8d85f5bb0701 d29aa8581f5e29d7 79da4c4468da458a 1478307bfaba477c]} {[5d088f63cafe9f37 133584d96679221 161399f560a6cfa0 e710650f46d75771 58a9902a10fca02b 2383df857099a14]} {[5d203c7094b2401c ffe995bd8fe6ce5a 11bd458cf2c7e69d 630a271acda2f65b a07886d4a425c4f2 1118db41223c8e46]}}}}
2.pub:b7dcbfcf0f289e8fe0bcff61f280ffec2ea0f44f573292c553ebc322b8178d3d8cb118c11e5a1567a5254b9ef8cae463
2.pub x=&{{{{[bf5a574da3d0724f 5726540a5fafeba8 1ecd50261cf0b58b 9c7ff113f8828b9c ac8fd7af489dfae6 b62aa95520458df]} {[b16b81aa2b6d6d0d a4f06370275b5fb3 a17a8fda62b7d34 4c1db9099a0cc2b2 e9d256359aacc0c2 3289ef54d619918]} {[760900000002fffd ebf4000bc40c0002 5f48985753c758ba 77ce585370525745 5c071a97a256ec6d 15f65ec3fa80e493]}}}}
P.X=17dcbfcf0f289e8fe0bcff61f280ffec2ea0f44f573292c553ebc322b8178d3d8cb118c11e5a1567a5254b9ef8cae463
P.Y=18c4ee047c6bac038bdeea9f8e86ead004a327168b878dc303f8201da3f5e389dcd1962cef003b22006f123da0f83182
P.Z=000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
sample3
sec=0748d9d99f59ff1105d314967254398f2b6cedcb87925c23c999e990f3f29c6c
sample4
sec:4aac41b5cb665b93e031faa751944b1f14d77cb17322403cba8df1d6e4541a4d
pub:841c5235ec7f4eed02b3f3bb60622d3ed0aba74016f4850c6d7c962656a4b78d72a15caeef62dfe656d03990590c0026
sig:af7ab839885d3189502b1092895c4676357ef7a32863bd4253eb4c7ab12fc3aa5a9d9a82e1e641c1c85965c468e1d33018e8a0bbe1d4aef5e751b3c94876c4de312d7ccca34c9fe6b80d8dd00c6a499759cea7febfc661f80831f9547c158c84

C:\eth\test\bls-eth-go-binary\examples>go run sample.go
sample1
verify=true
sample2
sec:39c34b1ca9365dbe459bfe2cecf3356b1af804a0b401ebfde47d5d24a616437c
1.pub:8930b583702e4755e03c97de66011504a06dea56db6a92a835ae7668f53a23a063428ce2c5022d3779b47f5f7e697a59
1.pub x=&{{{{[9ab6234a313a6155 fb0441c4b236b181 7f9b0947ef4fe48f 11028072e4622d43 f7c3f4ff1a518c27 585ba4c537fe02c]} {[3c0d4edd34a4ba4e 2c0826c9ce37ff06 c197a2a6d9970ae1 869ec7fc08592ab4 65e361e3b56d702 ecb45250fdc5ec7]} {[e0f48eb56444aa9e 8a2a1a533b0d0e0c e89642a8467693a5 6b7823e24d900a03 27d200e77653abb6 108d8d5ab9370af3]}}}}
2.pub:8930b583702e4755e03c97de66011504a06dea56db6a92a835ae7668f53a23a063428ce2c5022d3779b47f5f7e697a59
2.pub x=&{{{{[22aa96ab639f2c07 ff29254330afc237 fc0ca21f9cd25241 70d4d9253a7d3301 1885bbcfb9670ab1 123128918784f95e]} {[259267f39434a253 3a141e703a10d168 4de32e38e7b482f0 561ecf9e5714390f 47a7f3d588701a43 3f17ffe956fa3a0]} {[760900000002fffd ebf4000bc40c0002 5f48985753c758ba 77ce585370525745 5c071a97a256ec6d 15f65ec3fa80e493]}}}}
P.X=0930b583702e4755e03c97de66011504a06dea56db6a92a835ae7668f53a23a063428ce2c5022d3779b47f5f7e697a59
P.Y=0c6d85e8aff1f1ef0d9ceb31d10f11abdb46dcea1eb4168121c53a5373c2adeea7b14a69def1f1035132c52090abb48c
P.Z=000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
sample3
sec=0748d9d99f59ff1105d314967254398f2b6cedcb87925c23c999e990f3f29c6c
sample4
sec:4aac41b5cb665b93e031faa751944b1f14d77cb17322403cba8df1d6e4541a4d
pub:841c5235ec7f4eed02b3f3bb60622d3ed0aba74016f4850c6d7c962656a4b78d72a15caeef62dfe656d03990590c0026
sig:af7ab839885d3189502b1092895c4676357ef7a32863bd4253eb4c7ab12fc3aa5a9d9a82e1e641c1c85965c468e1d33018e8a0bbe1d4aef5e751b3c94876c4de312d7ccca34c9fe6b80d8dd00c6a499759cea7febfc661f80831f9547c158c84

```

**Comment by herumi** [comment] 2020-06-20 09:23
Thank you. It seems good.

**Comment by herumi** [comment] 2020-06-20 11:47
Hi @627965745 , I have another request.
Could you mind executing "go run [rand-win.go](https://github.com/herumi/misc/blob/master/go/rand-win.go)" to detect the reason of the problem?

On my Windows 10 Pro (Core i7-7700) environment, it shows different random values for each execution.

```
$ go run rand-win.go
ret=1 buf=[208 224 150 85 111 77 12 255 38 52 46 69 180 119 22 206 187 117 189 178 116 243 14 233 8 128 186 167 146 67 194 229 231 224 44 110 26 12 152 159 29 112 30 44 151 196 80 238 206 42 83 112 144 164 129 147 40 85 218 33 103 237 80 229]
i=0 flag=0
found 0 prov_=00000000008912E0

```

**Comment by 627965745** [comment] 2020-06-20 12:00
@herumi  returned all zeros
```
vampi@DESKTOP-LEQGVER MINGW64 /c/eth/test/bls-eth-go-binary (master)
$ go run rand-win.go
ret=0 buf=[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
i=0 flag=0
i=1 flag=8
i=2 flag=32

vampi@DESKTOP-LEQGVER MINGW64 /c/eth/test/bls-eth-go-binary (master)
$ go run rand-win.go
ret=0 buf=[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
i=0 flag=0
i=1 flag=8
i=2 flag=32
```

**Comment by herumi** [comment] 2020-06-20 19:40
Thank you. I added one flag.
https://github.com/herumi/misc/commit/5b68e43dbde91e04d9d9e66da534a5d85b9a6c59
 Could you retry "go run rand-win.go" for the newer [rand-win.go](https://github.com/herumi/misc/blob/master/go/rand-win.go)?

**Comment by 627965745** [comment] 2020-06-20 20:57
@herumi 
```
vampi@DESKTOP-LEQGVER MINGW64 /c/eth/test/bls-eth-go-binary (master)
$ go run rand-win.go
ret=1 buf=[30 97 219 50 254 94 174 105 86 186 18 146 162 89 224 206 126 211 64 159 121 154 118 137 132 12 7 37 187 55 138 223 25 183 153 191 243 201 91 53 234 177 98 228 233 71 13 66 125 22 15 238 100 40 97 4 125 229 31 69 54 232 85 207]
i=0 flag=0
CryptAcquireContext err -2146893813
i=1 flag=8
CryptAcquireContext err -2146893809
i=2 flag=32
CryptAcquireContext err -2146893802
i=3 flag=-268435392
found 3 prov_=0000000000096750

vampi@DESKTOP-LEQGVER MINGW64 /c/eth/test/bls-eth-go-binary (master)
$ go run rand-win.go
ret=1 buf=[98 12 33 139 113 92 119 62 87 161 183 61 233 203 71 245 223 227 251 54 85 73 232 28 227 20 24 30 152 53 200 77 0 213 149 109 123 156 104 39 128 176 215 194 238 57 146 103 208 156 118 57 207 120 19 84 82 5 144 247 157 159 115 224]
i=0 flag=0
CryptAcquireContext err -2146893813
i=1 flag=8
CryptAcquireContext err -2146893809
i=2 flag=32
CryptAcquireContext err -2146893802
i=3 flag=-268435392
found 3 prov_=00000000000C6750
```

**Comment by herumi** [comment] 2020-06-20 22:12
Thank for the reply again. I can fix the problem.
By the way, those error codes mean `NTE_BAD_KEY_STATE`.
I'm not sure, what do you set some special security policies or use login?

**Comment by 627965745** [comment] 2020-06-20 22:19
@herumi  Nothing special except I use Windows Hello with facial recognition for login

**Comment by herumi** [comment] 2020-06-20 23:22
I see. It is the first time that I saw this error.

**Comment by nisdas** [comment] 2020-06-21 03:23
@herumi what do you think is the root cause of this ? is it because of some security policies in windows

**Comment by herumi** [comment] 2020-06-21 11:36
I'm not sure, but there were people with a similar phenomenon. https://stackoverflow.com/questions/29996467/cryptacquirecontext-fails-with-return-code-0x8009000b-nte-bad-key-state-but The solution was the same as https://github.com/prysmaticlabs/prysm/issues/6320#issuecomment-647037643 .
I've update a static library for Windows https://github.com/herumi/bls-eth-go-binary/commit/298ffb6847bc5dc1886977cc0edf4495c7eb6ca9 .

There was a path to ignore the failure of the initialization of a random-generator, so I've removed it. If some environment fails to init, the current version will report an error.
And if a zero secret key is generated, I appended the code to detect it.

**Comment by prestonvanloon** [comment] 2020-07-06 19:42
@nisdas is there any further action to take on our side?

**Comment by rauljordan** [comment] 2020-07-22 14:45
Bump @nisdas

**Comment by herumi** [comment] 2020-07-22 23:07
The fixed version at https://github.com/prysmaticlabs/prysm/issues/6320#issuecomment-647037643 uses the same flag https://golang.org/src/crypto/rand/rand_windows.go , so I don't think this problem will happen.

**Comment by nisdas** [comment] 2020-07-23 02:04
Yeap we can close this now @prestonvanloon @rauljordan , it has been resolved as @herumi has described.

**Closed by nisdas** 2020-07-23 02:04 UTC
