### ISSUE TITLE
beacon-chain prints incorrect error message: you have disabled the flag enable-only-blinded-beacon-blocks

### ISSUE THREAD

**Issue by begetan** [prysmaticlabs/prysm#11408] opened 2022-09-05 19:19 UTC
# 🐞 Bug Report

### Description

Prysm beacon-chain client incorrectly reports errors about flag `enable-only-blinded-beacon-blocks` when getting incorrect network db version actually

### Has this worked before in a previous version?
This bug might be itroduced in version 2.4.1 with the new flag

## 🔬 Minimal Reproduction

1.  Download or sync goerli/prater beacon file `beaconchain.db`
2. Change Prysm beacon-chain configuration to mainnet and start service.
3. It show this error: 

<pre><code>
level=error msg="you have disabled the flag enable-only-blinded-beacon-blocks, and your node must resync to ensure your database is compatible. If you do not want to resync, please re-enable the enable-only-blinded-beacon-blocks flag"
</code></pre>

4. Set flag --enable-only-blinded-beacon-blocks=true as required.
4. Restart Prysm and get the actual error:

<pre><code>
database contract is 0xff50ed3d0ec03ac01d4c79aad74928bff48a7b2b but tried to run with 0x00000000219ab540356cbb839cbe05303d7705fa. This likely means you are trying to run on a different network than what the database contains. You can run once with '--clear-db' to wipe the old database or use an alternative data directory with '--datadir'" prefix=main`
</code></pre>

## 🔥 Error

<pre><code>
level=error msg="you have disabled the flag enable-only-blinded-beacon-blocks, and your node must resync to ensure your database is compatible. If you do not want to resync, please re-enable the enable-only-blinded-beacon-blocks flag"
</code></pre>

The evaluation of the flag `enable-only-blinded-beacon-blocks` is incorrectly going before database contarct check, which lead user to a wrong conclusion

## 🌍  Your Environment

**Operating System:**

<pre><code>
Ubuntu 20.04
</code></pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v3.0.0
  </code>
</pre>

**Comment by terencechain** [comment] 2022-09-05 23:52
@begetan goerli/prater DB and mainnet DB need to be in different location, you can't mix them under one location

**Comment by rkapka** [comment] 2022-09-06 14:12
> @begetan goerli/prater DB and mainnet DB need to be in different location, you can't mix them under one location

I think what OP is getting at is that the `database contract is ...` error should be shown instead of the blinded blocks one, as flipping the flag won't help you when you have the wrong db version.

**Comment by nisdas** [comment] 2023-07-25 09:42
This feature has been the default for a while, so the issue isn't relevant anymore, closing it now.

**Closed by nisdas** 2023-07-25 09:42 UTC
Labels: Priority: Low, UX
