### ISSUE TITLE
1.3.10 WebUI does not recognize existing wallet

### ISSUE THREAD

**Issue by KarelGordon** [prysmaticlabs/prysm#8983] opened 2021-06-03 19:50 UTC
# 🐞 Bug Report

### Description

I've just upgraded prysm to 1.3.10. Restarted the prysm validator and beacon services, pointed my browser onto the WebUI on port 7500 just to find out that the Web UI does not recognize my already existing local wallet nor any previous configuration. I was presented with exactly this screen:

![prysm-webui](https://user-images.githubusercontent.com/85314083/120702588-8a658b00-c4b4-11eb-9344-c41ed0cc5e95.png)

### Has this worked before in a previous version?

Yes, it worked fine with version 1.3.9.

## 🔬 Minimal Reproduction

Just install 1.3.9, setup/import your wallet (I followed this guide: https://someresat.medium.com/guide-to-staking-on-ethereum-2-0-ubuntu-prysm-56f681646f74), then upgrade to 1.3.10 and viola, it's there.

## 🔥 Error

No there aren't any errors presented in the log of the validator node. I presume this is just normal boot log:

<pre><code>
Jun 03 19:57:00 blackbox prysm.sh[1964]: Latest Prysm version is v1.3.10.
Jun 03 19:57:00 blackbox prysm.sh[1964]: Validator is up to date.
Jun 03 19:57:00 blackbox prysm.sh[1964]: Verifying binary integrity.
Jun 03 19:57:00 blackbox prysm.sh[1979]: validator-v1.3.10-linux-amd64: OK
Jun 03 19:57:00 blackbox prysm.sh[1981]: gpg: Signature made Wed 02 Jun 2021 04:52:18 PM CEST
Jun 03 19:57:00 blackbox prysm.sh[1981]: gpg:                using RSA key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E
Jun 03 19:57:00 blackbox prysm.sh[1981]: gpg: Good signature from "Preston Van Loon <preston@prysmaticlabs.com>" [unknown]
Jun 03 19:57:00 blackbox prysm.sh[1981]: gpg: WARNING: This key is not certified with a trusted signature!
Jun 03 19:57:00 blackbox prysm.sh[1981]: gpg:          There is no indication that the signature belongs to the owner.
Jun 03 19:57:00 blackbox prysm.sh[1981]: Primary key fingerprint: 0AE0 051D 647B A3C1 A917  AF40 72E3 3E4D F1A5 036E
Jun 03 19:57:00 blackbox prysm.sh[1964]: Verified /var/ethereum/prysm/prog/dist/validator-v1.3.10-linux-amd64 has been signed by Prysmatic Labs.
Jun 03 19:57:00 blackbox prysm.sh[1964]: Starting Prysm validator --config-file=/var/ethereum/prysm/prog/config.yaml --accept-terms-of-use --web
Jun 03 19:57:00 blackbox prysm.sh[1964]: time="2021-06-03 19:57:00" level=warning msg="Running on ETH2 Mainnet" prefix=flags
Jun 03 19:57:00 blackbox prysm.sh[1964]: time="2021-06-03 19:57:00" level=info msg="Enabling web portal to manage the validator client" prefix=node
Jun 03 19:57:00 blackbox prysm.sh[1964]: time="2021-06-03 19:57:00" level=info msg="Opened validator wallet" keymanager-kind=direct prefix=node wallet="/var/ethereum/prysm/validator/direct"
Jun 03 19:57:00 blackbox prysm.sh[1964]: time="2021-06-03 19:57:00" level=info msg="Checking DB" databasePath="/var/ethereum/prysm/data" prefix=node
Jun 03 19:57:00 blackbox prysm.sh[1964]: [83B blob data]
Jun 03 19:57:00 blackbox prysm.sh[1964]: time="2021-06-03 19:57:00" level=info msg="Starting Prysm web UI on address, open in browser to access" address="http://127.0.0.1:7500" prefix=node
Jun 03 19:57:00 blackbox prysm.sh[1964]: time="2021-06-03 19:57:00" level=info msg="Starting validator node" prefix=node version="Prysm/v1.3.10/5ae6e83c7f6238593c6dfa3a8e05fc7c3778783f. Built at: 2021-06-02 14:>
Jun 03 19:57:00 blackbox prysm.sh[1964]: time="2021-06-03 19:57:00" level=warning msg="You are using an insecure gRPC connection. If you are running your beacon node and validator on the same machines, you can >
Jun 03 19:57:00 blackbox prysm.sh[1964]: time="2021-06-03 19:57:00" level=warning msg="You are using an insecure gRPC connection. If you are running your beacon node and validator on the same machines, you can >
Jun 03 19:57:00 blackbox prysm.sh[1964]: time="2021-06-03 19:57:00" level=info msg="gRPC server listening on address" address="127.0.0.1:7000" prefix=rpc
Jun 03 19:57:00 blackbox prysm.sh[1964]: time="2021-06-03 19:57:00" level=info msg="Starting gRPC gateway" address="127.0.0.1:7500" prefix=gateway
Jun 03 19:57:00 blackbox prysm.sh[1964]: time="2021-06-03 19:57:00" level=info msg="Waiting for beacon chain start log from the ETH 1.0 deposit contract" prefix=validator
Jun 03 19:57:00 blackbox prysm.sh[1964]: time="2021-06-03 19:57:00" level=info msg="Beacon chain started" genesisTime=2020-12-01 13:00:23 +0100 CET prefix=validator
Jun 03 19:57:00 blackbox prysm.sh[1964]: time="2021-06-03 19:57:00" level=info msg="Deposit processed, entering activation queue after finalization" index=yyyyyy positionInActivationQueue=xxxx prefix=validator >
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Arch Linux 5.10.41-1-lts #1 SMP Fri, 28 May 2021 15:03:28 +0000 x86_64 GNU/Linux
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
1.3.10
  </code>
</pre>

**Comment by alex3498** [comment] 2021-06-04 06:04
I have the same issue.
I was to skip this page and manually register by opening http://localhost:7500/signup
But the dashbaord page didn't work anyway.
![image](https://user-images.githubusercontent.com/70336249/120753371-f00b4480-c4bf-11eb-9d5e-9355c569d33b.png)

**Comment by sponnet** [comment] 2021-06-04 07:16
Same here..  UI stopped recognizing exiting wallets. Underlying validator runs fine & attestations still work.

**Comment by heeckhau** [comment] 2021-06-04 19:26
See https://github.com/prysmaticlabs/prysm-web-ui/issues/181

**Comment by prestonvanloon** [comment] 2021-06-04 21:11
Closing as duplicate of prysmaticlabs/prysm-web-ui#181

**Closed by prestonvanloon** 2021-06-04 21:11 UTC
