### ISSUE TITLE
error building beacon chain node

### ISSUE THREAD

**Issue by somuchid** [prysmaticlabs/prysm#4358] opened 2019-12-26 16:40 UTC
os: Ubuntu 18.04.3 LTS (fresh & minimal installation)
bazel label: 2.0.0 
command: bazel build //beacon-chain:beacon-chain
error locations: two
1st) ./third_party/kafka/BUILD.bazel:3:1: error executing shell command
2nd) ./prysm/beacon-chain/BUILD.bazel:80:1 error executing shell command

detail error message:

ERROR: /home/j/prysm/third_party/kafka/BUILD.bazel:3:1: error executing shell command: '/bin/bash -c function cleanup_function() {
local ecode=$?
if [ $ecode -eq 0 ]; then
cleanup_on_success
else
cleanup_on_failure
fi
}
set -e
function cleanup_on_success() {
printf "rules_foreign_cc: ...' failed (Exit 127) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox

rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory  and dependencies directory  for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify '--sandbox_debug' Bazel command line flag.

rules_foreign_cc: Printing build logs:

_____ BEGIN BUILD LOGS _____
Bazel external C/C++ Rules #0.0.8. Building library 'librdkafka'
Environment:______________EXT_BUILD_ROOT=/home/j/.cache/bazel/_bazel_j/4f4fbc31f3566532ef3b804d1113524c/sandbox/linux-sandbox/539/execroot/prysm
INSTALLDIR=/home/j/.cache/bazel/_bazel_j/4f4fbc31f3566532ef3b804d1113524c/sandbox/linux-sandbox/539/execroot/prysm/bazel-out/k8-fastbuild/bin/third_party/kafka/librdkafka
PWD=/home/j/.cache/bazel/_bazel_j/4f4fbc31f3566532ef3b804d1113524c/sandbox/linux-sandbox/539/execroot/prysm
BUILD_TMPDIR=/tmp/tmp.5SwdXnw9aS
TMPDIR=/tmp
EXT_BUILD_DEPS=/tmp/tmp.qm6V74PtyM
SHLVL=2
BUILD_LOG=bazel-out/k8-fastbuild/bin/third_party/kafka/librdkafka/logs/CMake.log
BUILD_SCRIPT=bazel-out/k8-fastbuild/bin/third_party/kafka/librdkafka/logs/CMake_script.sh
PATH=/home/j/.cache/bazel/_bazel_j/4f4fbc31f3566532ef3b804d1113524c/sandbox/linux-sandbox/539/execroot/prysm:/bin:/usr/bin:/usr/local/bin
_=/usr/bin/env
__________________________bazel-out/k8-fastbuild/bin/third_party/kafka/librdkafka/logs/CMake_script.sh: line 51: /tmp/tmp.qm6V74PtyM/bin/cmake/bin/cmake: No such file or directory

_____ END BUILD LOGS _____
rules_foreign_cc: Build script location: bazel-out/k8-fastbuild/bin/third_party/kafka/librdkafka/logs/CMake_script.sh
rules_foreign_cc: Build log location: bazel-out/k8-fastbuild/bin/third_party/kafka/librdkafka/logs/CMake.log

Target //beacon-chain:beacon-chain failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/j/prysm/beacon-chain/BUILD.bazel:80:1 error executing shell command: '/bin/bash -c function cleanup_function() {
local ecode=$?
if [ $ecode -eq 0 ]; then
cleanup_on_success
else
cleanup_on_failure
fi
}
set -e
function cleanup_on_success() {
printf "rules_foreign_cc: ...' failed (Exit 127) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 196.387s, Critical Path: 13.68s
INFO: 537 processes: 537 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by positivenoise** [comment] 2020-01-01 17:22
Hello fellow human,
I also encountered this, you need to install cmake. Resolve it with `sudo apt install cmake`
Enjoy!

**Comment by prestonvanloon** [comment] 2020-01-03 19:17
Duplicate of #4283. Please install cmake locally or disable kafka as recommended here https://github.com/prysmaticlabs/prysm/issues/4283#issuecomment-566884428

**Closed by prestonvanloon** 2020-01-03 19:17 UTC
