### ISSUE TITLE
ERROR validator: Could not request attestation to sign at slot error=rpc error: code = DeadlineExceeded

### ISSUE THREAD

**Issue by GuillaumeOcculy** [prysmaticlabs/prysm#4939] opened 2020-02-24 21:15 UTC
I still got this error after running : 
```go
docker run -d -it -v $HOME/prysm/validator:/data --network="host"   gcr.io/prysmaticlabs/prysm/validator:latest   --beacon-rpc-provider=127.0.0.1:4000   --keymanager=keystore --keymanageropts='{"path":"/data","passphrase":"changeme"}'
```

```go
[2020-02-24 21:07:21]  INFO validator: New assignment attesterSlot=330346 committeeIndex=6 epoch=10323 pubKey=0x92612e5ca5ad status=ACTIVE validatorIndex=35211
[2020-02-24 21:09:24] ERROR validator: Could not request attestation to sign at slot error=rpc error: code = DeadlineExceeded desc = context deadline exceeded pubKey=0x92612e5ca5ad slot=330346
[2020-02-24 21:13:36]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=10323 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.078286462 oldBalance=3.078298795 percentChange=-0.00040% pubKey=0x92612e5ca5ad9ca0
```

**Comment by prestonvanloon** [comment] 2020-03-06 06:42
These issues are very difficult to identify root cause. In short, the beacon chain node took too long to generate the attestation data to sign. 

We should take a look at these deadlines to see if they could be tweaked. Currently, the client requires the request to complete within the same slot. Maximum of 12 seconds. 

Another idea would be to retry this request repeatedly until the epoch is over. That may make the issue worse for users running multiple validators

**Comment by prestonvanloon** [comment] 2020-03-31 04:34
This is a bit of an ongoing issue which stems mostly from poor performance with HashTreeRoot, memory management, and optimized aggregation. 

Tenatively assigning to @nisdas as the owner of feature flag `--enable-state-trie-cache` which will improve hash tree root performance. 

#4838 may help as well.

**Comment by rauljordan** [comment] 2020-04-14 17:39
This is now resolved by our revamped hash tree root cache enabled by default in master, closing

**Closed by rauljordan** 2020-04-14 17:39 UTC
