### ISSUE TITLE
Slasher kills beacon node: dropping peers

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5812] opened 2020-05-11 15:12 UTC
# 🐞 Bug Report

### Description

It has been reported by a few users (ex: `Haxington`) that slasher kills beacon node with attached validators. Opening up this issue for tracking.

Chat link for reference: https://discordapp.com/channels/476244492043812875/476588476393848832/708479430565167105

**Comment by rauljordan** [comment] 2020-05-15 15:28
@0xKiwi can we close? this was resolved by your fix to slasher right, can you link the PR?

**Comment by 0xKiwi** [comment] 2020-05-15 15:41
> @0xKiwi can we close? this was resolved by your fix to slasher right, can you link the PR?

Hey @rauljordan, I haven't been able to replicate this. Maybe #5782 gated the root cause of this though.

**Comment by rauljordan** [comment] 2020-05-15 16:31
This is a duplicate of #5854 ,  causing OOMs and peers to all drop to 0

**Closed by rauljordan** 2020-05-15 16:31 UTC
Labels: Bug, Priority: Medium, Slasher
