### ISSUE TITLE
Implement Precise Ticker for Slot Interval

### ISSUE THREAD

**Issue by rawfalafel** [prysmaticlabs/prysm#511] opened 2018-09-13 02:55 UTC
**Background**
In the current spec, new blocks are allowed to advance the chain every `slotDuration` seconds. As a concrete example, if the genesis block is published at time `T`, the first block can be published at time `T+slotDuration`, the second block time `T+2*slotDuration`, etc. Prysm currently has a naive implementation that uses the standard library [Ticker](https://golang.org/pkg/time/#NewTicker), but it has two issues. 

1. The clock doesn't tick precisely at `T+N*slotDuration`, where `N` is a non-negative integer. This means that the ticker will be "off beat" from the correct beat, even if the interval length is correct.
2. The clock may drift over time. The ticker uses a monotonic clock, meaning that it won't adjust to miniscule inaccuracies in the interval length. This is an issue if we expect the beacon chain to run for days/weeks/months.

**Requirements**
Replace the current naive ticker with a ticker that addresses both issues above. It's probably best to confirm that clock drift is an issue, although [this thread](https://github.com/golang/go/issues/19810) seems to confirm that it is. The thread also contains a sample solution by Russ Cox -- that may be helpful :smiley:

**Comment by danielschonfeld** [comment] 2018-09-14 01:27
@rawfalafel are you referring to `SLOT_DURATION` instead of `cycleLength` ?

**Comment by rawfalafel** [comment] 2018-09-14 01:44
>@rawfalafel are you referring to `SLOT_DURATION` instead of `cycleLength` ?

@danielschonfeld yeah, thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danielschonfeld** [comment] 2018-09-14 02:06
I am no expert on this, but from reading Russ Cox's comments and code examples, it seems to me that both him and the original OP come to agreement that there is no drift problem with go or their ticket implementation.  It seems that the problem is between the virtualized environment (Azure VM in this case) and the real world clock.

Russ also goes on to say that Go's implementation will generally stay loyal to the start time its aligned to.

Having that said, raises two questions:

1) Do you agree with my assertion? If not, please explain
2) If you do agree, the next question is whether or not we should go the extra length to account and adjust for virtualized environments unpredictability?

**Comment by rauljordan** [comment] 2018-09-18 04:32
Could be useful perhaps to check NTP at each cycle transition as that is a sensitive point for all beacon clients

**Comment by rauljordan** [comment] 2018-10-10 16:33
Closed by #635

**Closed by rauljordan** 2018-10-10 16:33 UTC
Labels: Bug, Good First Issue
