### ISSUE TITLE
Becaon node panic after node restart

### ISSUE THREAD

**Issue by ppratscher** [prysmaticlabs/prysm#4099] opened 2019-11-24 19:44 UTC
After restarting the node it continuously panics with the following error:
```
time="2019-11-24 19:43:12" level=info msg="Minimum number of validators reached for beacon-chain to start" ChainStartTime=2019-11-11 16:28:02 +0000 UTC prefix=powchain
time="2019-11-24 19:43:14" level=info msg="Waiting for enough peer handshakes before syncing" handshakes="0/1" prefix=initial-sync
time="2019-11-24 19:43:16" level=info msg="New peer connected" peer=16Uiu2HAkvznEZLYtSFYqSSDteMvek2RVx3vhw6DRBNs2bymCVyDA prefix=p2p
time="2019-11-24 19:43:20" level=info msg="Processing block 94481/94576 - estimated time remaining 31m40s" blocksPerSecond=0.1 peers="1/1" prefix=initial-sync
time="2019-11-24 19:43:20" level=info msg="Processing block 94481/94576 - estimated time remaining 15m50s" blocksPerSecond=0.1 peers="1/1" prefix=initial-sync
panic: could not process blockCopy from fork choice service: pre state of slot 94481 does not exist

goroutine 173 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).Start(0xc000295860)
	beacon-chain/sync/initial-sync/service.go:132 +0xf1c
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
	shared/service_registry.go:44 +0x23e
```

In order to avoid any unclean shutdown our process manager has a grace period of 5 minutes before killing the process. Unfortunately we don't have any logs prior to the restart.

In order to get rid of the panic we had to delete the db and re-sync the node from scratch.

**Comment by torfbolt** [comment] 2019-11-25 22:38
Can confirm, same problem here after node restart.

**Comment by ppratscher** [comment] 2019-11-26 13:06
Same issue happened today with our node again (latest master).

**Comment by prestonvanloon** [comment] 2019-11-28 04:49
What's interesting about these is that it seems you have two blocks at the same slot. Given that these are close to the head of the chain and some of the finality reversions we have seen this week, I think this might be prevented with #4137. 

However, I still think we need a resolution here. I suggest that once we have synced to finality, if there are any issues in syncing blocks after the finalized epoch then we should just jump to regular sync and sync backwards from there as needed.

I'll submit a fix for this.

**Comment by rauljordan** [comment] 2020-01-08 02:30
Duplicate of https://github.com/prysmaticlabs/prysm/issues/4412

**Closed by rauljordan** 2020-01-08 02:30 UTC
Labels: Bug, Priority: High
