### ISSUE TITLE
Metrics: validator balance returned as 0 on activated validator when node restart 

### ISSUE THREAD

**Issue by GuillaumeMiralles** [prysmaticlabs/prysm#5746] opened 2020-05-05 09:01 UTC
# 💎 Issue

### Background

I am trying to create a grafana dashboard that everybody could use. There is only one thing that bothers me actually in the metrics returned to Prometheus, is that when the node restart while the validator client is still running, all the validators have their balance set to 0

### Description
Run the node, run the validator client. Then after a while restart the node. Check the validator client metrics (http://localhost:8081/metrics) and see it being set to 0. I would expect to receive the last known validator balance, or just no data, but not a false returned validator balance instead

This create unwanted behavior on my dashboard and I haven't find a way to workaround it for the earning panels in a time frame on this dashboard: 
https://gist.github.com/GuillaumeMiralles/ef8617bd8cb245f25a1e384613ec1303

Validator client metrics before to restart the node: 
![metrics before restart](https://user-images.githubusercontent.com/23481418/81050355-21ca6a00-8ec0-11ea-90fa-c82e2544e9b0.png)

Validator client log when restarting the node: 
![log on restarting node](https://user-images.githubusercontent.com/23481418/81050407-34dd3a00-8ec0-11ea-8e27-40e4503c55c9.png)

Validator client metrics after to restart the node: 
![metrics after restart](https://user-images.githubusercontent.com/23481418/81050401-33ac0d00-8ec0-11ea-9a05-c4da8e90bf64.png)

**Comment by prestonvanloon** [comment] 2020-05-09 19:49
I don't think this is an API issue, but a metrics reporting issue in the validator client. If the validator balance is unknown, it should not be updated as zero.

**Comment by terencechain** [comment] 2020-05-09 20:21
The core problem here is why the validator client is requesting beacon node for blocks and attestations when it knows the beacon node is not yet at head. See you have errors:
```
Syncing to latest head, not yet ready to respond...
```


Validator should be blocking like this:
```
[2020-05-09 13:19:30]  INFO validator: Beacon chain started genesisTime=2020-04-17 17:00:00 -0700 PDT
[2020-05-09 13:19:36]  INFO validator: Waiting for beacon node to sync to latest chain head
[2020-05-09 13:19:42]  INFO validator: Waiting for beacon node to sync to latest chain head
[2020-05-09 13:19:48]  INFO validator: Waiting for beacon node to sync to latest chain head
```

**Comment by prestonvanloon** [comment] 2020-05-09 20:33
I disagree. Look at this bit of code
https://github.com/prysmaticlabs/prysm/blob/cf98de86f43d4a82b31ba3e3b5ba605f61a6d613/validator/client/validator_metrics.go#L69-L75

This should be using DeleteLabelValues(fmtKey) instead of setting it to 0.

**Comment by terencechain** [comment] 2020-05-09 20:43
No. These are not missing validators. They are active validators. 

Ok I found a way to reproduce this. @GuillaumeMiralles didn't post the instructions but i found a way to reproduce it.

Typically:
1.) Node starts
2.) Validator starts
3.) Validator blocks until node syncs to head. In this case validators balances will just be unknown

In @GuillaumeMiralles case:
1.) Node and validator are in sync to begin with
2.) Node restarts and validator loses connect
3.) After validator reconnects to the node, validator should run `WaitForSynced` before requesting for blocks and attestations

It is an edge case we should consider. Validator balances will show up as NA instead of 0

**Comment by prestonvanloon** [comment] 2020-05-09 21:01
So the API is reporting 0? What does the response look like?

**Comment by prestonvanloon** [comment] 2020-05-09 21:12
When I try to access a validator by index that doesn't exist yet because my node hasn't synced fully, this is what I get
```
{
  "error": "11 OUT_OF_RANGE: Validator index 25000 does not exist in historical balances"
}
```

Interestingly, when I try to request by public keys when the node is still syncing, I get a default response of the first 250 validators which would trigger that "missing validator" code path. 

I don't think the root of the problem here is necessarily the API. While we should reject API response while syncing for validator balances, it is inappropriate to say "a validator's balance is 0 in the state" simply when they are missing from the response. Their balance isn't 0, it is nothing, they don't exist.

**Comment by terencechain** [comment] 2020-05-09 21:28
> When I try to access a validator by index that doesn't exist yet because my node hasn't synced fully, this is what I get
> 
> ```
> {
>   "error": "11 OUT_OF_RANGE: Validator index 25000 does not exist in historical balances"
> }
> ```
> 
> Interestingly, when I try to request by public keys when the node is still syncing, I get a default response of the first 250 validators which would trigger that "missing validator" code path.
> 
> I don't think the root of the problem here is necessarily the API. While we should reject API response while syncing for validator balances, it is inappropriate to say "a validator's balance is 0 in the state" simply when they are missing from the response. Their balance isn't 0, it is nothing, they don't exist.

Yeah. I think theres two issues here.
1.) Validator local metrics need better interpretation on what `0` means
2.) Beacon node needs to return `Unavailable` for performance request when it's syncing.
See https://github.com/prysmaticlabs/prysm/pull/5795

**Comment by terencechain** [comment] 2020-05-12 18:55
Given the merge of #5795 I think we can close this given we've done all we can to fix it from prysm side. Anything else to add? @GuillaumeMiralles

**Comment by GuillaumeMiralles** [comment] 2020-05-12 20:45
From what I can read on #5795 it seems that 0 will not be returned anymore, but instead nothing will be. Which is totally fine for me. 
If what I described is correct, then yes we can close this issue.

Thanks for your work! :)

**Closed** 2020-05-12 23:05 UTC
Labels: Bug, Help Wanted
