### ISSUE TITLE
fatal error + enormous stack trace

### ISSUE THREAD

**Issue by uvizhe** [prysmaticlabs/prysm#5510] opened 2020-04-19 13:07 UTC
# 🐞 Bug Report

### Description

I run prysm during topaz testing and it just crashed.
### Has this worked before in a previous version?

IDK

## 🔬 Minimal Reproduction

IDK

## 🔥 Error

Here is the long stack trace I got: https://gist.github.com/uvizhe/7768520bdc04026124bc8df875d10f24

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
GNU/Linux 4.15.0-91-generic
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.0-alpha.4
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
`pubKey=0x8425ad522ac0eaf3bf099621399aeb67250f8c0b7c4147fc0bb175cf81db142f2f953451e7df2dda101a2eaa889793b8`

**Comment by HD125823** [comment] 2020-04-19 15:52
Can confirm, had the same fatal error (with huge stack trace) at slot 11357.

**Comment by 0xKiwi** [comment] 2020-04-19 20:48
Hello @uvizhe ! Thanks for reporting this issue. What distro of linux are you running, or are you using the windows WSL?

**Comment by uvizhe** [comment] 2020-04-20 10:34
I'm on Ubuntu 18.04.4 LTS

**Comment by prestonvanloon** [comment] 2020-04-21 03:38
Duplicate of #5513

**Closed by prestonvanloon** 2020-04-21 03:38 UTC
Labels: Bug
